### ISSUE TITLE
Include real initData and Clear Key license in the Clear Key example

### ISSUE THREAD

**Issue by ddorwin** [w3c/encrypted-media#10]
The example at https://w3c.github.io/encrypted-media/#example-source-and-key-known does not include the actual data. For completeness and to allow a reader to actually use the example, it should be complete, including having valid initData (maybe switch to "keyids") and a valid Clear Key license.

**Comment by ddorwin** [comment]
We need realistic values first (issue #34).

**Comment by paulbrucecotton** [comment]
Assigned to Mark at the Jul 7 meeting.
http://www.w3.org/2015/07/07-html-media-minutes.html#item03

**Comment by ddorwin** [comment]
#34 is now fixed. Assigning to Mark per the last comment. Please use the same values you added in #34.

**Comment by ddorwin** [comment]
I just reopened #34, so we may need to re-resolve that first.
