### ISSUE TITLE
Define what to do when CDM becomes unavailable

### ISSUE THREAD

**Issue by ddorwin** [w3c/encrypted-media#102]
Originally filed by @cpearce in [bug 27067](https://www.w3.org/Bugs/Public/show_bug.cgi?id=27067). See the original bug for the history.

We need to re-evaluate how this relates to the current spec text and propose specific changes to the current text. This is related to interoperability but in an unlikely case. I believe it is low priority at the moment.

**Comment by cpearce** [comment]
The behaviour that I implemented in Firefox is when we detect that the CDM has become unusable or crashed, we fire an "error" event at the HTMLMediaElement, abort the media load algorithm, abort any EME algorithms running and reject their promises, mark all MediaKeySessions as closed and resolve their "closed" promises. This last step results in subsequent calls to MediaKeySession methods rejecting with an InvalidStateError.

I don't think we need to be to complicated here. This case should be rare. Most video playback sites already listen on the HTMLMediaElement "error" event and respond by putting up a "please reload page and try again", so we should piggyback on that behaviour.

**Comment by ddorwin** [comment]
That sounds reasonable, though I believe it is the _resource selection algorithm_ we want to abort (see also #112).

Failure of the CDM instance is unrecoverable (different from just keys being unavailable), so aborting `HTMLMediaElement` algorithm(s) seems appropriate.
<br/>
**Specification of this behavior**

From an EME spec perspective, the `HTMLMediaElement` behavior should be initiated from within the Encrypted Block Encountered algorithm because that is where the the _cdm_ is used. The specific text should be similar to that discussed in issue #112. Where exactly to add this text is tricky as @cpearce pointed out in [comment 12](https://www.w3.org/Bugs/Public/show_bug.cgi?id=27067#c12) of the original bug. (It is also possible for implementations to initiate this behavior at other points, such as processing clear blocks, when the CDM comprises other parts of the media pipeline, such as decoding. Those cases should be covered by the main spec.)

Aborting and rejecting any in-process EME methods should be handled by the existing "If [any of ]the preceding step[s] failed" steps.

Closing all `MediaKeySession`s should be handled by invoking the Session Close algorithm. This will resolve the `closed` promise, prevent most methods from being called (via "If the Session Close algorithm has been run on this object" checks; see also #113), and ensure other behaviors are consistent (avoiding issues like #112). For clarity, we should add text referencing such situations in the introduction to the Session Close algorithm.

**Comment by ddorwin** [comment]
If there is agreement, we can move to _needs implementation_.

**Comment by steelejoe** [comment]
This seems reasonable to me, but would like to see confirmation from Chris and Jerry if possible.

**Comment by paulbrucecotton** [comment]
The Sapporo F2F attendees agree with @cpearce's proposal as re-stated by @ddorwin .

**Comment by steelejoe** [comment]
Following up on the request for author feedback, I received nothing negative. Everyone agrees this should be a fairly uncommon edge case, but should still be handled.

**Comment by ddorwin** [comment]
@paulbrucecotton wrote:
> @ddorwin: How does your proposal handle step "This last step results in subsequent calls to MediaKeySession methods rejecting with an InvalidStateError." as proposed by Chris?

I believe this is covered by the last paragraph in my proposal. The session is closed, which causes the "If the Session Close algorithm has been run on this object" steps to run. Except for `close()`, this results in `InvalidStateError`. Am I misunderstanding?

**Comment by mwatson2** [comment]
Keeping this open for review of the changes in 8fa55bb6e019822cece22a7d58a5016efee7c9b8

**Comment by mwatson2** [comment]
Any further comments on this ?

**Comment by steelejoe** [comment]
I did not see any changes to the pull as a result of Chris's comments. Perhaps I am not looking at the right one? I agree with Chris that this case can also arise during the decrypt phase and should be dealt with there. His suggestion to pull the text into a common algorithm and refer to it in both places makes sense to me also.

**Comment by mwatson2** [comment]
@steelejoe I interpreted Chris's comment as suggesting the cleanup steps be run on decrypt failure and replied that decrypt failure doesn't imply the CDM is unusable. However, I can see that we might want to say "If the CDM is unusable", run those steps, or ensure that this qualified procedure is applicable at any time.

**Comment by steelejoe** [comment]
@mwatson2 I believe the correct approach would be to check if the CDM is unusable in that case and then run the steps. That was my interpretation.

**Comment by ddorwin** [comment]
For future reference, "Chris's comments" are in the first commit (8fa55bb).

Although not as important as the HTMLMediaElement behavior addressed by these two commits, the spec may not currently address closing of sessions when the CDM becomes unavailable in other cases. This could include during other algorithms or completely asynchronously in an implementation-specific way (i.e. a broken pipe is detected).

The [Session Close](https://w3c.github.io/encrypted-media/#session-close) algorithm does not specifically cover this as a case when it should be called. Also, while we handle failures in the CDM steps of the other algorithms with "If any of the preceding steps failed, reject _promise_...", this does not cause the sessions to be closed.

One option would be to add a "Close all sessions" algorithm similar to what Chris suggested and state that it is called whenever the CDM is no longer usable for any reason. We could move the second sub-step from each of the above commits to that algorithm and call it instead.

**Comment by mwatson2** [comment]
I have added a "Close all Sessions" algorithm to MediaKeys as suggested. Please re-open if there are any problems with the changes.
