### ISSUE TITLE
InvalidAccessError usage is questionable

### ISSUE THREAD

**Issue by ddorwin** [w3c/encrypted-media#103]
Originally filed by @domenic in [bug 27283](https://www.w3.org/Bugs/Public/show_bug.cgi?id=27283). See the original bug for the history. @domenic also filed related [bug 27284](https://www.w3.org/Bugs/Public/show_bug.cgi?id=27284) asking whether `InvalidAccessError` be should discouraged.

Many uses of `InvalidAccessError` relate to empty parameters. If `TypeError` is more appropriate, we should switch those. (@domenic, is there a definition of `TypeError`? I could not find one in Web IDL.)

However, there are others related to invalid string values and even data that cannot be sanitized. (Some of those were added since the original bug was last updated.) We need to determine appropriate exception names for these.

**Comment by domenic** [comment]
TypeError is defined in https://tc39.github.io/ecma262/#sec-native-error-types-used-in-this-standard-typeerror. It is the "default" error type, for cases when something goes wrong and you don't expect authors to do any switching logic on `err.name`. It's not just used for type-system errors as you might expect. Invalid values of any type generally fit under TypeError (unless you really want to call out a specific facet of their invalid-ness for authors to switch on and recover from). IIUC, so would data that cannot be sanitized.

I'll try to add something to https://w3ctag.github.io/design-principles/ soon since this has come up a couple times.

**Comment by ddorwin** [comment]
@domenic Thanks, that is really helpful. ("Indicates the actual type of an operand is different than the expected type" in the tc39 link does not convey that. ;) )

**Comment by ddorwin** [comment]
I think this is now ready for someone to replace all the low-hanging fruit, so I'm marking it needs implementation. We can then remove that label and re-evaluate the remaining uses.

**Comment by domenic** [comment]
>  ("Indicates the actual type of an operand is different than the expected type" in the tc39 link does not convey that. ;) )

Hah, very true. Filed https://github.com/tc39/ecma262/issues/93.

**Comment by mwatson2** [comment]
Sent from my iPhone

On Oct 19, 2015, at 5:43 PM, Domenic Denicola <notifications@github.com>
wrote:

("Indicates the actual type of an operand is different than the expected
type" in the tc39 link does not convey that. ;) )

Hah, very true. Filed tc39/ecma262#93
<https://github.com/tc39/ecma262/issues/93>.

It depends what you mean by 'Type'. At its most general a type is the set
of allowed values of a variable and with that definition the text above
covers a very wide variety of ills.

But obviously people often think of type as one of a very small number of
well-known sets (ints, floats, etc.)

—
Reply to this email directly or view it on GitHub
<https://github.com/w3c/encrypted-media/issues/103#issuecomment-149386561>.

**Comment by mwatson2** [comment]
The above commit changes all but the two InvalidAccessErrors identified in the original bug thread to TypeErrors. @domenic suggests those two should be RangeErrors. Shall we change those as well ?

**Comment by ddorwin** [comment]
(Apologies for not getting to this sooner. It was on my backlog.)

`RangeError`'s [definition in ES6](http://people.mozilla.org/~jorendorff/es6-draft.html#sec-native-error-types-used-in-this-standard-rangeerror) is:
>Indicates a value that is not in the set or range of allowable values.

This seems odd for the two conditions where it is now used:

1. `remove()` is called on the wrong type of session.
1. `update()` is called with a server response that is incompatible with the session type.

For (1), I suppose the session type could be out of range, but that is the result of `createSession()` and nothing to do with `remove()`. `"NotSupportedError"` or `"InvalidStateError"` seem better. Really, though, `"InvalidAccessError"` ("The object does not support the operation or argument.") seems very appropriate.

(2) is also related to the type specified when the session object was created. At least in this case the input causes the error. However, it's hard to say that there is a "set or range of allowable values" that can be passed. (It is really infinite.) The following seem better:
* `"DataError"`:  "Provided data is inadequate."
* `"OperationError"`: "The operation failed for an operation-specific reason."

@domenic, thoughts?

**Comment by mwatson2** [comment]
@domenic Is it the case that `InvalidAccessError` is deprecated even for cases that meet the definition "The object does not support the operation or argument." ?

For (2) I can see `RangeError` being ok: the sat of allowed values isn't infinite in practice (most implementations will have an upper bound on the message length. At least, messages longer than available memory probably aren't supported) and even if it was infinite, this is a case where the provided value is not in that infinite set.

**Comment by domenic** [comment]
@mwatson2 indeed, given that definition overlaps with TypeError and RangeError I cannot see any use case for InvalidAccessError.

It's OK for RangeError to be used for infinite sets of allowed values, as long as there is a clearly defined out of range concept. For example, RangeError is appropriate when only positive integer values are allowed (of which there are, at least theoretically, an infinite number).

For (1), TypeError makes sense; if I understand correctly, it's being called on the wrong type.

One other issue is that https://github.com/w3c/encrypted-media/commit/1b048ee2401b18d4b62b6c13ddc166ebdf2ac5ec is a little strange; it seems to be trying to define a new RangeError type besides the one that already exists in ES? I guess this spec does that for TypeError too?

**Comment by mwatson2** [comment]
Actually, in (1) it is not the wrong data type (in the sense of a `TypeError`) but the wrong session type, where session type is a specific EME concept. It's not a `RangeError` because it's not the arguments that are wrong. It's not 'not supported' in the sense of a function which in principle could be supported but the implementation doesn't support it, but it is 'not supported' in the more general sense that this operation doesn't work on objects with this particular setting of the sessionType attribute.

**Comment by ddorwin** [comment]
As @mwatson2 said, (1) is not based on the object type but on a property ("session type") of the object that was set at creation time. We really want to convey that "You can't do that to this object instance even though it is possible on some objects of the same type."

(2) is similar in that the data (instead of the method called) is incompatible with that same object property that was set at creation time. We really want to convey that "This data is incompatible/invalid for this object instance even though it is reasonable on some objects of the same type."

I'm most concerned that these make sense to an author. I guess we can convey the details in the message, but it seems odd to say that an opaque binary blob of data "is not in the set or range of allowable values."

@domenic, 1b048ee follows in the existing pattern. See https://w3c.github.io/encrypted-media/#exceptions. This doesn't redefine the types, it just lists the ones used in this spec. IIRC, this followed the pattern in http://www.w3.org/TR/WebCryptoAPI/#SubtleCrypto-Exceptions. (Note that WebCrypto has reverse referencing for definitions, making the list perhaps even more useful. Does ReSpec support that?) I'm not attached to this section if you think it should be removed.

**Comment by domenic** [comment]
> (1) is not based on the object type but on a property ("session type") of the object that was set at creation time. We really want to convey that "You can't do that to this object instance even though it is possible on some objects of the same type."

That's fine; as discussed the "type" in "type error" doesn't really have anything to do with the object's `.constructor` or similar.

>  We really want to convey that "This data is incompatible/invalid for this object instance even though it is reasonable on some objects of the same type."

This sounds like a TypeError to me now?

In general it's not that I love TypeError so much, it's just that InvalidAccessError is strictly subsumed by it, and as such I am trying to get InvalidAccessError deprecated. Maybe there is an even better match in all these cases. My main concern is that it's not InvalidAccessError.

> 1b048ee follows in the existing pattern. See https://w3c.github.io/encrypted-media/#exceptions. This doesn't redefine the types, it just lists the ones used in this spec.

I see. The only problem then is that TypeError and RangeError are not "DOMException names from WebIDL" and when you use them you will not be "rejecting the returned promise with a DOMException". Now that I see the section I think it's a reasonable one in general; just a nit.

**Comment by mwatson2** [comment]
So, should we change these both to TypeError ?

I think the misuse of the DOMException term is widespread in the spec and should be fixed separately.

**Comment by ddorwin** [comment]
I filed #138 to fix `TypeError`.

@domenic, to be clear, I wasn't pushing for `InvalidAccessError`. I'm fine with replacing it. `TypeError` seems odd and unhelpful to the user. However, as you said above, "It is the "default" error type, for cases when something goes wrong and you don't expect authors to do any switching logic on `err.name`," and these two cases really are application bugs, so we don't expect any such switching.

We could debate more appropriate DOMException names, but `TypeError` is fine.
