### ISSUE TITLE
EME registry: Establish a update process & home

### ISSUE THREAD

**Issue by ddorwin** [w3c/encrypted-media#104]
We need to establish a permanent location for the non-REC track EME registry as was done for the MSE registry [MSE bug 25581](https://www.w3.org/Bugs/Public/show_bug.cgi?id=25581).

@plehegar

**Comment by ddorwin** [comment]
Before we publish to a new URL, we should finalize the file structure: issue #105.

**Comment by paulbrucecotton** [comment]
@plehegar:  How do we make progress on Issues 104 and 105?

**Comment by plehegar** [comment]
@paulbrucecotton sorry, I've been swamped. If I don't make progress by Tuesday, I'll ask @yfuna if he can help.

**Comment by plehegar** [comment]
The publication system isn't up to the task unfortunately. I'll set an alternative solution within 2 weeks.

**Comment by plehegar** [comment]
How about the following https://github.com/w3c/encrypted-media/pull/147 ?

Basically, all the files would appear under https://www.w3.org/html/media/

**Comment by paulbrucecotton** [comment]
Can we also fix the current WD reference fro [EME-REGISTRY] that currently contains an incorrect URL that generates a 404?

[EME-REGISTRY]

David Dorwin; Adrian Bateman; Mark Watson. [Encrypted Media Extensions Stream Format and Initialization Data Format Registry](https://www.w3.org/TR/encrypted-media/initdata-format-registry.html). URL: initdata-format-registry.html

**Comment by plehegar** [comment]
As soon the PR is merged, it will generate a new WD that will have the proper link.
If someone is willing to give a +1, I'll do the merge.

**Comment by ddorwin** [comment]
I think we should resolve #105 first so that the new paths are the permanent paths.

**Comment by jdsmith3000** [comment]
My initial take was that this proposal was straightforward, but it seems an awkward split for ISOBMFF and CENC, which are closely coupled.  Can you expand on scenarios you have in mind that would require this restructuring?

**Comment by ddorwin** [comment]
See #105 for the "correctness" reason and #106 for the practical reason.

**Comment by plehegar** [comment]
Update on this front: Automatic publication will support Working Group notes within 10 days. So, I now feel comfortable recommending that path again since it will be easy to update the drafts. We should:
1. be ok that we want the registries as Working Group Notes
2. be ok with plh taking a snapshot and push those manually for the first publication
3. be ok with plh setting up the automatic publishing system on every commit for those documents.

**Comment by paulbrucecotton** [comment]
@plehegar:  Since no one has expressed concern about your three items above can we proceed with publication of the WG Notes?

**Comment by ddorwin** [comment]
Let me land PR #167 for #105 first.

There will be some work necessary to get the links between the WD and Notes version of the spec and registry, respectively, to point to each other. Currently, the ED of both reference each other correctly.

**Comment by ddorwin** [comment]
The new structure has been merged.

**Comment by paulbrucecotton** [comment]
@plehegar expects to publish the non-REC track EME registry on Mon May 2.  When that is done this issue will be closed.

**Comment by plehegar** [comment]
I'm still working on updating the JS to generate proper references. The locations will look like:

https://www.w3.org/eme-initdata
https://www.w3.org/eme-initdata-cenc
https://www.w3.org/eme-initdata-webm
https://www.w3.org/eme-initdata-keyids
https://www.w3.org/eme-stream
https://www.w3.org/eme-stream-mp4
https://www.w3.org/eme-stream-webm

**Comment by paulbrucecotton** [comment]
I assume the above URLs will continue to return 404 until they are published on the TR page next week.

**Comment by plehegar** [comment]
correct. We're on track for publication on May 10.

**Comment by plehegar** [comment]
And we shipped. Next step is to make sure the /TR docs get updated on commits in this repo.

**Comment by paulbrucecotton** [comment]
@plehegar - Since these documents have been published<https://www.w3.org/blog/news/archives/5392>, I believe we can close this issue.

**Comment by ddorwin** [comment]
@plehegar:

1. The URLs [above](https://github.com/w3c/encrypted-media/issues/104#issuecomment-216513561) do not work. Only dated URLs like https://www.w3.org/TR/2016/NOTE-eme-stream-webm-20160510/ were pubished.
1. The registry URLs in the published spec (i.e. for WD and later maturities) are still relative rather than pointing to https://www.w3.org/TR/eme-initdata, etc. See https://www.w3.org/TR/encrypted-media/#bib-EME-INITDATA-REGISTRY. This likely needs to be fixed in `encrypted-media.js`, but it also depends on the first item.

**Comment by plehegar** [comment]
The exact links are
https://www.w3.org/TR/eme-initdata-registry
https://www.w3.org/TR/eme-initdata-cenc
https://www.w3.org/TR/eme-initdata-webm
https://www.w3.org/TR/eme-initdata-keyids
https://www.w3.org/TR/eme-stream-registry
https://www.w3.org/TR/eme-stream-mp4
https://www.w3.org/TR/eme-stream-webm

**Comment by plehegar** [comment]
The fix tries to use relative links with it's an ED and use /TR links when it's not.
