### ISSUE TITLE
EME registry: Separate definitions of Initialization Data Types from Stream Format parsing

### ISSUE THREAD

**Issue by ddorwin** [w3c/encrypted-media#105]
Originally filed as [bug 26811](https://www.w3.org/Bugs/Public/show_bug.cgi?id=26811).

In summary, the EME registry was created before Initialization Data Types were created. Now, the MIME type and Initialization Data Type are different and may be independent. Thus, we should have separate registries.

I believe we should also put the registries in their own directories. This will make publishing the registry separate from the EME spec (issue #104) easier and shorten all the filenames. For example:
```encrypted-media\
  ...
  registry\
    stream-format\
      bmff.html
      webm.thml
      ...
    initdata-format\
      cenc.html
      webm.thml
      ...
```

**Comment by ddorwin** [comment]
@plehegar FYI related to how this will be published.

**Comment by paulbrucecotton** [comment]
@plehegar - Any update on your work on this item?
See the Sapporo minutes where you agreed to review this:
http://www.w3.org/2015/10/30-html-media-minutes.html#item26

**Comment by plehegar** [comment]
@paulbrucecotton I should get around this within 2 weeks

**Comment by ddorwin** [comment]
This issues is really on me to break these up.

Any comments from the community on the proposed structure?

**Comment by boblund** [comment]
I proposed a structure here https://www.w3.org/Bugs/Public/show_bug.cgi?id=26811#c3 for a cenc init doc and a BMFF encapsulation doc. Another proposal https://www.w3.org/Bugs/Public/show_bug.cgi?id=26738#c21 uses the cenc init doc with a proposed MPEG2TS encapsulation doc.

**Comment by ddorwin** [comment]
Thanks. I had in mind a more complete separation where each type of doc has different sections. I can create a PR, but it would be helpful to have feedback on the actual file structure before I start.

Separately, `bmff.html` might need to be `mp4.html` given the link to mime types.

**Comment by jdsmith3000** [comment]
I thought I commented here earlier, but my comment is missing.  Roughly restating it:  The ISOBMFF and CENC combination is pretty tightly coupled, and separating the specs doesn't seem useful.  Can you provide other cases where this separation is needed?

**Comment by ddorwin** [comment]
In the original EME draft, content type controlled both the processing of the media data and the format of the Initialization Data. Now, the `contentType` describes the stream and how the user agent will process it, and `initDataType` describes the format of the Initialization Data. While Initialization Data can come from a stream, it may also be provided independent of the stream, including in formats not supported by the `contentType` (e.g. `keyids`). I believe there is a pretty clear line (after section 2) between the two in the existing Stream Format and Initialization Data definitions.

The concrete case where this is needed (or at least very useful) today is #106.

There is tight coupling between ISOBMFF and ISO Common Encryption, but that is unrelated to this issue. The coupling is because we [decided](https://www.w3.org/Bugs/Public/show_bug.cgi?id=17673) to define "BMFF" (and `"video/mp4"`) as ISO BMFF that uses the ISO Common Encryption protection scheme rather than a more generic protection scheme-independent format. However, from EME's point of view, there is no relationship between that format and the format of Initialization Data with  the `initDataType` `"cenc"`.

**Comment by jdsmith3000** [comment]
I think I was mixing format encryption specifics and `initDataType` when I raised my previous concern.  If the scope of this change is to extract just the `initDataType` content and separately specify it, then that should be relatively straightforward.

I see the connection between this and issue #106, but wonder if this work is needed in V1.  At most, I would request that this issue be tagged V1NonBlocking in common with the specific use case that would benefit from the restructuring.

**Comment by ddorwin** [comment]
Thanks. I will generate a PR. The relationship to V1 is #104. It would be preferable to have the final structure before we publish the new location. Doing so later could result in dead external links.

**Comment by ddorwin** [comment]
I created #167 for this.

**Comment by ddorwin** [comment]
Are there any comments on the PR? If there are not any major issues, I will land this Monday and we can iterate as necessary.

**Comment by jdsmith3000** [comment]
I am reviewing these documents today and will comment later.

**Comment by jdsmith3000** [comment]
These look fine to me, and true to the previous registry content.  About the only addition that occurred to me in reviewing them was to explicitly state that initialization data can be distributed in either the stream or separately (e.g. the manifest).  The current language allows either, but doesn't explicitly acknowledge init data outside of the stream.

**Comment by ddorwin** [comment]
@jdsmith3000, I [added text](https://github.com/w3c/encrypted-media/pull/167/files#diff-fc96b26f0ed327a5dddaef6d75eb9860R94) to the initData registry abstract.

I also added references between the registries.

**Comment by jdsmith3000** [comment]
@ddorwin I reviewed these changes and they look good.  Thanks David.
