### ISSUE TITLE
Update Web IDL URLs to point to WebIDL Level 1.

### ISSUE THREAD

**Issue by ddorwin** [w3c/encrypted-media#107]
The spec has a reference to WebIDL-1, but it also uses features of Web IDL (Second Edition) and contains links to https://heycam.github.io/webidl/.

Known items include:
* Promises
* `iterable` (pending issue #75)
* All references to `DOMException` use https://heycam.github.io/webidl/
* "present" refers to https://heycam.github.io/webidl/

@plehegar for process issues. Also, @plehegar what's the best way to include a reference for something that is used throughout the spec or in the IDL?

**Comment by ddorwin** [comment]
Oops all of those appear to be covered by http://www.w3.org/TR/WebIDL-1/. Thus, we should update all URLs to use that version of the spec. I'll change the subject.

The question about where to add `[WebIDL]` remains.

**Comment by ddorwin** [comment]
In addition, conform that that all features we use are in Level 1. In addition to the https://heycam.github.io/webidl/ URLs, this should include checking all references for "WebIDL" (Look for exactly that string in the text.)

**Comment by plehegar** [comment]
For Level 1:

Promises:
 http://www.w3.org/TR/WebIDL-1/#idl-promise
Iterables:
 http://www.w3.org/TR/WebIDL-1/#idl-iterable
DOMException:
 http://www.w3.org/TR/WebIDL-1/#dfn-DOMException
present:
 http://www.w3.org/TR/WebIDL-1/#dfn-present

My suggestion is to keep the references to  https://heycam.github.io/webidl/ for now and do a separate overall analysis of the dependencies. Once we believe we're getting closed to stable for EME, that's when we should really worry about it. I'm willing to provide the analysis. I could do one for WebIDL now if you'd like me to but let's keep it separate from modified the draft for now.

**Comment by ddorwin** [comment]
Per the telecon today, we should point to the latest and greatest and only worry about this in PR. I'm fine with closing this issue knowing that process will make us address this before PR.

**Comment by plehegar** [comment]
I was able to confirm with one of the WebIDL Level 1 editors that EME does not make use of any non-Level 1 definition or feature.

**Comment by plehegar** [comment]
imho, this issue can be closed.

**Comment by ddorwin** [comment]
Thank you!
