### ISSUE TITLE
MediaKeyMessageEventInit has an interface member with a default value

### ISSUE THREAD

**Issue by bashi** [w3c/encrypted-media#11]
Section 6.3.3 defines `MediaKeyMessageEventInit` and its `message` member has a default value, but according to the WebIDL spec, it seems that we cannot specify a default value for an interface member.

http://heycam.github.io/webidl/#idl-interface

"There is no way to represent a constant object reference value for a particular interface type in IDL."

http://heycam.github.io/webidl/#prod-DefaultValue

`DefaultValue` rule is either a `ConstValue`, a string or an array.

A possible workaround is that explicitly saying that when `message` member is not present, initialize `message` property to an empty ArrayBuffer in section 6.3.2 or somewhere.

**Comment by ddorwin** [comment]
I just removed the default value. I don't think we need any prose in 6.3.2 - that just defines the attributes, not the construction. All construction in the algorithms always specifies a value for the `message` attribute. Any prose would probably be in 6.3.3, but I'm not sure if that's necessary or what it would say.

**Comment by bashi** [comment]
Makes sense. Thanks!
