### ISSUE TITLE
Get Supported Capabilities for Audio/Video Type: "media types" referenced before definition

### ISSUE THREAD

**Issue by ddorwin** [w3c/encrypted-media#111]
The following Note in the [Get Supported Capabilities for Audio/Video Type](https://w3c.github.io/encrypted-media/#get-supported-capabilities-for-audio-video-type) algorithm references _media types_ five steps before it is defined.

>For example, if _audio/video type_ is Video and the top-level type is not "video" or _media types_ contains non-video codecs.

In addition, the step in question determines whether "_content type_ is not strictly a _audio/video type_," but this happens before the steps that process the _content type_, including determining the codecs. (In practice, this is probably applied in each of the next few steps.)

This step was moved up in 59c28e9a5ab0f53ee6795bf3373f07852f4dd850 (related to #12). Before that, the algorithm looked like [this](https://rawgit.com/w3c/encrypted-media/ea30c0ff8c94af726c3ae2dfe97160ac7c5db4db/encrypted-media-respec.html#get-supported-capabilities-for-media-type)

@mwatson2, do you think this step belongs where it is? If not, we can move it below the step that defines _media types_. Otherwise, we'll need to reword the Note.

**Comment by mwatson2** [comment]
Hmm, I'm not sure why I moved this. It should be moved back to the position you suggest.

**Comment by mwatson2** [comment]
Fixed in 496e5f3c27ac17268ea69a5f3103d80f766419e6
