### ISSUE TITLE
Encrypted Block Encountered algorithm: Steps to abort playback are insufficient

### ISSUE THREAD

**Issue by ddorwin** [w3c/encrypted-media#112]
The Encrypted Block Encountered algorithm says that "If decryption fails...Abort the media element's resource fetch algorithm, run the steps to report a MEDIA_ERR_DECODE error, and abort these steps."

It is really "the overall _resource selection algorithm_" that needs to be aborted, and there are other steps that should occur when aborting playback.

MSE's [End of stream algorithm](http://w3c.github.io/media-source/#end-of-stream-algorithm) refers to more appropriate steps:
> Run the [media data is corrupted steps](http://www.w3.org/TR/html5/embedded-content-0.html#fatal-decode-error) of the [resource fetch algorithm](http://www.w3.org/TR/html5/embedded-content-0.html#concept-media-load-resource).

MSE's algorithm has other branches, but it's not clear that we need to handle such cases.

At a minimum, we should replace the current text with that step from MSE.

**Comment by steelejoe** [comment]
This makes sense. However it might make more sense to follow the `If the HTMLMediaElement.readyState attribute equals HAVE_NOTHING` branch if no data has been successfully decrypted yet. This would distinguish between the case where the decryption failed because the wrong key (or no key) was available from the case where the encrypted data was actually corrupted causing the decryption to fail.

**Comment by ddorwin** [comment]
It is not generally possible to determine whether you have the wrong key. The decryption just transforms bits from one value to another.

My assumption was that MSE needed this text because it is doing more (i.e. demuxing) than EME, which is just processing decrypted blocks. Can we really [`HAVE_NOTHING`](http://www.w3.org/TR/html5/embedded-content-0.html#dom-media-have_nothing) at that point? Maybe someone more familiar with the MSE or HTML5 algorithms can speak to this.

**Comment by paulbrucecotton** [comment]
The Sapporo F2F attendees agreed with the suggestion to use the MSE-like text: "Run the "media data is corrupted steps" of the "resource fetch algorithm"."
