### ISSUE TITLE
generateRequest() and load() should check "If the Session Close algorithm has been run"

### ISSUE THREAD

**Issue by ddorwin** [w3c/encrypted-media#113]
The `generateRequest()` and `load()` algorithms do not have check "If the Session Close algorithm has been run on this object" like the algorithms for the other `MediaKeySession` methods. This makes sense in normal operation since there are checks of the object's _uninitialized_ value. However, any asynchronous closure (e.g. #102) could occur before these methods are called. Thus, we should add these checks to these algorithms to cover such corner cases.

**Comment by steelejoe** [comment]
I agree with this. I assume the text you would add is the same - `If the Session Close algorithm has been run on this object, return a promise rejected with a new DOMException whose name is InvalidStateError`. We should do this.

**Comment by ddorwin** [comment]
Yes, the text would be the same.

**Comment by cpearce-mozilla** [comment]
SGTM.
