### ISSUE TITLE
MediaKeySystemConfiguration returned from MediaKeySystemAccess::getConfiguration() should contain the exact strings from requestMediaKeySystemAccess()

### ISSUE THREAD

**Issue by ddorwin** [w3c/encrypted-media#12]
The `requestMediaKeySystemAccess()` algorithms process `MediaKeySystemConfiguration` objects to find supported configurations. The first supported configuration (subset) is saved in the resulting `MediaKeySystemAccess` so that it can be returned by `getConfiguration()`.

The saved configuration is currently based on the results of processing the original configuration, which might imply that the strings are generated and thus different from the strings passed to `requestMediaKeySystemAccess()`.

Instead, the strings should be identical to those provided by the application. (There may be _less_ strings, but any remaining strings should be the same.) This will allow applications to always compare the resulting strings to known strings to, for example, select appropriate logic or content. Otherwise, user agents might normalize or otherwise change the strings in a way that breaks applications or requires additional logic.

**Comment by ddorwin** [comment]
Changes will include:
* _media type capabilities_ should be renamed _supported capabilities values_
* Get Supported Capabilities for Media Type step 14 should be: "Add the the value to _supported capabilities values_."
* Adding a normative comment stating that the various strings must be exactly as provided.

**Comment by mwatson2** [comment]
https://github.com/w3c/encrypted-media/commit/bc064c4e0c7901ecc60b74e23ecad06e4e072f64

**Comment by ddorwin** [comment]
After bc064c4, I believe _configuration_ is no longer used in the Get Supported Capabilities for Media Type algorithm and can be removed. (It also stands out as an untyped variable.)

**Comment by mwatson2** [comment]
*configuration* is used in step 13: "If the user agent and implementation do not support playback of encrypted media data as specified by *configuration*, ..."

It is indeed an untyped variable. It contains the *container*, *robustness* and *media types*.

We could replace the reference to *configuration* in step 13 with this explicit list.

Note that *media types* here appears to refer to the precise codecs (with parameters), but *media type* refers to the top-level media type (audio / video). This is bit confusing. I wonder if we should replace *media types* with *codecs* or even *parameterized codecs* ?

**Comment by ddorwin** [comment]
Oops, I missed that step. I think configuration is really just the _requested media capability_ in a different representation (extracted into those three variables then put into a different form). (Configuration is not a good name for this either.) I think _configuration_ currently just adds a level of indirection that makes step 13 less obvious.

We could just use _requested media capability_, but I think there is some value in explicitly covering the components, such as the reference to _media types_ in step 13. I think we can be more explicit (and perhaps just as concise) by referencing the three components in step 13. This also eliminates 3 steps where we add those values to _configuration_.

In the Note below step 13, "previously added supported configurations" should be "previously added requested media capabilities."

If you agree, I will try to rewrite step 13.

I agree that _media type_ and _media types_ is confusing and should be addressed. I filed #73.

**Comment by mwatson2** [comment]
I agree. I already have the changes here locally and will push them soon.

**Comment by mwatson2** [comment]
I made a couple of other simplifications too.

**Comment by ddorwin** [comment]
Looks good. Thanks. I left a few minor notes on the change, but I think we can close this again.
