### ISSUE TITLE
Bug 26776: Diagnosing and resolving CDM errors needs a numeric systemCode

### ISSUE THREAD

**Issue by mwatson2** [w3c/encrypted-media#120]
Moving from Bugzilla (https://www.w3.org/Bugs/Public/show_bug.cgi?id=26776):

MediaKeyError was removed from EME to resolve Bug 25896 - "Why is EME creating new DOMException subclasses?"  This reduced error reporting to using standard DOMException types or with a string message, and removed the previous (and valuable) numeric systemCode.  We need to restore some way for numeric error codes to be collected.

**Comment by mwatson2** [comment]
*Last comment from Bugzilla*:

It seems like it would be sufficient to have a systemCode attribute attached to either MediaKeySession or MediaKeys.  I recommend using MediaKeySession since it has other playback attributes related to the current playback activity (e.g. expiration and MediaKeyStatusMap).

It is true that multiple systemCodes might occur, suggesting a Sequence of values might be most flexible; however, for telemetry uses, a single value seems like it would meet a large majority of all needs.

A numeric code still is our preference, suggesting we add this to MediaKeySession:

  `readonly attribute unsigned long systemCode;`

I agree that some language could be added that discouraged using this attribute to trigger site behavior changes.  Given that it is not directly supported by an event and is limited to one value at a time, the risk of misusing it seems like it would be very low anyway.

**Comment by ddorwin** [comment]
I don't think this is resolved and ready for implementation as "needs implementation" implies. There were no replies to that last comment. This seems like something we should get feedback on, especially from authors, first.

A PR might also be helpful if there is initial positive feedback.

**Comment by paulbrucecotton** [comment]
@mwatson2  - Can you please supply a Pull Request for your solution?

**Comment by mwatson2** [comment]
@paulbrucecotton I marked this as "needs implementation" because I thought we had concluded on it long ago and that it had been implemented. However, it was pointed out at the f2f that current implementations provide this kind of failure code information within the message field of Exceptions, not as a separate systemCode. This has proven sufficient for our debugging needs.

So, unless other authors feel that the message solution is insufficient and unless there are implementors planning to expose this information, I withdraw the proposal I pasted from Bugzilla above.

**Comment by steelejoe** [comment]
Although I would prefer a systemCode (and we do expose it from our CDM), I believe we can live with the message field. If more experience tells us otherwise, we can always file another bug.

**Comment by jdsmith3000** [comment]
We also support using the message field for this.  We've prototyped it already and believe it meets the needs we had for this issue originally raised in Bugzilla 26776.  I recommend adding "System specific error codes may be returned using the DOMException message".  If we agree on that, I'll process a change.

**Comment by ddorwin** [comment]
@jdsmith3000, where would you add such a Note? Is it really necessary given that the DOMException messages are already implementation specific?

**Comment by jdsmith3000** [comment]
@ddorwin, I was thinking of adding it to the intro statement in http://www.w3.org/TR/encrypted-media/#exceptions.  Strictly speaking, that section only applies to `MediaKeySesssion`.  In context, it would be:

"The methods report errors by rejecting the returned promise with a DOMException. The following DOMException names from WebIDL [WebIDL] are used in the algorithms. Causes specified in the algorithms are listed alongside each name, though these names MAY be used for other reasons as well. System specific error codes may also be returned using the DOMException `message`."

**Comment by ddorwin** [comment]
The [definition](https://heycam.github.io/webidl/#dfn-exception-message) of DOMException's message says it "is an optional, user agent-defined value that provides human readable details of the error." Thus, including such error codes is already normatively allowed.

It seems odd/undesirable to a) reference something (system-specific error codes) that is not mentioned elsewhere in the spec and b) explicitly reference another Key System-specific value. Given that this is already normatively allowed, what do we gain by adding this sentence and is it worth those costs?

To be clear, I'm fine with this behavior, and this is what Chrome has implemented. I'm just not sure we need any additional text.

**Comment by jdsmith3000** [comment]
I agree that we can rely on the DOMException definition, as you've recommended.
