### ISSUE TITLE
Use streamlined wording for creating and throwing exceptions

### ISSUE THREAD

**Issue by ddorwin** [w3c/encrypted-media#122]
The spec currently uses wording like the following:
>... with a new `DOMException` whose name is `TypeError`.

https://heycam.github.io/webidl/#idl-exceptions gives several "examples of wording to use to create and throw exceptions." I believe following these will simplify the EME spec text. This includes both the one place where we throw an exception and I believe where we create a new `DOMException` with which to reject a promise.

In the example above, the new wording would be:
>... with a newly [created](https://heycam.github.io/webidl/#dfn-exception-create) TypeError.

<br/>
I believe the existing wording is based on the example at https://www.w3.org/2001/tag/doc/promises-guide#example-add-bookmark.

@domenic, should that example be updated or is the wording above not appropriate for promises?

Related questions:
* Should "return a promise rejected with..." be "return a _newly created_ promise rejected with..."?
* Should there be even further simplified language for rejecting promises? For example, "reject the promise with TypeError", possibly with a reference tow Web IDL somewhere in there, would imply creation of the new DOMException.
* Perhaps you can provide some suggested language for the missing examples in https://heycam.github.io/webidl/#es-promise.

**Comment by domenic** [comment]
In general I think there is some leeway here as long as you are clear :). As you can see from the promises guide I haven't been too careful. But, I can appreciate wanting to get this right.

One misconception worth clearing up: TypeError is not a DOMException; it is a [simple exception](https://heycam.github.io/webidl/#dfn-simple-exception).

> "with a newly created TypeError"

This works great. It's appropriate for promises as well.

> Should "return a promise rejected with..." be "return a newly created promise rejected with..."?

I think either is OK but the latter is indeed a bit more precise.

> Should there be even further simplified language for rejecting promises? For example, "reject the promise with TypeError", possibly with a reference tow Web IDL somewhere in there, would imply creation of the new DOMException.

I think if you said this (or possibly "a TypeError") people would know what you mean. "a new TypeError" would make it 100% clear.

> Perhaps you can provide some suggested language for the missing examples in https://heycam.github.io/webidl/#es-promise.

"perform some steps once a promise is settled" covers the same situations as the promise's guide's ["Reacting to Promises"](https://www.w3.org/2001/tag/doc/promises-guide#shorthand-reacting) section. It is more formalized, which is good; everything in the promises guide is generally not formal enough (https://github.com/w3ctag/promises-guide/issues/27). But it is more awkward to use and read IMO, which is sad.

An example converting from promises-guide phrases to Web IDL's hooks would be:

1. Return the result of transforming _p_ with a fulfillment handler that returns undefined.

becomes

1. Return the result of performing the following steps once _p_ is settled:
   1. When _p_ is fulfilled, return undefined.

I think the ultimate resolution is to fix https://github.com/w3ctag/promises-guide/issues/27 by fleshing out the Web IDL hooks to include everything the promises guide does. In the meantime it's a judgment call which style you use. I think both styles are pretty unambiguous, but I am curious what you and others think.

**Comment by ddorwin** [comment]
At a minimum, we need to fix the TypeError references to not be DOMExceptions.

Follow-up questions for @domenic:

>> Should there be even further simplified language for rejecting promises? For example, "reject the promise with TypeError", possibly with a reference tow Web IDL somewhere in there, would imply creation of the new DOMException.

>I think if you said this (or possibly "a TypeError") people would know what you mean. "a new TypeError" would make it 100% clear.

I agree with what you said for TypeError, but my question was intended to be about DOMException names. My intent was to simplify the language such that rejecting a promise with a DOMException name ("reject the promise with NotSupportedError") would be shorthand for "reject the promise with a newly [created](https://heycam.github.io/webidl/#dfn-exception-create) DOMException whose name is NotSupportedError." This seems consistent with Web IDL's [guidance](https://heycam.github.io/webidl/#idl-exceptions) to use "Throw an IndexSizeError" to mean "throw a new DOMException with error name IndexSizeError" [1]. However, such suggestion/shorthand for rejecting promises should probably be called out somewhere, possibly in Web IDL.

If we do not decide on such a shorthand, should we use "newly created" for all new objects? For example:
>return a _newly [created](https://heycam.github.io/webidl/#dfn-exception-create)_ promise rejected with a _newly [created](https://heycam.github.io/webidl/#dfn-exception-create)_ DOMException whose name is NotSupportedError.

It's a bit repetitive but technically correct(?). On the other hand, you said "a new TypeError" would be fine so the same would probably be true for "a new DOMException."

[1] Interestingly, neither "new" nor "newly [created](https://heycam.github.io/webidl/#dfn-exception-create)" appear in the suggested text.

**Comment by domenic** [comment]
> My intent was to simplify the language such that rejecting a promise with a DOMException name 

I see. I agree that "reject the promise with a NotSupportedError" is pretty reasonable, although I think it's clearer when NotSupportedError is linked (even though Web IDL doesn't do that). And yeah, we should get that upstreamed to Web IDL so that "Reject" links somewhere. In the meantime I will try to stuff it into the promises guide where [reject](http://www.w3.org/2001/tag/doc/promises-guide#reject-promise) currently lives.

**Comment by ddorwin** [comment]
* I filed #138 to fix `TypeError`.
* I filed https://www.w3.org/Bugs/Public/show_bug.cgi?id=29331 to provide guidance in Web IDL.

In the meantime, should we go with the following?
>[reject](http://www.w3.org/2001/tag/doc/promises-guide#reject-promise) the promise with a NotSupportedError.

@domenic, what did you mean by the following?
>I think it's clearer when NotSupportedError is linked...
The term `NotSupportedError` should be linked to its definition? Do you want to file a Web IDL bug for this?
(EME links to an intermediary table today as discussed in #103. We could add links to the Web IDL definitions or just bypass the table entirely.)

**Comment by domenic** [comment]
It was a bug against Web IDL I guess. When you have an intermediate table that works too. It's just IMO slightly confusing to say "throw a NotSupportedError" without any links, like Web IDL currently does. I'll try to PR that in.
