### ISSUE TITLE
Add explicit NOTE to authors that calling requestMediaKeySystemAccess() may lead to user agent UI and other effects

### ISSUE THREAD

**Issue by ddorwin** [w3c/encrypted-media#123]
We have seen an instance of a third-party library calling `requestMediaKeySystemAccess()` with no apparent intent by the host site to actually use EME.

In addition to unnecessarily using resources, this may generate a user prompt, trigger download of a CDM, and/or cause other user-visible impacts on some implementations.

The algorithm and even some of the introductory text make it clear that user consent, prompting, etc. should be handled in this algorithm, but it might be worth explicitly noting this at the very top ([here](https://w3c.github.io/encrypted-media/#navigator-extension-requestmediakeysystemaccess) or [here](requestMediaKeySystemAccess)). This may be especially important since `canPlayType()` MSE's and `isTypeSupported()` do not have such side effects.

The text might be something like:
>**NOTE**
>Calling this method may have **user-visible effects**, including requests for user consent. This method should only be called when when the author intends to create and use a `MediaKeys` object with the provided configuration.

**Comment by paulbrucecotton** [comment]
Would it be feasible for @mwatson2, @jdsmith3000  and/or @steelejoe to get "author input" on this issue?

**Comment by mwatson2** [comment]
I think David's proposed note simply points out something which is factually correct - a consequence of the normative algorithms - but which seems to have been missed by some authors. So then my "input" as an "author" is, yes, it is useful to point out such things ;-)
