### ISSUE TITLE
'callable' or 'callable value'?

### ISSUE THREAD

**Issue by squelart** [w3c/encrypted-media#125]
There are 4 instances of 'callable value' and 2 of 'callable'. For consistency only one of these should be used, probably 'callable value'.

**Comment by ddorwin** [comment]
It looks like including "value" would be most consistent. There is a similar issue with "uninitialized" and perhaps other internal unexposed values.

**Comment by jdsmith3000** [comment]
It looks to me like `use distinctive identifier`  and `persistent state allowed` might similarly benefit from consistent use of value.  Is this a complete list?

* `callable`
* `uninitialized`
* `use distinctive identifier`
* `persistent state allowed`

**Comment by mwatson2** [comment]
There are a few cases where the same name is used for a stand-alone variable and for an internal value associated with an object. In the former case we do not need the "value" attached.
