### ISSUE TITLE
Making progress on EME open issues

### ISSUE THREAD

**Issue by paulbrucecotton** [w3c/encrypted-media#128]
There are currently over 40 EME open issues and I want to encourage everyone that is watching the EME GitHub to assist us in making further progress on these issues.

In particular I want to encourage participants to:
a) Produce candidate Pull Requests for the 20+ [needs implementation](https://github.com/w3c/encrypted-media/labels/needs%20implementation) issues
b) Indicate their support or lack of support for incoming Pull Requests so that we know your opinions on the PRs.

/paulc

**Comment by ddorwin** [comment]
Issues are being triaged per https://lists.w3.org/Archives/Public/public-html-media/2016Mar/0003.html. We have no issues without milestones and 18 V1 issues. Of those, we have 6 needs implementation and 3 help wanted that could use Pull Requests. Please also provide input on other issues where appropriate.
