### ISSUE TITLE
Confirm `readyState` behavior when blocked waiting for a key is correct

### ISSUE THREAD

**Issue by ddorwin** [w3c/encrypted-media#129]
The value of `readyState` when blocked waiting for a key (causing the `waitingforkey` event) was raised by @cpearce-mozilla in #100. Although the EME spec is explicit about the expected behavior, it is not clear whether that is the correct behavior. This issue tracks confirming the specified behavior or modifying it to be correct. This likely depends on correctly interpreting the definition of `readyState`.

The EME spec currently says:
>The element is potentially playing and its `readyState` is equal to `HAVE_FUTURE_DATA` or greater.

This was based on an interpretation of `readyState` as relating only to the buffering of media data (see #7), which seems to be implied by the definitions of the [Ready states](https://html.spec.whatwg.org/multipage/embedded-content.html/#ready-states).

Among the questions to address are:
* Should being blocked on a key affect the media element's `readyState`?
  * Note that this would cause the HTMLMediaElement `waiting` and `canplay` events to be fired in response to key availability (see #7). In #7, we decided to avoid using these events and only fire an EME-specific event.
* Should the `readyState` indeed be "equal to `HAVE_FUTURE_DATA` or greater" when the Queue a "waitingforkey" Event algorithm is run?
  * More specifically, is the `readyState` "equal to `HAVE_FUTURE_DATA` or greater" when the Encrypted Block Encountered algorithm is run?

<br/>The HTML spec [says](https://html.spec.whatwg.org/multipage/embedded-content.html#ready-state):
>Media elements have a _ready state_, which describes to what degree they are ready to be rendered at the current playback position.

Based on that definition ("ready to be rendered"), it sounds like `readyState` should consider whether the media data can currently be rendered, which would include decryption _and decoding_. Furthermore, `HAVE_CURRENT_DATA` and higher would imply that the current data has already been (decrypted and) decoded. However, I do not believe that is the intent, so perhaps the definition needs to be corrected.

The [`HAVE_ENOUGH_DATA` definition](https://html.spec.whatwg.org/multipage/embedded-content.html#dom-media-have_enough_data) actually references the fetching of the data, which would seem to imply that `readyState` is indeed related to buffering (and the resource fetch algorithm).

If the "ready to be rendered" definition is correct, the definition of `HAVE_ENOUGH_DATA` should probably also include decoding:
> The user agent estimates that data is being fetched **and decoded** at a rate...

Still, it doesn't seem possible to address key availability since it is not generally possible for the user agent (or CDM) to determine whether it has all the necessary keys for future blocks. That would be an argument against such interpretation and changes.

@foolip, can you clarify the intended meaning of `readyState`?

**Comment by ddorwin** [comment]
Current state of implementations:
* @cpearce-mozillain noted in #100, that "In Firefox's implementation, the HAVE_CURRENT_DATA and HAVE_FUTURE_DATA readyStates are dependent on whether we have enough decoded data" but that they have discussed changes.
* I observed in Chrome 49 that `readyState` is `HAVE_METADATA` when `waitingforkey` is fired (at least when blocked on the first frame).

**Comment by ddorwin** [comment]
The five events starting with `[loadeddata](https://html.spec.whatwg.org/multipage/embedded-content.html#event-media-loadeddata)` are also interesting:
* `loadeddata`: "The user agent can **render** the media data..."
* `canplay`: "The user agent can **resume playback**..."
* `canplaythrough`: "The user agent estimates that... the media resource could be **rendered**... without having to stop for **further buffering**."
* `playing`: "**Playback** is ready to start after having been paused or delayed due to **lack of media data**."
  * I wonder whether "paused" is misleading or ambiguous here.
* `waiting`: "Playback has stopped because the **next frame is not available**, but the user agent expects that frame to become available in due course."

Similar to my original comment above, there is a mix of "rendering"/"playback" and **buffering**. Were these specific word choices intentional and thus meaningful?

**Comment by foolip** [comment]
I couldn't say for certain what the original intentions were, but my take on `readyState` has long been something like this:
 * `HAVE_NOTHING`: No buffered ranges, media pipeline not set up.
 * `HAVE_METADATA`: `currentTime` is outside of the buffered ranges, but headers have been decoded.
 * `HAVE_CURRENT_DATA`: `currentTime` is at the end of a buffered range.
 * `HAVE_FUTURE_DATA`: `currentTime` is in a buffered range, but not at the end of it
 * `HAVE_ENOUGH_DATA`: like `HAVE_FUTURE_DATA` but we estimate that we can play through without running into any unbuffered areas.

This is a fantasy, however. It would be mostly redundant with `buffered`+`currentTime`. Also, the definition of `HAVE_FUTURE_DATA` is kind of broken when waiting for the network, taken seriously it would require the UA to continue playing as soon as even a millisecond of future data is available, which is a terrible policy.

So, implementations just do something else with `readyState`, based on the status of the media pipeline which of course doesn't process data synchronously as it comes in over the network. It sure would be nice to figure out what definitions would actually make sense and mostly match existing implementations.

Ignoring the HTML spec for a moment, would you *want* `readyState` to be affected when blocked waiting for a key? If one were to redefine `readyState` as being entirely related to the media pipeline, it would make sense, I think.

**Comment by ddorwin** [comment]
>Ignoring the HTML spec for a moment, would you *want* `readyState` to be affected when blocked waiting for a key? If one were to redefine `readyState` as being entirely related to the media pipeline, it would make sense, I think.

I think it really depends on how authors are using or want to use `readyState` and the related events.  Before EME (and MSE), network/buffering was really the only thing that would affect these. (Maybe slow decoding, but that's more of a corner case.)

@heff, @joeyparrish, and other authors, what are your thought and/or how do you use these?


It's also worth noting that blocked on a key should be transient, and the current `waitingforkey` event is mostly informative for development and debugging. During normal operation, this should only happen when playback has started and is waiting for a license to be returned from the server. Other cases I can think of are the app not expecting encrypted content, the wrong key(s) being provided, or the license policy(ies) not being satisfied. In the first two, there isn't anything the application can do. For the second, we have `keyStatuses`.

**Comment by paulbrucecotton** [comment]
This issues has been waiting since late November for "author input".

Could @heff, @joeyparrish, and/or other authors please comment?

**Comment by ddorwin** [comment]
See also the discussion at https://github.com/w3c/encrypted-media/pull/139#discussion_r50614064.

**Comment by heff** [comment]
@dmlap might be able to weigh in on this for video.js.

**Comment by joeyparrish** [comment]
We use `readyState` to determine when we can seek to the initial playback position.  Some browsers won't let us set `currentTime` until an initialization segment has been processed.  We do not use `readyState` for anything else currently.

We use `keyStatuses` to determine the presence or absence of keys we know about from the manifest.  If the pipeline is blocked waiting for a key we don't know about, we currently do not detect this.  If we used `waitingforkey` as well, our library could notify the application if the pipeline were blocked at a time when no license requests were in progress.  This would indicate that the stall was unlikely to be resolved, and that the manifest or DRM config might be broken.

So I can't think of a reason we would *need* `readyState` to reflect anything about decryption or key status.  I don't understand the original intent of `readyState` well enough to comment on any possible issues in consistency of interpretation when combined with EME.

**Comment by dmlap** [comment]
The two use-cases I'm aware of for `readyState` are:

1. Finding out whether the video element is ready to perform particular operations (e.g. seeking, checking duration)
2. Determining whether to display a loading indicator to the user

If events like `waiting` and `canplay` are contingent on `readyState` changing, then I think it would be really helpful for `readyState` to change based on key status. We'd like to display a loading indicator if playback is blocked for any reason, and receiving that notification through the existing events would save us another case to consider.

**Comment by paulbrucecotton** [comment]
>@heff, @joeyparrish, and other authors, what are your thought and/or how do you use these?

@ddorwin - We have input from multiple authors.  Is this sufficient to move this issue forward?

**Comment by jdsmith3000** [comment]
Input so far is mixed: One stating that `readyState `and `keyStatus` are separate and need not be combined, and another indicating that it would be useful for events like `waiting` and `canplay` to reflect key support as well as buffer state.

I have personally thought of these as separate indicators.  Combining them might streamline how we reflect playback state, though perhaps is not essential?  @dmlap states it would be useful for showing a loading indicator if waiting on either data or keys.

**Comment by dmlap** [comment]
@jdsmith3000 I might be misinterpreting but it doesn't seem to me that our comments conflicted with one another. @joeyparrish, did you mean your implementation is agnostic to whether `readyState` reflects `keyStatus` or that it was incompatible with `readyState` reflecting `keyStatus`?

**Comment by joeyparrish** [comment]
@dmlap, the only thing that would break my current use of `readyState` is if waiting for a key resulted in `HAVE_NOTHING`.  Once I at least `HAVE_METADATA`, my interactions with `readyState` are at an end.

**Comment by mwatson2** [comment]
Feedback from our player team is that they feel it makes more sense for readyState to be at HAVE_METADATA in the case that playback is waiting for a key. IMO, this aligns with a struct (re?)-interpretation of the definitions, which are written in terms of whether data is "ready to be rendered". I think the term "ready" is vague enough to understand this as meaning there are no external dependencies blocking the rendering - i.e. that all that is required is CPU time - so that it is an implementation detail whether decryption and decoding have actually happened, as long as there is nothing to stop them happening.

IIUC, some implementations already behave this way, rather than implementing what is currently in the specification.

**Comment by dmlap** [comment]
Moving to HAVE_METADATA when playback is blocked on a key sounds sensible to me, too.

**Comment by foolip** [comment]
I think you should be careful about changing `readyState` in a way that can only happen for EME. For plain media playback, if `buffered` contains minutes of data beyond `currentTime` and you're playing in `readyState` `HAVE_FUTURE_DATA`, then AFAIK there's nothing that could cause `readyState` to decrease except reaching the end of the buffered data.

My concern is that such a change would amount to monkey-patching HTML's definition of `readyState` and in an implementation it could be a dependency from HTML back to EME.

**Comment by paulbrucecotton** [comment]
This V1 issue has been dormant for nearly two months. 

@ddorwin, @mwatson2 or @jdsmith3000:  Can one of the Editors please self-assign this issue and figure out how to move it to resolution?

**Comment by mwatson2** [comment]
The balance of comments seems to be in favor of `readyState` changing when the required key is unavailable.

@foolip We are already forced to monkey-patch the HTML Media Element to achieve what we need. I think that with this change we stay closer to the definition of `readyState` as describing whether data is ready to be rendered, rather than simply whether it has been buffered. As you note [above](https://github.com/w3c/encrypted-media/issues/129#issuecomment-159632283) if it purely reflected buffered data and `currentTime` it would be redundant with those attributes.

Please see [this PR](https://github.com/w3c/encrypted-media/pull/200).

**Comment by ddorwin** [comment]
For reference, I believe the effect of having EME change `readystate` would be:
* When a key is unavailable: `readyState` would be set to `HAVE_METADATA` and both the `waitingforkey` and `waiting` events would be fired.
* When the key is provided: `readyState` would transition to `HAVE_CURRENT_DATA` or greater as appropriate based on buffering and the corresponding events `canplay`, `canplaythrough`, and `playing` would be fired as appropriate.

If we make such a change to include decryption [key(s)] as a condition of `readyState`, this may be inconsistently applied to `readyState` values in implementations. Specifically, the user agent to now that it `HAVE_FUTURE_DATA` or `HAVE_ENOUGH_DATA` and `canplaythrough` without checking the key ID for upcoming blocks and comparing it to `keystatuses`. Since that is unlikely, we should probably note that such checks of future blocks are a quality of implementation detail and/or unlikely to be performed. In other words, states beyond `HAVE_CURRENT_DATA` and `canplaythrough` do not (or are unlikely to) consider key availability beyond the _current_ key.


<br/>To minimize potential disruptions to the V1 timeline related to this (regardless of the outcome), we may want to note that this is subject to change in CR and/or add it to the at risk items since we don’t know what implementations do or have (explicit) implementation experience.


<br/>@dmlap wrote:
>If events like waiting and canplay are contingent on readyState changing, then I think it would be really helpful for readyState to change based on key status. We'd like to display a loading indicator if playback is blocked for any reason, and receiving that notification through the existing events would save us another case to consider.

This could be problematic since if a key is missing, the “loading” will never be resolved, leading to a frustrating experience for users. Perhaps this is better than only firing an event (e.g. `waitingforkey`) that the app does not handle, but it also allows the app author to incorrectly think they are handling the situation.

**Comment by paulbrucecotton** [comment]
@ddorwin 

>To minimize potential disruptions to the V1 timeline related to this (regardless of the outcome), we may want to note that this is subject to change in CR and/or add it to the at risk items since we don’t know what implementations do or have (explicit) implementation experience.

There are only two actions that can be taken on "at risk" features.  We either drop them completely when we go to Proposed Recommendation or we keep them WITHOUT "substantive changes".  If during CR we find it necessary to make a "substantive change" to a feature marked "at risk" then we cannot make such a change and continue to Proposed Recommendation.   We would have to republish the Candidate Recommendation which restarts the Patent Policy 60 day disclosure period [1] for the specification.

**Comment by mwatson2** [comment]
Reviewed at editors' meeting (@mwatson2 @jdsmith3000). We propose adding the following note:

> States beyond `HAVE_CURRENT_DATA` and the `canplaythrough` event do not (or are unlikely to) consider key availability beyond the current key.

We note that we could mark the feature of "modifying `readyState` based on key availability" as "at risk". We could then drop this "feature" before PR if necessary, returning to the current specification.

**Comment by ddorwin** [comment]
SGTM. Thanks.

**Comment by mwatson2** [comment]
@ddorwin @jdsmith3000 @mwatson2 discussed at editors meeting. This change will be merged with the two amendments noted as line notes in the PR.
