### ISSUE TITLE
MediaKeySession.load() step 5 refers to undefined "current MediaKeySession session type"

### ISSUE THREAD

**Issue by cpearce-mozilla** [w3c/encrypted-media#131]
Step 5 of MediaKeySession.load()  read:

> 5. If the object's session type is not the same as the current MediaKeySession session type, return a promise rejected with a new DOMException whose name is TypeError.

Step 5 refers to "the current MediaKeySession session type", but there's no definition of what "the current MediaKeySession session type" is. It seems that this is almost a check to enforce that the session type is a persistent type, but that's already done in step 4.

I propose we remove step 5.

**Comment by ddorwin** [comment]
@jdsmith3000 added this step in 58c8a82 for #20. It should have been added as a substep of step 8.8 where the issue box is. At that point, we can compare the session type of the persisted data to the object's session type.

I've re-opened #20. I think we can close this one.

**Comment by jdsmith3000** [comment]
Corrected in revised commit for issue #20.
