### ISSUE TITLE
Example 5 in section 12.1 has mismatch between initDataType and initData in generateRequest call

### ISSUE THREAD

**Issue by cpearce-mozilla** [w3c/encrypted-media#134]
In example 5 in section "12.1 Source and Key Known at Page Load (Clear Key)", the code that calls generateRequest() is:

          promise.then(
            function(createdMediaKeys) {
              var te = new TextEncoder();
              var initData = te.encode( '{"kids":["LwVHf8JLtPrv2GUXFW2v_A"]}');
              var keySession = createdMediaKeys.createSession();
              keySession.addEventListener("message", handleMessage, false);
              return keySession.generateRequest('webm', initData);
            }
          ).catch(
            console.error.bind(console, 'Unable to create or initialize key session')
          );

I think that should be:

          promise.then(
            function(createdMediaKeys) {
              var te = new TextEncoder();
              var initData = te.encode( '{"kids":["LwVHf8JLtPrv2GUXFW2v_A"]}');
              var keySession = createdMediaKeys.createSession();
              keySession.addEventListener("message", handleMessage, false);
              return keySession.generateRequest('keyIds', initData);
            }
          ).catch(
            console.error.bind(console, 'Unable to create or initialize key session')
          );

i.e. instead of generateRequest('webm', initData), it should be generateRequest('keyIds', initData), since initData is actually a 'keyids' type initData.

**Comment by ddorwin** [comment]
Yes, the type needs to be changed to 'keyids'.

For the record, https://github.com/w3c/encrypted-media/commit/f2e710ffa7c1365423916a4e5a9620a4722178d5 added a real initData value but didn't update the type to match.
