### ISSUE TITLE
Typo in HTMLMediaElement.setMediaKeys method definition

### ISSUE THREAD

**Issue by cpearce** [w3c/encrypted-media#140]
The setMediaKeys method definition, step 5.1 reads:

"If mediaKeys is not null, it is already in use by another media element, and the user agent is unable to use it with this element, let this object's attaching media keys value be false and reject promise with a new DOMException whose name is QuotaExceededError."

I think that's a typo, it should read:

"If mediaKeys is not null, **and** it is already in use by another media element, and the user agent is unable to use it with this element, let this object's attaching media keys value be false and reject promise with a new DOMException whose name is QuotaExceededError."

**Comment by ddorwin** [comment]
Those are three separate conditions that must all be true. It follows the structure `A, B, and C.` In this case, B implies A, but I think it is still helpful to be explicit.

I think "it" could be less ambiguous, and that might help. "It" might also be technically incorrect.

I propose the following, which is consistent with step 5.2.3.
>If mediaKeys is not null, **the CDM instance represented by _mediaKeys_** is already in use...

**Comment by cpearce** [comment]
OK, that sounds fine. I've done that in PR#141.
