### ISSUE TITLE
Do not allow the user agent to "choose to skip this step" in setMediaKeys()

### ISSUE THREAD

**Issue by ddorwin** [w3c/encrypted-media#144]
To resolve issue #98, we removed one of the "The user agent may choose to skip this step..." statements. I think we should remove the remaining statement from `setMediaKeys()`.

Implementations are welcome to make such optimizations as long as they do not affect the observable behavior. It's simplest to ensure consistent behavior if we do not allow such exceptions unless really necessary.

In addition, as I noted in https://github.com/w3c/encrypted-media/issues/98#issuecomment-149301160, the Note following the statement is misleading because the user agent may just be waiting for a MediaKeys object to be specified.

**Comment by steelejoe** [comment]
I agree with this change.

**Comment by mwatson2** [comment]
+1

**Comment by paulbrucecotton** [comment]
>I think we should remove the remaining statement from  setMediaKeys() .

@ddorwin and @mwatson2  - If no one objects before the end of this week (Feb 12), I recommend we make the proposed change.

**Comment by jdsmith3000** [comment]
I agree with deleting both the statement and the note.

Under setMediaKeys 5.3.3:
`Queue a task to run the Attempt to Resume Playback If Necessary algorithm on the media element.`

Remove:
`The user agent MAY choose to skip this step if it knows resuming will fail.`
`NOTE: For example, the user agent may skip this step if mediaKeys has no sessions.`

**Comment by ddorwin** [comment]
Sounds good.
