### ISSUE TITLE
Update CENC and ISOBMFF standards references in the CENC stream format spec

### ISSUE THREAD

**Issue by jdsmith3000** [w3c/encrypted-media#148]
Both CENC and ISOBMFF standards are available in newer versions than the "**ISO Common Encryption EME Stream Format and Initialization Data**" spec currently references.  We should consider updating it to these:

> **A.1 Normative references**
> 
> **[CENC]**
> [ISO/IEC 23001-7:2016, Information technology — MPEG systems technologies — Part 7: Common encryption in ISO base media file format files](https://www.iso.org/obp/ui/#iso:std:iso-iec:23001:-7:ed-3:v1:en). International Standard. URL: https://www.iso.org/obp/ui/#iso:std:iso-iec:23001:-7:ed-3:v1:en
> 
> **[ISOBMFF]**
> [ISO/IEC 14496–12, Information technology — Coding of audio-visual objects — Part 12: ISO Base Media File Format] (http://standards.iso.org/ittf/PubliclyAvailableStandards/c068960_ISO_IEC_14496-12_2015.zip). International Standard. URL: http://standards.iso.org/ittf/PubliclyAvailableStandards/c068960_ISO_IEC_14496-12_2015.zip

ISOBMFF is not specified directly in the CENC source, but is pulled from [specref](https://github.com/tobie/specref).  Updating it would require a opening a [specref issue](https://github.com/tobie/specref/issues).

**Comment by ddorwin** [comment]
Specifically:
* CENC: The 2016 3rd edition has been published, replacing the 2015 2nd edition currently referenced.
* ISOBMFF: There is a 2015 version, replacing 2012 version currently referenced.

The CENC reference was previously updated for #64. The comments there apply to this update as well.

**Comment by ddorwin** [comment]
Triaging per https://lists.w3.org/Archives/Public/public-html-media/2016Mar/0003.html.

**Comment by paulbrucecotton** [comment]
> Updating it would require a opening a specref issue<https://github.com/tobie/specref/issues>

@jdsmith3000: Since opening and resolving the specref issue is the "long pole" here can you please open that issue?

**Comment by paulbrucecotton** [comment]
@jdsmith3000 - Now that the ISOBMFF reference is fixed in [specref](https://github.com/tobie/specref/issues/282), the only change that needs to be made is to manually change the CENC reference.  Can you assign this issue to yourself and prep this small PR?

**Comment by jdsmith3000** [comment]
This PR changes both cenc.html and mp4.html to get both references up to date:  
- The CENC reference is manually defined in cenc-respec.html and snapshot as cenc.html.  
- The ISOBMFF comes from specref, but still required a new snapshot of mp4-respec.html to produce an mp4.html copy that was updated with the new reference.
