### ISSUE TITLE
MediaKeySystemAccess::getConfiguration() should return a read-only object (copy)

### ISSUE THREAD

**Issue by ddorwin** [w3c/encrypted-media#15]
The `MediaKeySystemAccess::getConfiguration()` algorithm currently says, "Return this object's configuration value." We don't want the application to be able to modify the internal object and affect future calls. Is there a way to indicate that the return value is read-only in IDL or must we do so in prose?
Can an object be read-only or do we need to return a copy to prevent applications from modifying the internal state?

**Comment by ddorwin** [comment]
A cached copy is fine too. Are other specs using this? Is there a preference or tendency for one over the other?

**Comment by mwatson2** [comment]
You need someone like Boris to comment on that.

**Comment by bzbarsky** [comment]
I'm not sure there's a preference for one or the other so far; very few specs are returning random JS objects to represent state.

Web Crypto does the [Cached] thing, with an attribute getter and an object that's created once from internal state and then returned all the time.  This object is not frozen.

WebGL's getContextAttributes returns a new object each time, created from some internal state.

The current spec for MediaKeySystemAccess.getConfiguration matches the WebGL behavior: it's specified to return a new object each time, created from the internally stored dictionary.  So the basic issue that was reported doesn't seem to be a problem: this is already returning a copy of the state every time, fwiw.

**Comment by ddorwin** [comment]
Can you explain how the current spec specifies returning a new object each time?

"Return this object's _configuration_ value" would seem to indicate that it is returning the _same_ object each time.

**Comment by bzbarsky** [comment]
The current spec defines an operation that returns a dictionary type, yes?

The behavior is then determined by <http://heycam.github.io/webidl/#es-operations>.  The "Return this object's _configuration_ value" text is step 7 of the steps defined there.  Then step 8 is performed.  The operation is defined to return a dictionary, so you end up in <http://heycam.github.io/webidl/#es-dictionary> under the "An IDL dictionary value V is converted to an ECMAScript Object value by running the following algorithm" steps.  Note step 1 and step 4.

Or more conceptually, IDL dictionaries are always passed by value, not by reference.  Converting from a JS object to a dictionary always copies; conversion from a dictionary to a JS value always creates a new object.

**Comment by ddorwin** [comment]
Thanks for the explanation. I think that behavior is fine and addresses this bug. I will add a non-normative note stating that this creates a copy.

On a related note, would it be more correct to refer to "`MediaKeySystemConfiguration` dictionary" instead of "`MediaKeySystemConfiguration` object" within the algorithms, specifically step 7.3.3.1.2 of requestMediaKeySystemAccess()?

**Comment by bzbarsky** [comment]
Yes, calling that a "MediaKeySystemAccess dictionary" makes a lot more sense.

Also, it might be a good idea to file a bug on Web IDL to define what it means to resolve a promise with an IDL value (in particular, that you convert the IDL value to a JS value and resolve the promise with that)...

**Comment by ddorwin** [comment]
I'll make the changes in the previous two comments.

Boris filed https://www.w3.org/Bugs/Public/show_bug.cgi?id=27995 related to his last paragraph above.

**Comment by mwatson2** [comment]
Note that I had previously modified the "Get supported configuration" algorithm to return a MediaKeySystemConfiguration dictionary type, rather than an object, so the change to step 7.3.3.1.2 of requestMediaKeySystemAccess() is simply to return *supported configuration*.
