### ISSUE TITLE
Clarify the meaning of "do[es] not support" a media capability

### ISSUE THREAD

**Issue by ddorwin** [w3c/encrypted-media#151]
Step 12 of the [_Get Supported Capabilities for Audio/Video Type_](https://w3c.github.io/encrypted-media/#get-supported-capabilities-for-audio-video-type) algorithm says
>If the user agent and implementation do not support playback of encrypted media data for the combination of _container_, _media types_, _robustness_ and _local accumulated configuration_, continue to the next iteration.

In practice, _media types_ means codecs. The question is whether "do not support" means (a) "is **certain it does not** support" or (b) "is **not certain** it can support." This is mainly relevant when a codec string is ambiguous or otherwise not known to be supported. These are likely the cases where `canPlayType()` would return `"maybe"` rather than `""` or `"probably"`.

If (a), ambiguous or potentially-supported codec strings would cause the current configuration to be selected. If (b), they would not be included and may cause the current configuration to be skipped.

While (a) might be seen as friendly, it also:
* Prevents an application from using certain patterns.
  * For example, one configuration may include a codec string that indicates advanced features (about which some UAs may not be certain) may be followed by a configuration containing a more common codec string.
  * If the UA does not reject the first codec string, the application cannot differentiate.
* Encourages bad practices (i.e. using incomplete codec strings), which could prevent implementations from providing accurate and specific responses.
  * By being strict in a new API, we can avoid some of the issues we are now stuck with for `canPlayType()`.

We have been more "strict" than friendly before (i.e. requiring all `sessionTypes` to be supported) in order to enable application control similar to the example above.

Note: Part of the issue here is the liberal handling of codec strings (e.g. by `canPlayType()`) in many implementations, that the differentiation between `"maybe"` and `"probably"` is often irrelevant, and that the EME API has two states instead of three. MSE’s `isTypeSupported()`  also only has two states and appears to be liberal, but it does not explicitly need to support a series of configurations like EME does. If it was possible, being strict would probably be better there as well. Perhaps more importantly, `canPlayType()` and `isTypeSupported()` are designed to allow the application to walk a tree of capabilities whereas EME is designed to check lists of specific codecs and get a response. Furthermore, EME allows a subset of the listed types to be selected (and thus satisfy the configuration).

The following are some examples that frequently occur today for `canPlayType()` and MSE's `isTypeSupported()`:
* `"avc1"` - [valid RFC6381 syntax](https://tools.ietf.org/html/rfc6381#section-3.4) but very ambiguous.
* `"mp4a.40"` - [valid RFC6381 syntax](https://tools.ietf.org/html/rfc6381#section-3.4) but very ambiguous.
* `"mp4a"` - [**invalid** RFC6381 syntax](https://tools.ietf.org/html/rfc6381#section-3.4) and very ambiguous.
* `"avc1.58A01E"` - Extended profile. Probably not supported but returns `"maybe"` in Chrome and likely elsewhere.

Chrome currently implements (b), which is basically implemented by determining whether the codec string would result in `"probably"` if passed to `canPlayType()`. (Chrome's handling and filtering of codec strings in `canPlayType()` has been improved recently.) Based on sample code, it appears that Edge implements (a), even allowing `"mp4a"`.

Thus, we have an interoperability issue that should be resolved in the spec.

**Comment by joeyparrish** [comment]
This has been a source of confusion for me as an author, particularly trying to come up with one way to formulate queries that is compatible with both Chrome and Edge.  The only way I could manage this was to use `contentType: 'video/mp4'` and `contentType: 'audio/mp4'` by ignoring the codec strings completely.  Having a capabilities entry for each full content type didn't work.

I would like to be able to be as specific as possible and know, for example, whether each track is in a DASH manifest is playable.  At the moment, I am relying on MediaSource to do this, and assuming that any codec string acceptable to MediaSource is also acceptable to the CDM.

If the CDM can handle a superset of what MSE can handle, I will miss out on the ability to play some tracks.  (I find this unlikely, and it doesn't concern me much.)

If the CDM can handle a subset of what MSE can handle, I may try to play something that fails to decode, and specific information from EME could have helped me avoid this.  (I find this more likely, but in practice haven't run into it yet.)

**Comment by ddorwin** [comment]
In the first comment, I focused on codec strings, but we should also consider whether a container (that does not imply a codec) without a codecs string (e.g. `'video/mp4'`) should be supported.

While this may at first seem like an obvious "yes," what are the use cases? This might be useful for walking the tree, but as mentioned above, this is not how EME is queried. The remaining question is whether there are use cases when support for the container is sufficient (no codecs will be used). With the separation of Initialization Data Type from container, I can't think of such a case. Please speak up if you have one or think there is a use case for passing just the container.

**Comment by ddorwin** [comment]
The specific proposal is be explicit that (b) is the intent by replacing:
>If the user agent and _implementation_ do not support playback...

with:
>If the user agent is not certain it and _implementation_ support support playback...

We might add an explicit note about the container-only case since that may not be obvious to the reader.

<br/>
For reference, the following are examples of `contentType` values that would unambiguously be considered unsupported:
* `'video/mp4'`, `'audio/mp4'`, and any other container-only value (unless the container implies a codec by definition)
* `'video/foo'`
* Values that contain the following codec strings:
  * `"avc1"`
  * `"mp4a.40"` and `"mp4a"`
  * `"avc1.58A01E"` in most current implementations
  * `"foo"`

**Comment by mwatson2** [comment]
This proposal seems reasonable to me.

**Comment by mwatson2** [comment]
I created #163 for this. Are there any further comments ?

**Comment by joeyparrish** [comment]
The proposal works for me.  I was using less specific mime types in my code to workaround an Edge bug, but the bug I was working around was actually triggered by something else.  I am able to use specific mime types with codecs in my code now.

**Comment by mwatson2** [comment]
Thanks @ddorwin and @joeyparrish for comments. Any further comments ? I will merge this later this week if there are no further comments.
