### ISSUE TITLE
EME License Release Format Example

### ISSUE THREAD

**Issue by JSaunders0102** [w3c/encrypted-media#152]
In section 9.1.5 License Release Format of the EME (W3C Editor's Draft 26 February 2016), an example is provided that says:
"The following example is a license release for a temporary license for **a single key ID**. (Line breaks are for readability only.)".
But, in the example, it appears to show two "kids":
     EXAMPLE 3
     {
       "kids": [ "LwVHf8JLtPrv2GUXFW2v_A", "0DdtU9od-Bh5L3xbv0Xf_A" ],
       "tfirst" : 1430425323757,
       "tlatest" : 1430425383757
     }
Both kids have the same first/latest time. Is this correct? If so, what do the two "kids" values represent if not two separate key IDs?

**Comment by mwatson2** [comment]
It's a typo. Either there should be only one kid in the example, of the text should not say "single kid". I suggest the former.

**Comment by JSaunders0102** [comment]
Thank you. On a similar note, are there any plans to update the figure at the beginning? It seems to be somewhat out of sync with the contents.

**Comment by mwatson2** [comment]
We have issue #2.

**Comment by ddorwin** [comment]
I think the latter (showing multiple keys) is more helpful to the reader. (We might also want to add a second key to the License Format example above it.)

I think we need to clean up the sentence more anyway - it is not possible for a release message to be issued for a `"temporary"` license.
