### ISSUE TITLE
Non-method algorithm intro paragraphs may be misleading about when to run the algorithm

### ISSUE THREAD

**Issue by ddorwin** [w3c/encrypted-media#153]
(The following focuses on added HTMLMediaElement algorithms, but this also applies to algorithms for other objects.)

The section for several algorithms in the spec begin with text like "The following steps are run when..." "The Do Something algorithm is run when..."

For some algorithms, such as the [Initialization Data Encountered](https://w3c.github.io/encrypted-media/#initdata-encountered) algorithm, this means the algorithm should be run when this happens. However, for others, the when to call the algorithms is explicitly specified somewhere else and this is just informative context. There is no differentiation of these cases.

First, we should avoid implying the former when it is not the intent (the latter). Instead, we can follow other examples, such as "This algorithm does something..." Second, we _may_ not even need the former. For example, some recent updates explicitly added when to call the "Encrypted Block Encountered" algorithm to the top of https://w3c.github.io/encrypted-media/#htmlmediaelement-extensions.

**Comment by mwatson2** [comment]
This is expected to be solved by #181

**Comment by mwatson2** [comment]
Closing because we'll address this under #181.

**Comment by ddorwin** [comment]
The "run when" text still appears in three HTMLMediaElement algorithms:
* Initialization Data Encountered
* Queue a "waitingforkey" Event
* Attempt to Resume Playback If Necessary

I think we addressed the `MediaKeySession` algorithms in #181, but these were not addressed.

**Comment by ddorwin** [comment]
PR #285.
