### ISSUE TITLE
EME undermines its stated purpose

### ISSUE THREAD

**Issue by GravisZro** [w3c/encrypted-media#156]
It's stated in the abstract that the EME purpose it's for "providing APIs to control playback of protected content" but a standard (open) API undermines all content protection schemes using it thereby defeating its reason for existing.

There are a couple ways this can manifest:
- If the protected content, CDM, license requests/responses are all written to disk by the browser then they can be packaged into a single file for later playback.
- The CDM is architecture and OS agnostic, so it cannot make direct rendering calls.  As a result, any possible output from the CDM can be recorded to disk as an unprotected media format.

(sidenote: W3C members like Netflix have "promised" to not prosecute program authors therefore, content owners (e.g. Warner Bros.) will be prosecuting people that implement EME in a way that allows you to save content for later viewing under a DMCA violation claim.)

However, regardless of the reaction content owners have, the core purpose of this API is impossible to fulfill because it's paradoxical.  You cannot have a standard and open API for protected content because doing so intrinsically removes the protections.

**Comment by steelejoe** [comment]
There are a couple of inaccuracies or misconceptions above. Your statements _may _be true for some CDM (though none that I am aware of) but they are not true for _all _CDMs. 

A typical DRM protocol will operate more like SSL/TLS, with a handshake of some kind and some well known keys on each side. Protecting against replay attacks like you describe can be handled in largely the same way. DRM protocols are generally designed specifically to prevent this kind of attack.

There is no requirement that a particular CDM be either architecture or OS agnostic. I am not sure where you got that impression but please let us know so we can correct the text. Rendering of the content by the CDM is also allowed (although not required) so the video capture you describe may not be possible within the browser. You can see a reference to this in the flow diagram from the EME spec.

**Comment by GravisZro** [comment]
> There is no requirement that a particular CDM be either architecture or OS agnostic. I am not sure where you got that impression but please let us know so we can correct the text.

If CDMs are not run via some sort of virtual machine then you are creating a non-portable standard.  That seems like a giant flaw in itself.  People will be sued for reverse engineering CDMs despite the DMCA exemption of REing for compatability.  There is no way for this to end well.

> A typical DRM protocol will operate more like SSL/TLS, with a handshake of some kind and some well known keys on each side. Protecting against replay attacks like you describe can be handled in largely the same way. [...] Rendering of the content by the CDM is also allowed (although not required) so the video capture you describe may not be possible within the browser.

I did not specify that a browser would be used, only that EME would be implemented.  The CDM's target environment can be emulated and once emulated, you have full control over _all_ inputs and outputs for the CDM.  This attack _cannot_ be mitigated.

**Comment by steelejoe** [comment]
You are free to implement a user agent and CDM which allows for the capture of any and all content. However the ClearKey Key System probably gives you what you want and is easily implementable. 

Capture outside the user agent (for example via camcorder, special video drivers, inline video capture hardware, etc.) is outside the scope of this spec.

**Comment by GravisZro** [comment]
> Capture outside the user agent [...] is outside the scope of this spec.

I'm not talking about capture outside the user agent, this attack could be easily integrated into an existing user agent.  The spec itself removes the protections by standardizing the interface to the protected media.  Following the spec _is_ the attack vector, this is why EME is self-defeating.

**Comment by GravisZro** [comment]
From what I can tell, EME is predicated on the idea that the CDM is outside the control of the user agent.  However, what I am trying to explain is that by using emulation a.k.a. a virtual machine, you can execute and capture the input and output of a CDM does and therefore be able to replay the protected media.  Once done, this removes the protection of any and all CDMs.  You can do this in real-time and integrate it into a browser or render to an unprotected format.  The concept of EME/CDMs is flawed because by making a standard interface for protected media, you remove the only possible protection for media: security by obscurity.

**Comment by steelejoe** [comment]
> From what I can tell, EME is predicated on the idea that the CDM is outside the control of the user agent. 
The CDM in many cases is implemented by the same entity that implemented the user agent. In that case it has complete control. In other cases it may not be implemented by the same entity, but there is some trust established. Restrictions have been outlined in the spec to provide some best practices here. Primarily the user agent must have some level of trust in the behavior of the CDM before providing access to it.

> However, what I am trying to explain is that by using emulation a.k.a. a virtual machine, you can execute and capture the input and output of a CDM does and therefore be able to replay the protected media. 
I understand what you are explaining. What you are describing is _theoretically_ possible with any system for playing back encrypted media. This is an argument against encrypting media at all, not a technical argument against this proposed API.

**Comment by GravisZro** [comment]
> I understand what you are explaining. What you are describing is theoretically possible with any system for playing back encrypted media.

I laid out a very practical way it can be done with EME.

> This is an argument against encrypting media at all, not a technical argument against this proposed API.

The proposed API is literally "Encrypted Media Extensions" and you are saying an argument against encrypted media is non-applicable?  I'm saying the API is a pointless endeavour and you are saying that it doesn't matter because it's not a technical argument therefore not a reason to not do it?

This seems to be highly applicable: **"It is difficult to get a man to understand something, when his salary depends upon his not understanding it!"**

**Comment by mwatson2** [comment]
@GravisZro I don't think you did lay out a very practical way to circumvent content protections provided by CDMs operating under EME.

That said, it is well-known that the purpose of content protection is not to prevent all unauthorized access to the content (this is impossible) but rather to make such access difficult, to a degree defined in what are known as robustness rules.

A solution which did not meet these robustness rules would not be approved by content providers. It is hard to understand how the EME API, _per se_, has any impact on that aspect of the arrangement. For example, if we compare the situation with the prior one in which content is distributed to proprietary plugins such as Flash and Silverlight.

**Comment by GravisZro** [comment]
>  I don't think you did lay out a very practical way to circumvent content protections provided by CDMs operating under EME.

Allow me to clairify then: [libemu](https://web.archive.org/web/20150812195102/http://libemu.carnivore.it/) can be used to execute the CDM.  From that point, all DLL calls must go through libemu which enables anyone to easily record/replace all IOs.

> That said, it is well-known that the purpose of content protection is not to prevent all unauthorized access to the content (this is impossible)

Which is why it should **NOT** be done **at all**.

> A solution which did not meet these robustness rules would not be approved by content providers.

A) This is outside the scope of the spec.
B) Are you admitting that the ECE is being created for the sake of your corporate masters and not the common good?

**Comment by mwatson2** [comment]
So, I think the techniques CDMs use to avoid circumvention attempts of the kind you describe are very much out of scope too.

I understand it's your opinion that content protection should not be done at all because it is imperfect (and possibly for other reasons) but this opinion is not shared by the content industry.

The point of EME is to enable migration from a widely disliked system of proprietary plugins to something with better security and privacy properties for users, that is all. The EME ecosystem is in fact _more complex_ for service providers than the previous system, as we must support a different CDM for each browser, but this is a reasonable trade-off for the various advantages that EME has for both service providers and users.

**Comment by GravisZro** [comment]
> I understand it's your opinion that content protection should not be done at all because it is imperfect (and possibly for other reasons) but this opinion is not shared by the content industry.

What does the "content industry" have to do with the EME spec?  Stay on topic.  The EME is incapable of accomplishing its purpose.  That's the discussion.

> The point of EME is to enable migration from a widely disliked system of proprietary plugins to something with better security and privacy properties for users, that is all. 

Arguments against EME about DRM have been dismissed saying that the EME is not about DRM.  Therefore, you must adhere to this assertion _or_ address the comments against DRM.

**Comment by GravisZro** [comment]
Oh this is wonderful.  I looked up these jokers and it's **Joe Steele from Adobe** (lead engineer for Adobe Primetime) and **Mark Watson from Netflix** (director of streaming standards).  No conflict of interest here.  It's no wonder you guys can't bring your to the obvious conclusion that EME shouldn't exist: your jobs depend on it.

**"It is difficult to get a man to understand something, when his salary depends upon his not understanding it!"**

**Comment by mwatson2** [comment]
Joe and behave attempted to address your point in good faith, but if you are not interested in taking our comments seriously, there is little point continuing the discussion and I suggest we close this issue.

**Comment by mwatson2** [comment]
s/behave/I have

**Comment by GravisZro** [comment]
@mwatson2
No, what you have done so far is admit I am correct in my assertion that EME cannot perform its stated purpose and declare EME should proceed anyway because of Netflix's contractual obligations to the "content industry".

> it is well-known that **the purpose of content protection is not to prevent all unauthorized access to the content (this is impossible)** but rather to make such access difficult, to a degree defined in what are known as robustness rules.

> A solution which did not meet these robustness rules would not be approved by content providers.

My suggestion to avoid the entire EME boondoggle has been predicated entirely on contractual obligations to a small group of content companies.

> I understand it's your opinion that content protection should not be done at all because it is imperfect (and possibly for other reasons) but this opinion is not shared by the content industry.

The truth is that the overwhelming majority of the content is uploaded and served without any faux protection.  The contractual obligations of a few companies should not be forced upon the entire world because that's exactly what making EME a standard is doing.

If using non-standard systems is too much for Netflix to handle then they should renegotiate their contracts and if that is impossible then Netflix should use something else but one thing is for sure, **the point of international standards is not to prop up your company's business model.**  You know everything I've written is true but because of your economic position, you still want to push EME on the world knowing that it is ineffective.

**What will Netflix do when EME becomes a ratified standard and is then subsequently undermined by a simple solution?**  Will Netflix stand by this standard despite its ineffectiveness or will they abandon it because it cannot satisfy their contractual obligations?

**Comment by mwatson2** [comment]
> No, what you have done so far is admit I am correct in my assertion that EME cannot perform its stated purpose

I have not agreed with that assertion.

Regarding your other points above, I respectfully disagree. I refer back to my previous [comment](https://github.com/w3c/encrypted-media/issues/156#issuecomment-208544379) on the purpose of the EME work.

Regarding your original comment, you claim that the definition of a common Javascript API for multiple DRMs (which is all that EME is) somehow affects the effectiveness of those DRMs. I don't see how this could be the case.

**Comment by GravisZro** [comment]
> Regarding your original comment, you claim that the definition of a common Javascript API for multiple DRMs (which is all that EME is) somehow affects the effectiveness of those DRMs. I don't see how this could be the case.

In order to capture all content generated by any CDM, you simply need to run the the CDM in a virtual environment (using something like libemu) and record the arguments to DLL rendering calls.  Knowing how to interface with DRM systems is half the puzzle which in this case is EME.  The other half is capturing the output and since everything under the sun is going to support Windows, you only need to capture a few different rendering methods.  So, solving the puzzle of DRM with a standard interface is deprotecting the content.

If you are going to deprotect the content, you should change all instances of "protected" content phrasing to "encrypted" content.  At least that way the DMCA laws are not attached to the EME.

**Comment by GravisZro** [comment]
@mwatson2: Removing all instances of "protect", "protection" or any term indicating it will keep your content "safe" in any manner from the EME spec would resolve this bug.

**Comment by steelejoe** [comment]
@ddorwin @mwatson2  As I commented in the other bug added by @GravisZro this seems like it duplicates [bug 20944](https://www.w3.org/Bugs/Public/show_bug.cgi?id=20944) to some extent. 

@mwatson2 You may be on to something with the language change you suggested. I believe we have suggested just using "encrypted" and "encryption" in the past -- don't remember where that went. 

@GravisZro I think you would find that almost everyone working on this spec has an interest in making it work. Not because it furthers some evil agenda, but because it moves the needle a little closer to interoperability. Without this work, the natural outcome is not that companies will abandon DRM. The natural outcome is that companies who want this functionality will do exactly what they are doing today and standardize it to the extent possible outside of the W3C. My hope was that by doing this within the W3C we would get useful feedback and move towards better interoperability and better user privacy in an open forum. I believe (and I hope the editors would agree) we have received that feedback and that resulting players are better (i.e. more interoperable, better at respecting users privacy) than what existed before.

**Comment by GravisZro** [comment]
@steelejoe 

> You may be on to something with the language change you suggested.

that was actually me.

> I think you would find that almost everyone working on this spec has an interest in making it work.

Of course, they are getting paid to do it.

> Not because it furthers some evil agenda

I dunno, money is claimed to be the root of all evil, so I think that's still debatable. ;)

> but because it moves the needle a little closer to interoperability.

If that is true then you should be overjoyed by my [SPIR-V suggestion](https://github.com/w3c/encrypted-media/issues/157#issuecomment-209218898) because it will maximize interoperability.

> Without this work, the natural outcome is not that companies will abandon DRM. The natural outcome is that companies who want this functionality will do exactly what they are doing today and standardize it to the extent possible outside of the W3C

I have no expectation of DRM vanishing overnight but I know DRM won't survive long if it's standardized because that will be the source it's undoing.

**Comment by GravisZro** [comment]
resolved by https://github.com/w3c/encrypted-media/pull/160
