### ISSUE TITLE
Remove all "protection" language

### ISSUE THREAD

**Issue by GravisZro** [w3c/encrypted-media#159]
I've noticed that the EME is heavily salted with language about "protected" media.  However, the EME cannot guarantee any level of protection whatsoever.  As [mwatson2 admits,](156#issuecomment-208532031)

> it is well-known that the purpose of content protection is not to prevent all unauthorized access to the content (this is impossible)

Being that EME [removes a lot of obscurity that helps keep protected content safe](156#issuecomment-208976644) and thereby undermining it's protection, it seems only reasonable that there be no expectation of protection in the EME specification.

Also, to ensure that lawyers don't claim that EME is specifically for protected content thereby activating sections of the DMCA, all language regarding protection or safety in regards to content should be removed for the EME specification.

**Comment by paulbrucecotton** [comment]
>I've noticed that the EME is heavily salted with language about "protected" media.

I do not understand this since the word "protected" only occurs three times in the EME April 12 WD [1].  In addition the word "protection" only occurs about 13 times and many of those usages are not about "projected media".

Can you please be more specific about how you want the specification changed?

/paulc

[1] http://www.w3.org/TR/2016/WD-encrypted-media-20160412/

**Comment by ddorwin** [comment]
Focusing solely on the correctness of the use of "protected" and "protection" in the spec:
* I created #160 to remove some incorrect uses of "protected" and"protection".
* Most of the remaining occurrences of "protection" are references to mechanisms/techniques, "systems", and "providers". In the last two cases, these are referring to Key Systems and implementers/providers of them.
* A few uses of "protection" are completely unrelated to the media or Key Systems.

**Comment by GravisZro** [comment]
@paulbrucecotton
> I do not understand this since the word "protected" only occurs three times in the EME April 12 WD [1]

search instead of "protect" and you will find there are 21 instances on that page.

**Comment by mwatson2** [comment]
I think David's proposal in PR #160 should address this issue and indeed the "Clear Key" keysystem does not provide anything that would usually be called "content protection".

But, for the record:
- the fact that no security system is _perfect_ is well know, not really an "admission"
- EME does not impact any of the obscurity that is sometimes used in the implementation of DRMs (for example code obfuscation). This is a matter within the CDM. It may be useful to note that EME is not the API of the CDM itself: that is an internal API between the UA implementation of EME and the CDM
- none of the EME implementations make any attempt to restrict user modification of the EME implementation itself. Some are Open Source (Mozilla, Google). Such restrictions are constrained within the CDM.

**Comment by GravisZro** [comment]
@ddorwin: While your patch is an improvement, there are more instances to remove because content **cannot be protected**.  as mwatson2 wrote, ["this is impossible"](https://github.com/w3c/encrypted-media/issues/156#issuecomment-208532031).

**Comment by ddorwin** [comment]
@GravisZro, I believe you are referring to the items covered by my second bullet above. We need some term to reference these things. Constructive suggestions are welcome.

As to your assertion, note that @mwatson2 said (emphasis mine), "the purpose of content protection is **not** to prevent all unauthorized access to the content (this is impossible)." He was saying that _prevention_, not _protection_, is impossible. "Protection" does not mean infallible prevention. For example, a lock on your door provides some protection (when locked), but it does not _prevent_ someone from entering your house - that is impossible.

**Comment by GravisZro** [comment]
@ddorwin 
> "Protection" does not mean infallible prevention.

You are correct.  However, the EME interface in itself removes the protection of obscurity, thus deprotecting anything that could be considered protected.  Instead of a hidden door, you have pointed where the door is and the only thing keeping it from blowing wide open is the door handle.  The only protection remaining is if the person knows how to open a door.  EME does not interface with protected content, it interfaces with deprotected content.

**Comment by GravisZro** [comment]
@ddorwin It's worth noting that in the computer realm when something is "protected" that it is not possible to interfere with it through anything but extraordinary measures.  An AES256 encrypted message is protection that would require someone trying trillions of combinations to keep trying until the heat death of the universe before decrypting that message.  Programs cannot access protected memory without invading the kernel and taking control of the entire computer.  Protected member variables from a subclass cannot be accessed without using assembly language and even then it's iffy.  Nothing about CDMs is protected.  It might be considered "private" but saying anything to do with CDMs is "protected" is a misnomer at best.

**Comment by mwatson2** [comment]
@GravisZro The english word "protect" does not have the strong connotation you suggest. One may say "the umbrella protects me from the rain" for example. More precisely, it might be instructive to look at the [PlayReady robustness rules](https://www.microsoft.com/playready/licensing/compliance/) which define the nature of the measures that should be necessary to circumvent that DRM in various ways. The term "content protection" is commonly used to describe solutions providing the level of protection described there.

Nevertheless, EME of course does not imply any particular level of protection: that depends on the CDM.

Finally, please take a closer look at the [EME API](https://w3c.github.io/encrypted-media) itself. It does not "remove a lot of obscurity that helps keep protected content safe". You might be thinking about the API for a modular CDM itself, such as Mozilla's [GeckoMediaPlugin](https://wiki.mozilla.org/GeckoMediaPlugins). IIUC, Mozilla and Adobe have gone to some lengths to ensure the CDM can authenticate the environment in which is it running, but in any case, whatever properties their solution has is a matter for them, not an issue with the EME specification.

**Comment by GravisZro** [comment]
@mwatson2
> EME of course does not imply any particular level of protection: that depends on the CDM.

Then that needs to be expressed explicitly in the EME spec because as far as the law is concerned, being protected imbues it with it's own set of legal restrictions per the DMCA.

> It does not "remove a lot of obscurity that helps keep protected content safe"

It absolutely does.  it's defines the functional interface with the CDM/DRM and limits the scope of what it does to a very narrow set capabilities and rendering methods.  [It's like covering a bicycle in wrapping paper.](https://www.triathlonbox.co.uk/sites/default/files/styles/large/public/funny-pictures-bike-wrapped-up-present.jpg) You have removed the mystery and you are only left with the fine details which do not change how it's used.

> Mozilla and Adobe have gone to some lengths to ensure the CDM can authenticate the environment in which is it running

All you have to do is make a record of what works and feed it back to the CDM in a contained virtual environment.  This is as much protection as setting your password to "password".  ಠ_ಠ

**Comment by mwatson2** [comment]
> Then that needs to be expressed explicitly in the EME spec because as far as the law is concerned, being protected imbues it with it's own set of legal restrictions per the DMCA.

IANAL, but I believe the applicability of the law depends on exactly what the thing *is* (i.e. the actual implementations) rather than how well, or not, we describe it.

> It absolutely does. it's defines the functional interface with the CDM/DRM and limits the scope of what it does to a very narrow set capabilities and rendering methods.

Not really. You might be able to say this of an API for the CDM itself, but not of the EME specification which is at a much higher level (between UA and page). 

> All you have to do is make a record of what works and feed it back to the CDM in a contained virtual environment.

Well, you're welcome to try, but even if that were the case it would be a problem with that particular implementation not with the EME specification. Other implementations are very different.

**Comment by GravisZro** [comment]
@mwatson2
> I believe the applicability of the law depends on exactly what the thing is (i.e. the actual implementations) rather than how well, or not, we describe it.

Sure... but explain that to a judge who doesn't even understand that an interface specification is.  You need to be explicit.

> You might be able to say this of an API for the CDM itself, but not of the EME specification which is at a much higher level (between UA and page).

I did write "functional interface" rather than the exact interface because while the interface may differ, the basis of it (it's function) is directly linked to the EME.  You may not be able to use a CDM for UA 1 with UA 2 but that isn't the issue.  The issue is that by specifying that the interfaces of CDM 1 and CDM 2 will be the same (which is the effect of the EME), makes all CDMs vulnerable to a single attack that would make **all** of them ineffective.  Furthermore, by specifying the interface openly (the spec itself) reveals what information is being passed through the API to the CDM itself.

> Well, you're welcome to try, but even if that were the case it would be a problem with that particular implementation not with the EME specification. Other implementations are very different.

It's a generic attack method, it will work on all implementations.  Also, when you say I'm welcome to try, do you speak for your company too?  I'm certain the folks in legal would disagree with you.

**Comment by steelejoe** [comment]
@GravisZro Does issue 160 resolve this? If not -- can you explain why?

**Comment by GravisZro** [comment]
@steelejoe the 160 patch was an improvement but there are still instances of "protect" in regards to content when there should be none because it cannot be protected.  claiming it's protected is ingenuous at best and has serious legal ramifications.

**Comment by steelejoe** [comment]
@GravisZro I assume you are talking about the particular phrase "content protection"? This is a widely understood industry term of art. First page results on Google [show](http://www.digital-cp.com/) [many](http://www.contentprotectionsummit.com/la-2015/) [examples](http://www.amazon.com/gp/help/customer/display.html?nodeId=201460980) of this in common use. In my opinion changing this text would not serve to clarify what the spec is attempting to describe.

**Comment by josephlhall** [comment]
@steelejoe I think you mean PR #160 above, and that looks like a good fix for this issue, in my opinion. (I certainly don't think the spec needs to remove all the uses of the English work "protect" due to @GravisZro's concerns.)

**Comment by GravisZro** [comment]
@steelejoe 
Using the term "content protection" is like using the term "job creators" which is to say that both are deceitful and both are used by groups of people with legal interests.  The term "content protection" is used by "the content industry" for the express purpose of invoking the legal ramifications of the DMCA.  However, it does not accurately describe what is actually is, a restriction.  If you used the term "content restriction" then it would be more accurate by far.  The W3C isn't about serving any industry, so there is no need to serve them in the spec.

**Comment by GravisZro** [comment]
@josephlhall Just because you grasp the finer points of the DMCA doesn't mean the dumbest backwater judge they can find will understand anything but "content protection".

**Comment by GravisZro** [comment]
so after more thought, i've concluded that "obfustication" would be another acceptable replacement because it accurately describes what the misnomer "protection" is actually doing.  however, the spec is still perfectly intelligible with just completely removing all references to "content protection".

**Comment by paulbrucecotton** [comment]
I agree with several commenters that PR 160<https://github.com/w3c/encrypted-media/pull/160> adequately resolves this issue and ask that the Edtiors close this issue.

/paulc
HTML Media Extensions WG Chair

**Comment by GravisZro** [comment]
@paulbrucecotton 
You and the other commenters have conflicts of interest which compel you to reject removing the remaining protection language.  Ask for public comment and I bet my bottom dollar that you will get a much different response.

**Comment by ddorwin** [comment]
Closing per https://github.com/w3c/encrypted-media/issues/159#issuecomment-215513841 above.
