### ISSUE TITLE
Explicitly state "RFC words" should be interpreted per RFC2119

### ISSUE THREAD

**Issue by ddorwin** [w3c/encrypted-media#162]
The spec uses RFC2119 words MUST, MUST NOT, etc., and they are differentiated by ReSpec, but we do not reference RFC2119. We should explicitly document their interpretation like other specs do.

Examples:
* https://www.w3.org/TR/html5/infrastructure.html#conformance-requirements
* https://w3c.github.io/webappsec-secure-contexts/#conventions

As an aside, this seems like something ReSpec should insert automatically along with the formatting.

**Comment by paulbrucecotton** [comment]
>As an aside, this seems like something ReSpec should insert automatically along with the formatting.

@jdsmith3000:  Can you open a bug a ReSpec asking for this change since getting that bug resolved will be the "long pole" on this V1NonBlocking issue?

**Comment by mwatson2** [comment]
Turns our ReSpec does support this. Just add a section with `id="conformance`.

**Comment by mwatson2** [comment]
PR #254
