### ISSUE TITLE
Privacy: Ensure the user can clear all identifiers and other data that might enable tracking

### ISSUE THREAD

**Issue by ddorwin** [w3c/encrypted-media#168]
The spec requires that _Distinctive_ Identifiers be clearable but not _all_ potential identifiers. Examples include:
* Identifiers that don't match the definition of Distinctive Identifier (i.e. random values, especially after #117 is fixed).
* Persisted sessions and session data (#session-storage). (See [bug 27268 comment 5](https://www.w3.org/Bugs/Public/show_bug.cgi?id=27268#c5) by @hsivonen.)

<br/>In addition, as discussed in [bug 27268 comment 6](https://www.w3.org/Bugs/Public/show_bug.cgi?id=27268#c6), "we should add a note somewhere explaining [how] persistent sessions could be used to track users." To address this, we should explicitly mention persistent sessions and other persistent state in https://w3c.github.io/encrypted-media/#user-tracking is the most likely candidate.

It probably also makes sense to explicitly mention persistent sessions in:
* https://w3c.github.io/encrypted-media/#privacy-storedinfo
* https://w3c.github.io/encrypted-media/#incomplete-clearing
* Maybe https://w3c.github.io/encrypted-media/#private-browsing.

**Comment by ddorwin** [comment]
In addition, all traces of a session should be removed when the session data is removed (e.g. a call to `update()` containing the acknowledgement of a release message).

**Comment by ddorwin** [comment]
https://w3c.github.io/encrypted-media/#allow-identifiers-cleared says:
> Implementations should allow users to clear Distinctive Identifier(s) along with cookies [COOKIES] and other site data. It is recommended that users be offered the option to clear Distinctive Identifier(s) as part of user agent features to clear browsing history.

This same guidance should apply to all identifiers and persisted data. Specifically, similar text should be included in or referenced from:
* https://w3c.github.io/encrypted-media/#user-tracking
* https://w3c.github.io/encrypted-media/#privacy-storedinfo
* https://w3c.github.io/encrypted-media/#incomplete-clearing

Note: Addressing this may involve moving it from its existing location and referencing it from there.

**Comment by mwatson2** [comment]
https://w3c.github.io/encrypted-media/#privacy-storedinfo is already quite general. I'm not sure if needs modification for this issue.

Equally, https://w3c.github.io/encrypted-media/#incomplete-clearing consistently refers to "Distinctive Identifiers _and data stored by Key Systems_".

**Comment by mwatson2** [comment]
I created pull request #173 for this.

**Comment by mwatson2** [comment]
Reviewed at editors' meeting (@mwatson2 @jdsmith3000). This looks good. The PR needs to be rebased to make the diffs clear.

**Comment by mwatson2** [comment]
Diffs are unclear. @mwatson to rebase and generate clean diff.

**Comment by mwatson2** [comment]
See [htmldiff](https://services.w3.org/htmldiff?doc1=http%3A%2F%2Frawgit.com%2Fmwatson2%2Fencrypted-media%2F9eebaa4e6e0ea1dbd2d61f59cbafbe2be71d9678%2Findex.html&doc2=http%3A%2F%2Frawgit.com%2Fmwatson2%2Fencrypted-media%2Fc9bb525093cb700107eb5ec0c6d1153fb71fdc98%2Findex.html#implementation-requirements).

**Comment by ddorwin** [comment]
PR #173 addresses the core of this issue.

I believe we should also address the following before closing the issue (as a separate small PR).

>In addition, all traces of a session should be removed when the session data is removed (e.g. a call to `update()` containing the acknowledgement of a release message).

The `update()` algorithm already says "clear all stored session data associated with this object..." We could stress the _all_ by surrounding it with `<em>`. In addition, I propose that we specifically require the removal of all traces in [Session Storage and Persistence](https://w3c.github.io/encrypted-media/#session-storage).

Of the links in previous comments:
* https://w3c.github.io/encrypted-media/#user-tracking is addressed by PR #173.
* I filed #211 to track consolidation, specifically including https://w3c.github.io/encrypted-media/#privacy-storedinfo and https://w3c.github.io/encrypted-media/#incomplete-clearing.
* While we could specifically explain issues in https://w3c.github.io/encrypted-media/#private-browsing, it already references the other sections and does not go into details, so I think it is fine to leave this as is.

**Comment by ddorwin** [comment]
PR #173 has now been committed.

Before closing this (leaving remaining consolidation to #211), I think we should make one more small PR per my comment above. Comments?

>The `update()` algorithm already says "clear all stored session data associated with this object..." We could stress the _all_ by surrounding it with `<em>`. In addition, I propose that we specifically require the removal of all traces in [Session Storage and Persistence](https://w3c.github.io/encrypted-media/#session-storage).

**Comment by jdsmith3000** [comment]
Are you suggesting language in [Session Storage and Persistence](https://w3c.github.io/encrypted-media/#session-storage) that says the CDM must ensure identifiers or other data can be fully deleted?  I'm not sure what you mean by "all traces".

**Comment by ddorwin** [comment]
@jdsmith3000, I created #216 to address this.

**Comment by ddorwin** [comment]
The small PR to address my comment has been committed. Remaining consolidation will be tracked in #211.
