### ISSUE TITLE
Be explicit about how the lack of audioCapabilities/videoCapabilities in a configuration is handled

### ISSUE THREAD

**Issue by ddorwin** [w3c/encrypted-media#178]
The [Get Supported Configuration](https://w3c.github.io/encrypted-media/#get-supported-configuration) algorithm currently allows `audioCapabilities` and `videoCapabilities` to not be present in the `MediaKeySystemConfiguration`, but the spec does not specify how this is to be handled/interpreted.

When the capabilities member is present, the sequence must be non-empty and for each entry:
* `contentType` must be non-empty.
* `robustness` may be empty, in which case we rely on this text from the [definition](https://w3c.github.io/encrypted-media/#widl-MediaKeySystemMediaCapability-robustness) of this member: "The empty string indicates that any ability to decrypt and decode the content type is acceptable."

I see two options:

**Option 1: Require these members be present.**
There may not be sufficient reason to allow these members to be optional. Applications _should_ specify them in most cases, especially since this should improve the chances of success across client implementations.

I can think of two scenarios where they legitimately might not need to be specified:

1. Audio-only content: `videoCapabilities` is unnecessary.
1. Managing persistent state: Content type is irrelevant and it's simpler to not specify types to cover all implementations.

(1) can be supported by a) stating that content types not specified are not supported by the instance or b) requiring an explicit indication, such as an empty list. We could additonally prohibit not specifying _both_ members, which would ensure there is always a robustness specified (even if per the existing text regarding the empty string).

It may not be necessary to support (2):
* Even when media data won't be decrypted by the instance, robustness is still relevant as discussed above.
* It is probably better to fully specify the requirements so the `MediaKeySystemAccess` (and `MediaKeys`) object can be reused for playback and to avoid the potential for multiple user consent requests.

**Option 2: Specify the behavior.**
Specify something similar to the text for `robutstness` as the behavior when `audioCapabilities` or `videoCapabilities` - and perhaps both - are not present.

In such cases, there will be no guarantees of any audio or video type support, respectively. Thus, the most important clarification is the robustness level, perhaps especially when neither member is present. (We should consider that robustness could theoretically be relevant even when no content is to be decrypted. As a hypothetical example: case (2) above if there multiple pipelines.)

We could specify this in the two member definitions. Along with `robustness`, I wonder whether we should also normatively specify this in the algorithm steps or non-normatively refer to the definition at the appropriate step in the algorithm.

**Comment by joeyparrish** [comment]
I use a query with an empty config to establish the presence or absence of a particular key system.  Example:

```js
    var testKeySystems = [
      'org.w3.clearkey',
      'com.widevine.alpha',
      'com.microsoft.playready',
      'com.apple.fps',
      'com.adobe.primetime'
    ];

    testKeySystems.forEach(function(keySystem) {
      navigator.requestMediaKeySystemAccess(keySystem, [{}])
          .then(function() {
            support[keySystem] = true;
          }, function() {
            support[keySystem] = false;
          });
    });
  }
```

This is part of a `support()` method that the application can use to query the platform's rough capabilities.  This is not used during playback.  It is just for reporting to the application if it asks.

When we are actually playing content, we specify audio and video capabilities, except when there are no encrypted tracks of a particular type.  For example, if there is encrypted video and clear audio, we will set `audioCapabilities: undefined`.  I have a note in our source from January 2016 that states that queries with `audioCapabilities: []` would fail.

**Comment by ddorwin** [comment]
This `support()` method could cause a user prompt and likely does on some platforms. In theory, there could be multiple prompts for multiple key systems or a second prompt for playback if the configuration used has different requirements. There is currently no way to query key system support without the potential for a prompt.This is by design to allow implementations to prompt for permissions or download before responding. See [bug 25923](https://www.w3.org/Bugs/Public/show_bug.cgi?id=25923).

Do you know why or how this `support()` method is used? If this is a use case we want to support, we might consider a dedicated method that provides a hint but no guarantees.

I wonder whether `audioCapabilities: undefined` should be interpreted as `audioCapabilities` being "[present](https://heycam.github.io/webidl/#dfn-present)," which is what caues the Get Supported Capabilities for Audio/Video Type algorithm to be run. Chrome's developer tools treats it as a member with the value `undefined`. If setting it to `undefined` does mean it is present, I would expect `audioCapabilities: undefined` to fail because the result of the algorithm will be `null`.

**Comment by joeyparrish** [comment]
This `support()` method is something Shaka Player provides starting in v2-beta for two purposes:

1. Check for basic API support (does the browser have HTML5 video, MSE, EME and other necessary APIs)
2. Probe each API and provides details on types and key systems that are supported

If we *really* shouldn't probe EME for key systems, we should change that functionality in Shaka while v2 is still in beta.

The reason we set `audioCapabilities: undefined` instead of not having it at all stems from a quirk of the Closure compiler (IIRC).  We define an external record type for `MediaKeySystemConfiguration`, and I seem to recall that omitting a field was not allowed by the compiler.  I just retested this, and Closure currently allows it.  Either I misremember, or I misunderstood at the time, or updates to Closure have fixed this quirk.

So, open questions from Shaka Player:

1. Should I stop probing key systems in `shaka.Player.support()`?
2. Should I omit `audioCapabilities` instead of setting it to `undefined`?

**Comment by ddorwin** [comment]
>1. Should I stop probing key systems in `shaka.Player.support()`?

I believe so. You can check whether EME is supported by checking for the presence of `navigator.requestMediaKeySystemAccess`, but I do not think it is a good idea to probe key systems as part of normal production behavior given the potential UX impact. If you do probe, it would be best to do so with the actual configurations you would use. Probing could also be done as part of diagnostics or something like that, but I would label any just library method as for use only in such scenarios.

>2. Should I omit `audioCapabilities` instead of setting it to `undefined`?

I believe so. I'll get clarity on the meaning of "[present](https://heycam.github.io/webidl/#dfn-present)," but not using `undefined` seems safer.

**Comment by ddorwin** [comment]
I propose that we adopt Option 1 in the original comment above. It seems easier to document, understand, and implement, and it encourages authors to provide capabilities, which should result in a better user experience across client implementations.

Assuming this choice, we then need to decide how to handle audio- or video-only content. We could allow either `audioCapabilities` or (exclusive) `videoCapabilities` to contain an empty list and indicate that there will be no audio or video streams, respectively. See also #197, which relates to unencrypted streams.

**Comment by ddorwin** [comment]
We have positive feedback form Mark on the proposal. I think we can move forward with implementation.

The remaining question is how to handle audio- or video-only content. For the sake of having a proposal, I'll propose that both are optional **but** we have a check that both are not "not present." If a capabilities item is not present, that will indicate that no decryption/decoding of that _Audio/Video Type_ is required.

**Comment by mwatson2** [comment]
Just to check, what I intent to implement makes the `audioCapabilities` and `videoCapabilities` mandatory, but allows an empty list to be provided for at most one of them.

**Comment by mwatson2** [comment]
Pull Request #204

**Comment by mwatson2** [comment]
PR reviewed at editors' meeting (@mwatson2 @jdsmith3000) with no comments.

**Comment by ddorwin** [comment]
>Just to check, what I intend to implement makes the audioCapabilities and videoCapabilities mandatory, but allows an empty list to be provided for at most one of them.

This was the original proposal, then I flipped to it being optional in my last comment. However, I now think an empty sequence is the best solution for at least the following reasons:
* It moves us closer to most members of `MediaKeySystemConfiguration` having a default value or being required.
* It is simpler to handle (especially with the next item).
* We can simplify the algorithm and ensure it is always present by using a default value of `[]`.

If we do that last item, all members will have a default value except:
* `label` - really only for debugging
* `initDataTypes`
   - We could make a similar argument for this as we did in this issue, though you don't really need an initDataType to `load()` a session.
   - Regardless, we could also use a default of `[]` to simplify our logic.
   - Thoughts? Should we open another non-blocking issue?

Note: `sessionTypes` does not have a default in the IDL, but the prose essentially specifies a default of `[ "temporary" ]`. I don't believe Web IDL allows default sequence values other than the empty sequence.

**Comment by mwatson2** [comment]
I think a default value of [ ] is better: making it required means a change in implementations that could be a breaking change for some sites (something that previously might have worked would instead return a WebIDL conversion error).

I'll update the PR.

**Comment by mwatson2** [comment]
@ddorwin @jdsmith3000 @mwatson2 discussed at Editors' meeting. Our proposal is to define [ ] as default for all of `videoCapabilities`, `audioCapabilities` and `initiDataType` and make appropriate adjustments to the logic.

The only behavior change is that it becomes required to specify a non-empty list for at least one of `videoCapabilities` and `audioCapabilities`.
