### ISSUE TITLE
MediaKeySession.remove() and close() should mark session's keys as "unknown"

### ISSUE THREAD

**Issue by cpearce** [w3c/encrypted-media#18]
The spec should have a note that MediaKeySession.remove() and close() mark session's keys as "unknown", and that the "update usable keys" algorithm should be run.

It should be clear that closing/removing a session doesn't make the known keys "expired".

**Comment by ddorwin** [comment]
Should the keys' statuses be set to `"unknown"` or should the keys be removed from the list, meaning `keyStatuses` would be empty. The latter seems more appropriate.

See [Known Key](https://w3c.github.io/encrypted-media/#known-key). Specifically, "Keys only become unknown when they are explicitly removed from a session", though that was originally written with `update()` in mind.

Regardless of the behavior, I think we should specify it in the [_session close_](https://w3c.github.io/encrypted-media/#session-close) algorithm, which runs as the result of `remove()`, `close()`, and anything else that causes the session to be closed.

We also need to determine the behavior for "released" keys, especially when a "persistent-release-message" is loaded. Should `keyStatuses` be empty or contain all the keys with a new status? I'll update #16.

**Comment by steelejoe** [comment]
I agree. I think the keys should simply be removed from the list.

**Comment by jdsmith3000** [comment]
I also agree that keystatus should be empty when remove is run.  I believe the same is true for released keys.  Persistent keys can be reloaded and then have a valid status.
