### ISSUE TITLE
Keys in other sessions MUST be unaffected by closing a session, even if there are overlapping key IDs.

### ISSUE THREAD

**Issue by ddorwin** [w3c/encrypted-media#186]
The spec currently says:
>Keys in other sessions SHOULD be unaffected, even if they have overlapping key IDs.

This issue proposes to change the SHOULD to a MUST:
>Keys in other sessions MUST be unaffected, even if they have overlapping key IDs.

As discussed in https://github.com/w3c/encrypted-media/pull/184#discussion-diff-62884927, "it seems this SHOULD should be MUST. Otherwise, there is a difference in observable behavior. At a minimum, non-overlapping key IDs should be unaffected, but I think the spec should expect correct and consistent behavior unless there is a good reason not to." @mwatson2 agreed.

If there are no objections by May 20th, we will make this change.

**Comment by ddorwin** [comment]
There is another similar statement:
>Keys from different sessions SHOULD be cached independently such that closing one session does not affect keys in other sessions, even if they have overlapping key IDs.

This statement will also be updated:
>Keys from different sessions MUST be cached independently such that closing one session does not affect keys in other sessions, even if they have overlapping key IDs.

**Comment by ddorwin** [comment]
Oops. I didn't mean to change the milestone. Since we plan to fix this Friday, though, I'll set it to V1.

**Comment by steelejoe** [comment]
One small modification I would suggest -- 

> Keys from different sessions MUST be cached in such a way that closing one session does not affect keys in other sessions, even if they have overlapping key IDs.

The other way seems to imply different storage locations, as opposed to maintaining a ref count on the keys in memory. Maintaining a ref count seems like an acceptable implementation as long as the app visible behavior is as described.

**Comment by ddorwin** [comment]
@steelejoe, that seems fine, though it makes me wonder whether we should be addressing more than just the keys. For example, the observable behavior should be that key policies should be entirely independent as well.

Also, I think we should say something other than "cached," which is only used normatively in this sentence (and non-normatively above it). I think we are referring to the in-memory representation. I think we really want to say, "stored" (not necessarily persisted) or "represented" such that...

**Comment by steelejoe** [comment]
@ddorwin Agreed. Maybe we could say something more general like -- "State information for different sessions that is associated with a key ID MUST be stored in such a way that closing one session does not affect the application visible behavior in another session, even if they have overlapping key IDs."

**Comment by ddorwin** [comment]
@steelejoe, thanks for the suggestion! Below is a slightly modified version of your text.

>State information, including keys, for each session MUST be stored in such a way that closing one session does not affect the observable state in other session(s), even if they contain overlapping key IDs.

**Comment by ddorwin** [comment]
The commit message should have been "Fix #186: Keys in one session **MUST be unaffected** by other sessions" ("NOT" removed).
