### ISSUE TITLE
Be more explicit about the implications of empty robustness strings

### ISSUE THREAD

**Issue by ddorwin** [w3c/encrypted-media#196]
The [definition](https://w3c.github.io/encrypted-media/#widl-MediaKeySystemMediaCapability-robustness) of the `robustness` dictionary member currently says, "The empty string indicates that any ability to decrypt and decode the content type is acceptable."

To help authors (and discourage use of the empty string), the spec should more explicitly state the meaning of "any ability" and possible implications, which may include configuration of the CDM (see #177) to the lowest robustness level the Key System supports.

**Comment by mwatson2** [comment]
On reviewing this, I'm not convinced we need a clarification. "any ability" is quite clear and this is a specification, not a user guide. The `robustness` string is a best effort request passed through non-robust code anyway. Verifying the actual level of robustness available happens in the CDM message exchange.

**Comment by ddorwin** [comment]
I created PR #257 with proposed text.
