### ISSUE TITLE
ReSpec sources cannot be used with the W3C HTML diff service

### ISSUE THREAD

**Issue by ddorwin** [w3c/encrypted-media#198]
When reviewing pull requests, it can be helpful to diff the resulting HTML with the previous version of the document. PRs often don't initially include the generated file (or it becomes out of date), so it is best to diff against the -respec.html files.

The problem is that the W3C HTML diff service (http://services.w3.org/htmldiff) does not expand relative addresses in the compared document relative to the source address. Such URLs become relative to the diff service (i.e. `https://services.w3.org/encrypted-media.js`). As a result, images, custom CSS, and - most importantly - the spec-specific JavaScript are not loaded. The missing JavaScript causes ReSpec to fail, which causes many diffs that have nothing to do with the actual change to be displayed.

As an example, see this [diff of the current ReSpec source against the generated file](http://services.w3.org/htmldiff?doc1=https%3A%2F%2Fw3c.github.io%2Fencrypted-media%2F&doc2=https%3A%2F%2Fw3c.github.io%2Fencrypted-media%2Fencrypted-media-respec.html).

Note: When diffing PRs, you must use the RawGit URLs for the raw GitHub URL of the -respec.html file you want to use.

**Comment by ddorwin** [comment]
The commit above works around this issue by rewriting the relative resources the first time the ReSpec source is loaded.

There are caveats:
* Only encrypted-media-respec.html files can be compared.
 - Generated files cannot be diffed due to a limitation in the diff service. See the comments for details.
   - For this reason, the example dif above still fails but for different reasons.
 - I did not apply the workaround to registry file.
* The current version of the JS, CSS, and image files in the trunk will be used.
 - This may cause some issues, especially when updating the macros.
 - (It is probably possible to determine the correct path from the query string of the diff service URL.)
* There are still a bunch of warnings and logs from ReSpec, but they do not appear to affect the output.

FYI @wolenetz.

**Comment by ddorwin** [comment]
@dontcallmedom FYI on the issues using https://services.w3.org/htmldiff.

So I don't forget, here's a wish list for the diff service:
 * Much wider fields for the URLs. It is hard to edit them to replace the commit hash.
 * Address this issue for everyone.
 * Correctly handle `<script>` inside `<body>` (i.e. by not trying to diff it).
  - See the console error messages for the [diff of the current ReSpec source against the generated file](http://services.w3.org/htmldiff?doc1=https%3A%2F%2Fw3c.github.io%2Fencrypted-media%2F&doc2=https%3A%2F%2Fw3c.github.io%2Fencrypted-media%2Fencrypted-media-respec.html).
 * Automate the process of building URLs for a given commit in GitHub. Maybe this should be an extension.

**Comment by dontcallmedom** [comment]
I've now made the URL fields as wide as possible.

Re viewing diff of respec-generated documents, I think the "simplest" approach is to use the [spec generator](https://labs.w3.org/spec-generator/) to obtain the generated version out of the HTML source.

I think the diff algorithm could be smarter, but at the moment (scarily enough), the on-line service is basically a wrapper around a perl script which itself invokes `diff`, so there is only so much that can be made smarter about it. I think it could be made more powerful and easier to maintain by using [python difflib](https://docs.python.org/2/library/difflib.html) or possibly one of the HTML diff libraries that have been built on top of it ([htmldiff](https://github.com/mitsuhiko/htmldiff), [htmltreediff](https://github.com/christian-oudard/htmltreediff/), [another htmldiff](https://github.com/aaronsw/htmldiff/blob/master/diff.py)), or by porting the existing algorithm in the perl script to python — but any of those are more than a quick fix :)

Regarding automating the building of URLs for github commits, do you have something specific in mind?

**Comment by mwatson2** [comment]
I still get respec warnings for all the definitions, and so the links for those defined terms do not show up in the diff. See [this example](https://services.w3.org/htmldiff?doc1=http%3A%2F%2Frawgit.com%2Fmwatson2%2Fencrypted-media%2Ff8636f760d1d230403990bfca8ec59967729b30e%2Fencrypted-media-respec.html&doc2=http%3A%2F%2Frawgit.com%2Fmwatson2%2Fencrypted-media%2Fff15980d84cf7f5ecbde96a9a881840070779b2e%2Fencrypted-media-respec.html).

**Comment by plehegar** [comment]
Should be addressed by https://github.com/w3c/encrypted-media/commit/b5d8c5a088b8adfaa6c32ec75f9d617d6e3cb1d4
