### ISSUE TITLE
Ensure session type is correct for loaded sessions

### ISSUE THREAD

**Issue by ddorwin** [w3c/encrypted-media#20]
[Bug 27111](https://www.w3.org/Bugs/Public/show_bug.cgi?id=27111) split the persistent session type in two, but the `load()` algorithm does not ensure that the type the session was originally created with matches the type of session into which it was loaded. In addition to correctness, this will be important when #16 is resolved and the algorithms behave differently depending on the session type.

The best and simplest option is to update the the `load()` algorithm to ensure that the (new) `MediaKeySession` object was created (`createSession()`) with the correct/matching type. This ensures that the application knows what behavior to expect. This should be reasonable for most applications since they are unlikely to mix the two types of "persistent-" sessions.

**Comment by steelejoe** [comment]
This makes sense, although I wish we could figure out a simpler way to handle this. Presumably this would fail by rejecting the Promise with a message indicating the type of failure?

**Comment by steelejoe** [comment]
Also -- to handle the case where license removal receipts are being used with persistent licenses should we establish a precedence between the two types? I can imagine a cached session with "persistent-release-message" being loaded into a new session created with "persistent-license" but not the reverse.

**Comment by ddorwin** [comment]
"persistent-license" sessions can still send removal receipts. "persistent-release-message" is for non-persisted licenses that must persist the release message. Thus, in the scenario you described, you would always use "persistent-license".

**Comment by ddorwin** [comment]
I think b7afb88 addresses a different issue (one that is already addressed elsewhere).

b7afb88 checks whether the object's _session type_ is in the list of `sessionTypes` in the `MediaKeySystemConfiguration` used to create the `MediaKeys` that was used to create the `MediaKeySession`. We already handle this in the first step of the `createSession()` algorithm.

This bug was about ensuring that the `MediaKeySession` object's _session type_ is the same as the object that originally stored the session. In other words, it is the same as that of the `MediaKeySession` object on which `generateRequest()` was called.

We should revert the step added in b7afb88 and add a new step under the "Use the cdm to execute the following steps:" step.

**Comment by jdsmith3000** [comment]
I agree with your comment.  I'll revert the change and replace it with a new one.

**Comment by jdsmith3000** [comment]
Updated to add this step:

5.If the object's session type is not the same as the current MediaKeySession session type, return a promise rejected with a new DOMException whose name is InvalidAccessError.

**Comment by ddorwin** [comment]
The step was added in the wrong location. See #131. It should be moved to a substep of step 8.8 where the issue box is and be updated to reference the stored session's session type.

**Comment by jdsmith3000** [comment]
My new commit moves the session check, references the stored session and deletes the issue the change addresses.  It's now in step 8.8.2 under load().

**Comment by jdsmith3000** [comment]
Fix checked in 12 days ago.  Issue should be closed.
