### ISSUE TITLE
Add "pending" or [temporarily] "unknown" value to MediaKeyStatus

### ISSUE THREAD

**Issue by ddorwin** [w3c/encrypted-media#21]
Determining key status, especially for output protection (`"output-downscaled"`or `"output-not-allowed"`), may take time. The spec currently says to use the status "that corresponds to the reason for the additional processing."

However, without a separate status, an application will not know whether that reported status represents a temporary state or the actual (determined) state - there will be no subsequent event or status change for which the application can wait.

If the status is instead set to a [temporarily] unknown state, the application will know to expect the status to change, and a `keystatuseschange` event would be fired when the status is finalized.

As a specific example, when a license is initially provided, applications currently cannot differentiate between HDCP not being supported and HDCP negotiation in progress. The interim `"output-not-allowed"` or `"output-not-allowed"` status would likely cause an application to behave (i.e. fetching appropriate streams) as if HDCP is not supported. An application might behave differently if the status is temporarily unknown.

Another potential use of an `"unknown"` status value would be for platform-based CDM impelmentations that do not support key statuses. However, it seems there is a good chance that such platforms do not expose the key IDs either. If we don't need to address this case, we could name the state something more specific, such as `"pending"`. Alternatively, we could add both for the different use cases.

**Comment by steelejoe** [comment]
Re: the "pending" status
I am not sure this adds any value. Why would we not advise the application developer to always expect the status to change? 

For example - you could have this sequence:
<pending>
<output-downscaling>
<pending>
<ready>
<pending>

This would represent content being downscaled, the end user plugging in display with appropriate protections (no longer downscaling), the user unplugging the device and then closing browser tab (before the determination of status). 

Re: the "unknown" status
I am not sure what this would convey to the application. Presumably even a platform-based implementation will know whether it has a key or not. Can you be more specific?

**Comment by ddorwin** [comment]
re: `pending`
I think we may be thinking about different scenarios - you mentioned plugging in an appropriate display, which would seem like a corner case, where I am concerned about the time it takes to determine whether the current display(s) are appropriate.

The purpose is to enable the application to make decisions about which streams to fetch. If you remove pending from your sequence, you get:
>`output-downscaled`, `usable`

If the display is never compatible, the application only ever sees:
>`output-downscaled`

When does the application know that it won't see `usable` and should start fetching different streams? That's the intended purpose of `pending`.


re: `unknown`:
There are existing DRM implementations that do not expose key IDs and/or statuses but otherwise support EME (see #32). `unknown` would address the case where key IDs but not statuses are exposed. As I noted, this seems unlikely and can probably be ignored.
