### ISSUE TITLE
Information Stored on User Devices Mitigations section is structurally inconsistent.

### ISSUE THREAD

**Issue by ddorwin** [w3c/encrypted-media#210]
PR #202 fixes the requirement inconsistencies identified in issue #187. However, the structure of the Mitigations subsection of the [Information Stored on User Devices](https://w3c.github.io/encrypted-media/#privacy-storedinfo) section remains internally inconsistent and inconsistent with other Mitigations sections. This issue tracks editorial changes to address this and is low priority.

Specifically:
* The Mitigations section begins with "In summary," but not all items in the summary are covered in the following subsections.
* This is the only Mitigations section that includes a "summary." All others either do not have subsections or only have subsections.

**Comment by mwatson2** [comment]
PR #264
