### ISSUE TITLE
Update the PR merge process in TEAM.md

### ISSUE THREAD

**Issue by ddorwin** [w3c/encrypted-media#214]
As discussed in https://lists.w3.org/Archives/Public/public-html-media/2016May/0015.html and now being practiced by the ediors, we can use the big green merge button for PRs. We need to update the process documented in [TEAM.md](https://github.com/w3c/encrypted-media/blob/gh-pages/TEAM.md).

As part of this, we should include guidance about ensuring the commit message is clean. For example:
1. Click the green "Merge pull request" button.
2. Choose to squash and merge.
3. Click the green "Confirm squash and merge" button.
4. Clean up the commit summary - single line field of bold text.
   - Generally use the format `Issue #123: Description` or `Fix #123: Description`.
   - Use "Fix" if this merge resolves all items in the issue and the issue should be closed.
5. Clean up the additional commit text in the multiline text box below the summary.
   - Most often, you will want to delete all the text.
   - The most likely exception is when there was some useful additional information in one of the commit messages in the PR. You may also want to provide some additional information in addition to the summary.

**Comment by ddorwin** [comment]
It may be necessary to use `git merge` instead of `git rebase` locally for this flow to work.

**Comment by plehegar** [comment]
This one needs to be closed at this point and be reopened if there is new information.
