### ISSUE TITLE
Privacy: Clarify "distinctive identifier" around multiple users.

### ISSUE THREAD

**Issue by xhwang-chromium** [w3c/encrypted-media#223]
In the spec about "Non-Associable Identifiers", it says:

> Implementation must not expose associable identifiers to applications, even in encrypted form, across origins or across clearing of identifiers.

Other than across "origins" and across "clearing of identifiers", there is another case which could be sensitive: across "multiple users". For example, multiple OS user accounts, or multiple user profiles (if supported by the user agent) . It feels bad if a JS application (origin) can associate different users using the same device through the distinctive identifier.

Should we add some requirement or recommendation that "implementation should not expose associable identifiers to applications across different users"?

**Comment by ddorwin** [comment]
"[operating system] user account" and "profile" are both mentioned  in several non-normative **Concerns** sections but except for one instance of "profile" are not covered in the corresponding normative **Mitigations** sections or elsewhere. The fix for this may be as simple as ensuring we explicitly cover these in the corresponding **Mitigations** sections.

**Comment by mwatson2** [comment]
The proposal for #224 defines "user agent profile" which could then be used in the normative identifier requirements.

**Comment by ddorwin** [comment]
The referenced spec section is now **Associable Identifiers** and says:
>All identifiers, including Distinctive Identifiers, exposed by the implementation to applications, even in encrypted form, across origins or across clearing of identifiers must be non-associable by applications.


<br/>PR #287 adds "browsing profiles," which includes OS user accounts, to that list and most other places that reference per-origin identifiers.
