### ISSUE TITLE
Use consistent terminology for browsing/user agent profile

### ISSUE THREAD

**Issue by ddorwin** [w3c/encrypted-media#224]
Currently, the spec uses "profile," "browsing profile," and "user agent profile" to refer to the same thing. We should be consistent. I wonder if there is a standard term we should use and/or reference (like COOKIES).

**Comment by mwatson2** [comment]
I don't think there's a standard term since likely the types of capabilities offered in this regard vary from user agent to user agent. I suggest we say "user agent profile", subsume accounts into this, and define it as follows:

> *User Agent Profile*
>
> A User Agent on a given machine may support execution in a variety of different contexts or modes that are expected to behave independently in respect of page visible data. In particular, all stored data is expected to be independent. In this specification we refer to such independent contexts or modes as "User Agent Profiles".
>
> Examples of such independent contexts are if the user agent is running in different user accounts or if the user agent provides the capability to define multiple independent profiles for a single account.

**Comment by mwatson2** [comment]
PR #263

**Comment by ddorwin** [comment]
>I suggest we say "user agent profile", subsume accounts into this...

While including user accounts in the definition is fine, I think (OS) user accounts are still worth calling out in some cases.
