### ISSUE TITLE
Normatively referenced recommendations in Allow Identifiers to Be Cleared algorithm have been moved

### ISSUE THREAD

**Issue by ddorwin** [w3c/encrypted-media#226]
The behavior of the Get Consent Status algorithm depends on whether the "any of the recommendations of Allow Identifiers to be Cleared are not supported." These recommendations were moved to a new section in https://github.com/w3c/encrypted-media/commit/5f51c491baa1ebf4360550d574ffd5484f1d95d3.

We need to do something to restore the intended unambiguous reference to these recommendations. Options include adding a reference to the new Allow Persistent Data to Be Cleared section at the same point or somehow noting that the already-referenced section includes everything in the new section.

To help avoid such issues in the future, we should also add a comment to the source that notes that the section is referenced by an algorithm.

**Comment by jdsmith3000** [comment]
PR applies "Allow Identifiers to Be Cleared" **and** "Allow Persistent Data to Be Cleared" in the Get Consent State step.

I've not added an "Section is referenced by an algorithm" text to these sections.  I believe that would apply to other sections as well, and perhaps isn't needed for V1.  It also might be done as an editorial change.

**Comment by ddorwin** [comment]
>I've not added any "Section is referenced by an algorithm" text to these sections. I believe that would apply to other sections as well, and perhaps isn't needed for V1. It also might be done as an editorial change.

My suggestion was to add this as a comment in the source as a note for editors or anyone else that might be changing the section. It would not be visible. I agree this can be done at any time as an editorial change.

**Comment by ddorwin** [comment]
Fixed by the commit above.

**Comment by mwatson2** [comment]
Sorry, I missed this one.

Strictly speaking, the change here adds new requirements above those that were in the original text. The requirement in _Get Consent Status_ is related only to Distinctive Identifiers, not to persistent data in general. Whether you need to prompt, or merely inform, depends on whether the recommendations are followed _for Distinctive Identifiers_ and not on whether those recommendations are followed for other kinds of persistent data. So, we should say:

> ... any of the recommendations of Allow Identifiers to be Cleared are not supported or any of the recommendations of Allow Persistent Data to be Cleared are not supported in respect of Distinctive Identifiers.

**Comment by ddorwin** [comment]
SGTM. I assume you meant "..." at the end and not a period.

**Comment by mwatson2** [comment]
PR #236
