### ISSUE TITLE
It may not be possible to return undefined from MediaKeyStatusMap.get()

### ISSUE THREAD

**Issue by ddorwin** [w3c/encrypted-media#233]
The [definition](https://w3c.github.io/encrypted-media/#widl-MediaKeyStatusMap-get-MediaKeyStatus-BufferSource-keyId) of `MediaKeyStatusMap`'s `get()` method says:
> Returns the `MediaKeyStatus` of the key identified by _keyId_ or `undefined` if the status of the key identified by _keyId_ is not known.

This text was added for #70 with the goal of being consistent with the [ES6 Map interface's get()](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-map.prototype.get). We cannot just use `maplike` for the reasons in #25 and #39.

In an implementation discussion, @foolip said, "The IDL says that the return value is a MediaKeyStatus, and undefined is not of that type."

Is there a way we can be consistent with the behavior of `Map`?

**Comment by mwatson2** [comment]
Can't we just update the IDL so that the return type as `(MediaKeyStatus or void)` ?

**Comment by foolip** [comment]
https://heycam.github.io/webidl/#es-void says that "The only place that the void type may appear in IDL is as the return type of an operation."

Making the type nullable seems like the simplest solution, but it makes it less likely that you'll ever be able to migrate this to some future `setlikeusingvalue<>` thing.

**Comment by mwatson2** [comment]
Isn't the return type of an operation exactly where we want to use it ? (Return type of get())

**Comment by foolip** [comment]
Oops, I was also reviewing something related to an attribute's type today and didn't flush the cache. `(MediaKeyStatus or void)` should presumably work, even though I've never seen it and it could require changing the bindings generator in Blink to actually implement.

**Comment by mwatson2** [comment]
PR #239

**Comment by ddorwin** [comment]
This seems like what we want, but I'm not sure the current Web IDL grammar allows this. https://heycam.github.io/webidl/#prod-ReturnType says
```ReturnType	→	Type
 | "void"```
which  means one of these two.

[`Type`](https://heycam.github.io/webidl/#prod-Type) can be a `UnionType` (`(TypeA or TypeB)`), but I don't see how `void` can be a `UnionMemberType`.

@heycam and @bzbarsky, can you comment on whether this should be possible or how else we can match the behavior of `Map`/`maplike`?

**Comment by bzbarsky** [comment]
You use "any" and prose, most simply.

**Comment by mwatson2** [comment]
Well, from a pure BNF perspective, `void` matches the `identifier` choice in `[NonAnyType](https://heycam.github.io/webidl/#proddef-NonAnyType)`.

**Comment by bzbarsky** [comment]
It matches the regexp, but it does not produce the `identifier` token.  See http://heycam.github.io/webidl/#idl-grammar where it says:

> If the longest possible match could match one of the above named terminal symbols or one of the quoted terminal symbols from the grammar, it MUST be tokenized as the quoted terminal symbol. Thus, the input text “long” is tokenized as the quoted terminal symbol "long" rather than an identifier called “long”

So the string "void", after it comes out of the tokenizer, is tokenized as the terminal symbol "void", not an `identifier`.

**Comment by mwatson2** [comment]
> If the longest possible match could match one of the above named terminal symbols or one of the quoted terminal symbols from the grammar

It depends on whether 'the grammar' means the specific grammar production or the whole grammar. If the former, it can't match the terminal symbol "void" because that is not one of the options in the `NonAnyType` production.

**Comment by mwatson2** [comment]
Ok, I agree. I'll change it to `any`.

**Comment by bzbarsky** [comment]
It means the whole grammar.
