### ISSUE TITLE
Privacy: Update User Tracking section, including to specifically address Permanent Identifiers

### ISSUE THREAD

**Issue by ddorwin** [w3c/encrypted-media#237]
A lot has changed with respect to Distinctive Identifiers and related issues since the [User Tracking](https://w3c.github.io/encrypted-media/#user-tracking) section was written. We should review and update it to be consistent. Specifically, [Distinctive] Permanent Identifiers should be explicitly addressed as these pose a different set of tracking concerns.

**Comment by paulbrucecotton** [comment]
@ddorwin and @mwatson2 :  What is the status of the two "privacy" V1NonBlocking issues ie [ISSUE-237 ](https://github.com/w3c/encrypted-media/issues/237) and [ISSUE-242](https://github.com/w3c/encrypted-media/issues/242)?

**Comment by ddorwin** [comment]
PR #307.
