### ISSUE TITLE
Problem about MediaKeySession.keyStatuses key order

### ISSUE THREAD

**Issue by jwwang** [w3c/encrypted-media#24]
MediaKeyStatusMap is a read-only maplike which represents an ordered list of key–value pair. (https://heycam.github.io/webidl/#idl-maplike) How is the order defined? Since the key data is populated by the CDM and can't modified by the script, I wonder if the order does really matter.

**Comment by ddorwin** [comment]
I don't think the order should matter (or that applications should assume an order, even in the same user agent). Do you agree?

If so, we can add a statement or non-normative note that the order of all iterators is not defined. Does that work? Perhaps http://heycam.github.io/webidl/#idl-maplike should say something similar.

**Comment by jwwang** [comment]
The order shouldn't matter. However, since MediaKeyStatusMap is a map-like object which define an ordered list, the order must be defined anyway. Otherwise, MediaKeyStatusMap can't be a map-like object. I really want MediaKeyStatusMap to be a sequence of [BufferSource,MediaKeyStatus] to avoid such ambiguities in the spec.

**Comment by ddorwin** [comment]
Issue #39 proposes to avoid maplike. Should we define an order as part of that in case we later want to switch to a map, or should we leave the order undefined? It seems that if we tell authors that the order is undefined, we can always switch to a defined order.

**Comment by ddorwin** [comment]
This is being discussed and will be addressed in issue #39.
