### ISSUE TITLE
Privacy: Add statement that all values exposed or inferable by the application must be per-origin

### ISSUE THREAD

**Issue by ddorwin** [w3c/encrypted-media#242]
We have a clear requirement that (most) [identifiers are per-origin](https://w3c.github.io/encrypted-media/#per-origin-identifiers) and that [persisted data must be clearable](https://w3c.github.io/encrypted-media/#allow-persistent-data-cleared), but I don't believe there is a single place that says most values (Permanent Identifiers being the obvious exception), both persisted and not, must be per-origin and not be accessible or inferable by other origins.

Some references to ~~#per-origin-identifiers~~ (now `#per-origin-per-profile-identifiers`) may not actually be related to identifiers and should instead point to such a requirement.

I believe there are some references in the `MediaKeys` and/or `MediaKeySessions` sections, and the web platform relies on origins, but it is still worth making a clear statement and having a reference target that is not specific to identifiers.

**Comment by paulbrucecotton** [comment]
@ddorwin and @mwatson2 :  What is the status of the two "privacy" V1NonBlocking issues ie [ISSUE-237 ](https://github.com/w3c/encrypted-media/issues/237) and [ISSUE-242](https://github.com/w3c/encrypted-media/issues/242)?

**Comment by jdsmith3000** [comment]
I see your comment about persisted or not, but is this concern not sufficiently addressed by [Information Stored on User Devices](https://w3c.github.io/encrypted-media/#privacy-storedinfo) for V1?

**Comment by ddorwin** [comment]
PR #328.
