### ISSUE TITLE
Privacy: Revisit the steps where consent for distinctiveIdentifier is required

### ISSUE THREAD

**Issue by ddorwin** [w3c/encrypted-media#246]
In step 3 of https://w3c.github.io/encrypted-media/#get-consent-status, there are conditions that cause consent to be _required_. Given changes to the definition of Distinctive Identifier (#117), it's possible that some or all are always true, making this redundant and/or insufficient.

See also @hsivonen's https://github.com/w3c/encrypted-media/issues/110#issuecomment-224845536.

**Comment by ddorwin** [comment]
Note that the current spec language was added before the focus on the relationship to Permanent Identifiers and the related potential for user tracking by a central server (#237).

**Comment by mwatson2** [comment]
The two conditions that trigger a requirement for consent are when the user agent does not support:
* the recommendations of _Allow Identifiers to be Cleared_, and
* the recommendations of _Allow Persistent Data to be Cleared_ in respect of _Distinctive Identifiers_.

(I believe that first bullet should end in "or" not "and", but anyway).

_Allow Identifiers to be Cleared_ no longer contains any recommendations, so this can be removed.

The recommendations of _Allow Persistent Data to be Cleared_ are (in summary) to allow users to clear persistent data on a per-origin basis along with cookies, other site data and browsing history etc.

I don't see anything in the new definition of Distinctive Identifiers which would make this redundant. What we are saying, as before, is that if all these recommendations are followed then the Distinctive Identifier is hardly different from a Cookie (in terms of what the app sees) and that informing the user is sufficient.

**Comment by mwatson2** [comment]
I created PR #268 with the proposal above.

**Comment by steelejoe** [comment]
I think "in respect of" is much less common usage than "with respect to" and will bug some folks. I know it confused me for a bit. Maybe just swap those?

**Comment by mwatson2** [comment]
[s/in respect of/with respect to/](https://github.com/w3c/encrypted-media/pull/268/commits/92238af347093eed6c0b12494e9010ee4ea76e41)
