### ISSUE TITLE
Web IDL links in the EME WD point to the Web IDL ED

### ISSUE THREAD

**Issue by ddorwin** [w3c/encrypted-media#249]
The Web IDL links in the EME spec are supposed to point to:
* Web IDL's ED in GitHub for EME EDs (GitHub)
* Web IDL's CR (TR/ address) for EME WDs and later

This  is controlled by `encrypted-media.js`.

Currently, both point to the GitHub address. For example, see https://www.w3.org/TR/2016/WD-encrypted-media-20160610/. @plehegar FYI.

The first step is to try to reproduce this by changing the `specStatus` locally.

**Comment by jdsmith3000** [comment]
Is this issue to confirm the proper links, or do you know they are broken now?  Are they manually updated?

**Comment by ddorwin** [comment]
The links aren't broken - they work - but they are to an unstable reference even in the WD. The links are generated by the macros in `encrypted-media.js`. That script is supposed to choose the appropriate base URL, but it's apparently always choosing the ED version, which seems unexpected since that is the override. I haven't looked into it more.

**Comment by ddorwin** [comment]
I manually changed the `specStatus` in `encrypted-media-respec.html` to `"WD"` locally and saw the expected results. It appears this only happens in the publishing flow. It is possible that `window.respecConfig.specStatus` is `"ED"` at some point during the auto-publishing flow? @plehegar

**Comment by paulbrucecotton** [comment]
>The Web IDL links in the EME spec are supposed to point to:
> - Web IDL's ED in GitHub for EME EDs (GitHub)
>- Web IDL's CR (TR/ address) for EME WDs and later

@ddorwin and @plehegar : Is this issue impacted by the Web Platform WG's decision to take WebIDL-1 to Proposed Recommendation?
https://lists.w3.org/Archives/Public/public-webapps/2016JulSep/0070.html 

/paulc

**Comment by ddorwin** [comment]
This appears to have been corrected in the CR: https://www.w3.org/TR/2016/CR-encrypted-media-20160705/. WebIDL links in that version correctly point to https://www.w3.org/TR/WebIDL-1/.
