### ISSUE TITLE
A number of minor corrections.

### ISSUE THREAD

**Issue by wgenemorgan** [w3c/encrypted-media#252]
I just completed a review of the June 10 Working Draft, and I ran across some minor typos and instances where the wording was unclear:

1. Introduction:  "This specification enables script to select content protection mechanisms, control license/key exchange, and **implement** custom license management algorithms."

Suggest execute or select or select and execute.

2. Definitions: Key Session:  "only media element(s) associated with **that object**"

It is not clear whether "that object" refers to Key Session or MediaKeys.

3. Definitions: Known Key: "...and any **license release message** is acknowledged."

Add cross reference?

4. Definitions: Permanent Identifiers: "A Distinctive Permanent Identifier is not a Distinctive **Identifiers** because..."

s/Identifiers/Identifier/ ?

5. Section 3.1.1, 3rd paragraph after note: "in one at least one of"

Either "in one of" or "in at least one of".

6. Section 3.1.1 requestMediaKeySystemAccess method, step 7.3.3.2: "Resolve promise with access and abort these steps."

The precise scope of "these steps" is not clear.

7.  Section 5, MediaKeys Interface, description of persistent-license: "A message of type "license-release" containing the record of license destruction will be generated when remove() is called until the record is acknowledged by a response passed to update()."

Difficult to parse.  Maybe fixed by comma after "called".  Also consider replacing "generated when remove() is called" with "generated each time remove() is called".

8. Section 6.2, MediaKeySession Interface methods:

In some of the methods, both **message type** and **message** are nullified, on others only **message** is nullified.

9. Section 7.2, HTMLMediaElement Extensions methods, step 5.1: "If mediaKeys is not null, the CDM instance represented by mediaKeys is already in use by another media element, and the user agent is unable to use it with this element, ..."

Please use explicit AND or OR between the three conditions.

10. Various locations: search for "resource fetch algorithm":

This is the only link to an algorithm where "algorithm" is part of the link text.  Is this deliberate?

11. Section 6.6.4, Session Closed, second note: s/furter/further/

**Comment by mwatson2** [comment]
PR #276 

I did not find a reference for "license release message". I guess we could link to the message type.

Inclusion of "algorithm" in the link for "resource fetch algorithm" is deliberate, as this is what it is called in the HTML5 specification, whereas the algorithms in our specification have names that do not include the word algorithm, but they appear in a "Algorithms" section.

**Comment by jdsmith3000** [comment]
Changes seem clear.  LGTM.

I don't see much value in a general message type reference for "license release message".  It's used in two places currently.
