### ISSUE TITLE
Make MediaKeySystemConfiguration.sessionTypes a sequence<MediaKeySessionType>

### ISSUE THREAD

**Issue by cpearce** [w3c/encrypted-media#260]
`MediaKeySystemConfiguration.sessionTypes` is defined as a `sequence<DOMString>`. But the values are supposed to be the values from the MediaKeySessionType enum. So why can we just make 
`MediaKeySystemConfiguration.sessionTypes` a `sequence<MediaKeySessionType>`?

**Comment by ddorwin** [comment]
[I updated the message above to show the template types.]

See #47 for the reason we changed the sequence to be of DOMStrings.

**Comment by ddorwin** [comment]
I'm going to close this with the explanation above. Feel free to reopen if you disagree.

**Comment by cpearce** [comment]
That makes sense, thanks for pointing out the previous issue explaining this.
