### ISSUE TITLE
Replace "incumbent settings object" with "current settings object"

### ISSUE THREAD

**Issue by ddorwin** [w3c/encrypted-media#270]
https://w3c.github.io/webappsec-secure-contexts/#new has updated the recommended language. See https://readable-email.org/list/public-script-coord/topic/multiple-globals-and-you for details.

**Comment by mwatson2** [comment]
Duplicate of #269 

@ddorwin I hereby pass you the token for deciding which one to close.

**Comment by ddorwin** [comment]
I moved my text to #269.
