### ISSUE TITLE
Update Revision History

### ISSUE THREAD

**Issue by ddorwin** [w3c/encrypted-media#280]
The [Revision History](https://w3c.github.io/encrypted-media/#revision-history) hasn't been updated in almost two years. As we move towards publishing v1, I wonder what the value of the existing history is in a published document.

Note: For comparison and discussion, [Media Source's Revision History](https://w3c.github.io/media-source/#revision-history) appears to include every commit since mid-2012. Do we want that in the final REC or should it be slimmed down?

@plehegar for guidance
@wolenetz FYI for MSE

**Comment by jdsmith3000** [comment]
I support removing this on both EME (where it hasn't been updated) and MSE (where it has).

As an alternative, the Web Audio Spec just pulls in a GitHub change log:  http://www.w3.org/TR/webaudio/changelog.html
