### ISSUE TITLE
“these APIs” is ambiguous

### ISSUE THREAD

**Issue by ddorwin** [w3c/encrypted-media#283]
The spec refers to the APIs defined in the EME specification as these APIs 22 times. While longer, we may want to say “the APIs [defined] in this specification” instead.

As an example, in the following statement from https://w3c.github.io/encrypted-media/#direct-individualization, a section outside any of the objects, it might not be clear which APIs we are referring to. (We’re mostly referring to “message” events and similar.)
>MUST NOT be passed to or through the application via these APIs.

**Comment by ddorwin** [comment]
Unless there are comments or suggestions, I'll plan to replace "these APIs" with "the APIs defined in this specification" tomorrow.

**Comment by mwatson2** [comment]
Sounds good to me.

**Comment by ddorwin** [comment]
PR #291.
