### ISSUE TITLE
'waitingforkey' event has no inverse

### ISSUE THREAD

**Issue by joeyparrish** [w3c/encrypted-media#284]
As far as we've been able to tell, there's no inverse of the `waitingforkey` event to let an application know that the user agent is no longer waiting for a key.

We tried to do this with `keystatuseschange` events, supposing that a usable key status indicates that the browser is no longer waiting.  However, for content without a clear lead, we found two big problems with this.
1. If the CDM just got a new key, but it's either the wrong key or there are still other keys needed, this is not the inverse of `waitingforkey`.  In most cases, though, another `waitingforkey` event fires after the `keystatuseschange` event.  Relying on an additional `waitingforkey` to convey that we are still waiting brings me to the second issue with this strategy...
2. The `waitingforkey` event does not always fire strictly before the `keystatuseschange` event.  In some cases, we have all the keys we need, but the `keystatuseschange` event fires first, followed by a `waitingforkey` that is now obsolete.  I assume there is a race between the decoder thread dispatching `waitingforkey` and the CDM thread dispatching `keystatuseschange`.  At the application level, there's no clear way to tell when this has happened, so it looks as if the wrong keys have been obtained.

Since using `keystatuseschange` as the inverse of `waitingforkey` seems to be dependent on timing, we have concluded that this is not a suitable solution.  We wanted to use `waitingforkey` as a diagnostic measure to tell application integrators when their license servers served the wrong keys, but without a matching event when the pipeline is unblocked, we will have to cut that feature.

Is there an inverse event we can use today?  If not, could a future version of EME include one?

**Comment by cpearce** [comment]
@joeyparrish: Isn't the "canplay" event the opposite of "waitingforkey"? In Firefox, we don't fire "canplay" until we've got keys and we can actually decode and play.

**Comment by paulbrucecotton** [comment]
@ddorwin or @jdsmith3000 : Please mark this issue as VNext.

**Comment by cpearce** [comment]
Note Firefox has implemented waitingforkey in Firefox 51. It should appear from tomorrow's Nightly build onwards.

**Comment by jdsmith3000** [comment]
We don't plan to address this issue in EME V1.

**Comment by joeyparrish** [comment]
It's been 4 years, and I assume implementation have improved significantly.  Though I haven't retested this and the thing we were trying to do with it in Shaka Player has long since been abandoned, I'm going to assume that "canplay" works for this purpose in current user agents, and that no further change is needed in the spec.  If it comes up again, I'll consider it a UA bug if "canplay" doesn't serve this purpose as expected.
