### ISSUE TITLE
Restrict all interfaces to secure contexts

### ISSUE THREAD

**Issue by ddorwin** [w3c/encrypted-media#289]
#271 added `[SecureContext]` to `requestMediaKeySystemAccess()`, which effectively makes use of the APIs and CDM impossible on insecure contexts. However, all the other dictionaries, interfaces, and partial interfaces will still be visible to insecure contexts. This is a bit strange since feature detection using `if (MediaKeys)` would succeed while `if (navigator.requestMediaKeySystemAccess)` would not.

Probably the correct/consistent thing to do would be to add `[SecureContext]` to all IDL blocks, including `partial interface HTMLMediaElement`. This is easy and straightforward.

However, that alone would not prevent the `encrypted` and `waitingforkey` events from being fired even though the `on...` attributes would not be usable. I see three options:
 1. Abort the relevant algorithms when in an insecure context, preventing the events from being fired.
 1. Fire the events but leave the `on...` attributes inaccessible.
 1. Fire the events and allow use of the `on...` attributes but leave everything else inaccessible. (This is accomplished by adding `[SecureContext]` to the `mediaKeys` and `setMediaKeys` members rather than the entire `partial interface`.)

(2) and (3) allow players on insecure contexts to detect but not handle encrypted content, which seems good. (2) seems like unexpected behavior and limits the benefits in the previous sentence. Therefore, I am leaning towards (3).

@mikewest, any comments on the preferred behavior?

**Comment by mikewest** [comment]
I think the behavior you're suggesting is reasonable. It's basically up to each feature to determine which of its aspects require secure contexts, and it seems like the tradeoffs you're noting above support (3) as a reasonable compromise between hiding everything and enabling graceful failure.

**Comment by ddorwin** [comment]
PR #294.

**Comment by smaug----** [comment]
SecureContext is meaningless and isn't valid webidl with enums and dictionaries.

**Comment by ddorwin** [comment]
@smaug----, I'm not sure what the first part of your statement means, but I've opened #403 to address the second part. If you have further concerns, please open a new issue.

**Comment by smaug----** [comment]
There is just one statement, I'd say :)
SecureContext is meaningless with enums and dictionaries.
