### ISSUE TITLE
Allow applications to check MediaKeySessionType support via requestMediaKeySystemAccess()

### ISSUE THREAD

**Issue by ddorwin** [w3c/encrypted-media#29]
Currently, applications can request/require support for persisting state, but this does not guarantee that either of the `persistent-*` `MediaKeySessionType` values are supported. Although applications can check support for specific `MediaKeySessionType` values by calling `createSession()`, which will throw a `DOMException` "If the Key System implementation represented by this object's cdm implementation value does not support sessionType," it would be nice if applications could check before selecting a key system and potentially causing a user prompt.

Consider the following scenario:
1) User wants to pin content for offline playback.
2) User agent prompts the user for permission to use the key system.
3) Application reports that offline playback is not supported.

The problem is worse in the event that the user agent supports another key system (or configuration) does support `persistent-license`.

We don't need to add every capability to `MediaKeySystemConfiguration`, but this seems like an important one since there is no downgrade option.

Assuming we want to address this, we need to decide how to expose this information. A sequence of `sessionTypes` would be easy and extensible. For consistency with the other sequence members of `MediaKeySystemConfiguration`, support for any of the `MediaKeySessionType` values in the sequence (or an empty sequence) would result in success.

If an application needs a specific session type, it can check getConfiguration() on the resulting `MediaKeySystemAccess` object or only request the specific `MediaKeySessionType`.

Step 2 of `createSession()`, which is currently "If the Key System implementation represented by this object's cdm implementation value does not support sessionType, throw a new DOMException whose name is NotSupportedError", should probably be updated to check a property from the resulting `MediaKeySystemAccess`. The most obvious and understandable behavior would be to use the list of `sessionTypes`. The downside is that this would, for example, prevent an application that only checked for `persistent-license` from creating `temporary` sessions as appropriate.

**Comment by ddorwin** [comment]
Regarding the last paragraph above, the other checkable value that is also used as parameter - `initDataTypes` - is not checked against the `MediaKeySystemAccess` object [1]. `audioCapabilities` and `videoCapabilities`, are not checked anywhere either, though these values are mostly outside the scope of EME. It appears that only the `MediaKeysRequirement` members affect the algorithms.

Checking the properties of the `MediaKeySystemAccess` object would be clearer than checking "this object's cdm implementation", but we don't currently enforce this in similar cases.

[1] Step 5 of `generateRequest()` currently says:
>If the Key System implementation represented by this object's cdm implementation value does not support initDataType as an Initialization Data Type, return a promise rejected with a new DOMException whose name is NotSupportedError. String comparison is case-sensitive.

**Comment by mwatson2** [comment]
I think David's proposal is a good one.

**Comment by ddorwin** [comment]
A few notes:
* All session types must be supported for the configuration to be selected. This is required for the next item.
 * Note: Members related to content types, including `initDataTypes `, that are sequences are OR/one-of, but the usage is different. Specifically, "These are all the types I can support" vs. "I need support for these things.")
* `createSession()` only allows `sessionType` values that were specified in the configuration.
* For all sequence members, empty sequences will now fail. The default of the member being "not present" will cause it to be ignored.
* If the `sessionTypes` member is not specified, it as treated as if it was `[ "temporary" ]`. This value is included in the resulting configraiton.
 * I would have preferred to define a default value, but the only valid default value for a Web IDL sequence is `[]`.
* When the `sessionTypes` member is present, `"temporary"` is not implied - it must be specified (along with any other values).
