### ISSUE TITLE
Move the Individualization section out of the Privacy section

### ISSUE THREAD

**Issue by ddorwin** [w3c/encrypted-media#301]
Individualization is currently a subset of the Privacy User Tracking section, but it is more than just a privacy topic. There is a TODO in the source related to this.

There isn't an obvious place for it, but Implementation Requirements (after the Identifiers subsection) is probably better. We can reference the requirements in that section from the User Tracking section.

**Comment by steelejoe** [comment]
I agree, the Implementation Requirements section is a better fit. This could follow the model of "Support Multiple Keys" e.g. "Implementations must support Key Systems which send the _individualization-request_ message type."

**Comment by mwatson2** [comment]
Makes sense.

**Comment by ddorwin** [comment]
PR #306.
