### ISSUE TITLE
Turn off EME by default and activate only with express permission from user

### ISSUE THREAD

**Issue by hhalpin** [w3c/encrypted-media#304]
I think this text would help address the concerns over the EME. It should be added in the Security Section part of the current EME spec: https://www.w3.org/TR/encrypted-media/#security

"A conforming implementation of this specification MUST ensure that this API cannot be used without the user's express permission due to the inherent risks in the activation of a CDM in a user agent. The API MUST be disabled by default, and should only be activated when the user gives express consent and is fully informed on a per-origin basis."

In particular, this is stronger text than is currently included and could replace this text under ""Per-origin user alerts / prompts and permissions"":  "User Agents SHOULD ensure that users are fully informed and/or give explicit consent before a Key System that presents security concerns that are greater than other user agent features (e.g. DOM content) may be accessed by an origin" as this text does mandate off by default, uses MUST, and notes that an EME-enabled Key System *always* presents security concerns that are greater other user agent features (due to DMCA). 

This is explicitly different in scope and effect from : https://github.com/w3c/encrypted-media/issues/288

**Comment by mwatson2** [comment]
There are costs to prompting users, including the fact that if used too often, prompts encourage click-through behavior, rather than the desired 'informed consent' outcome.

This is one reason why the choice to ask for consent - where there is scope for judgement to be applied - is typically left to user agent implementors. UA implementors can gauge how serious the issue is relative to other issues and know what other mitigations they have applied, including in this case offering direct incentives to security researchers to encourage review.

I don't agree that it is _impossible_ for Key Systems to present no greater security concern than other user agent features. In fact this would be a highly desirable outcome which should be encouraged.

**Comment by hhalpin** [comment]
I do not think the choice should be left to UA implementers insofar as it is not the responsibility of the Working Group and the W3C to take into account the needs of users. Particularly in this case, the needs of users conflicts with the short-term interests of the business models of a few companies that also create  user agents, insofar  in making it as any less easy - even if there are reasonable grounds -  for users as possible to stream DRM-protected content may hurt the profit margins of these companies. Thus, in order to err on the user safety given widespread concerns re DRM and the relatively unique anti-circumvention DMCA provisions  (https://en.wikipedia.org/wiki/Digital_Millennium_Copyright_Act#Criticisms), off by default should be a MUST for EME. 

In brief, Key Systems do indeed present a greater security concern that any other part of the UA, as no other part of the UA has legally enforced anti-circumvention provision. This is widely known by the security community and while EME has done as best as possible to ameliorate these concerns, the concerns justifiably remain. So I disagree and the formal objection stands until the required edits are made and tests made in the test-suite.

**Comment by paulbrucecotton** [comment]
This issue will be closed with no action as per [HME WG decision](https://lists.w3.org/Archives/Public/public-html-media/2016Sep/0003.html) and added to the list of current [Formal Objections against EME](https://dev.w3.org/html5/status/formal-objection-status.html).

/paulc
HME WG Chair

**Comment by jdsmith3000** [comment]
Closing per https://github.com/w3c/encrypted-media/issues/288#issuecomment-245045850.

**Comment by hhalpin** [comment]
So, was this was closed despite being within scope. What was the Director's response to this formal objection? Otherwise, it should be re-filed if the Director did not actually have a response that can be communicated back to the person originating the objection and that I can agree or disagree with it. 

Note that this is different than #312 as I am requiring a MUST. I also want the user to have CONTROL, not simply be informed of the use of EME and DRM>  I do not agree with @ddorwin dowin's take on things, namely that user fatigue means that the user should not be informed. This ended up not being the case with WebRTC, a very frequently used API. Furthermore, I disagree with @ddorwin, as "all CDMs pose an increased security risk" There is plenty of evidence that no sandbox is secure, including those put around CDMs. For an evidence, see the recent pwn2own results, and we should expect more soon:

https://venturebeat.com/2016/03/18/pwn2own-2016-chrome-edge-and-safari-hacked-460k-awarded-in-total/

**Comment by ddorwin** [comment]
@hhalpin, a couple corrections:
 1. #312 _is_ about changing SHOULD to MUST in a couple instances. (I don't claim that would address all your concerns.)
 1. The points you attribute to me that you disagree with were not actually my points. They appear to be taken from https://github.com/w3c/encrypted-media/issues/312#issuecomment-245770160, in which I summarized opposition to the proposal in this issue (and explained how such concerns do not apply to the change proposed in #312).

**Comment by hhalpin** [comment]
To be clear, #312 does not address my comments as it does not enforce, via a MUST, user consent to turning on EME/DRM in the first instance of usage, *regardless* of context. #312 has already been sent to "Version Next" of EME. I do not think security and privacy concerns should wait till the next version (which may never come), but should be implemented now.
