### ISSUE TITLE
Early detection of output protection status

### ISSUE THREAD

**Issue by mwatson2** [w3c/encrypted-media#311]
At any given time, Output Protection (HDCP etc.) may be inapplicable (internal displays), not engaged or engaged at various different security levels. The type of video content that may be provided, specifically the resolution, may be dependent on the Output Protection status.

In EME, this may be implemented by providing separate keys for each resolution and a license which specifies the Output Protection requirements for each key. The CDM is responsible for enforcing these license restrictions, including restricting video resolution according to the license conditions.

A problem with the EME API is that the information about Output Protection status, in the form of the status of each key, is not available until after the license is provided.

Unless the CDM supports downscaling, the consequence is one of the following:
- only low resolution video can be downloaded before the license has been provided. The presentation begins at low quality.
- downloading of video data cannot begin before the license has been provided. The presentation takes longer to start because of this.
- high resolution data downloaded before the license has been provided may need to be discarded once the license has been provided and key status determined. The presentation takes longer to start in these cases and data is downloaded unnecessarily.

Since downscaling is not widely supported, this feature requests asks for a mechanism to discover output protection status before the license is provided, without a round trip to the server.

**Comment by mwatson2** [comment]
Without pre-empting discussion of this feature request, I would like to briefly document a few possible solutions (without comment on their merits):

- A new API could be provided which returns the Output Protection status, for example one of { <internal display>, <not engaged>, <hdcp 1.4 engaged>, <hdcp 2.2 engaged>, ... }.
- Output Protection could be considered a form of robustness and values for the `robustness` field in `requestMediaKeySystemAccess` could be defined to represent different Output Protection reuiqrements.
- Output Protection requirements could be specified early in `initData` allowing key status to be exposed at the same time the key request message is generated.

**Comment by joeyparrish** [comment]
It seems to me that discovering output protection status early only helps if you know what the policy is for each resolution.  If you don't know the output protection policy per resolution, you must wait for the license anyway.  Perhaps this is easy for some applications that are in control of the entire stack, but for generic apps or middleware, this is not a likely scenario.

I strongly object to putting output protection requirements in init data.  Output protection requirements are part of license policies, and policies can be changed on the license server at any time.  Putting policy information of any kind into init data means the data the client has may be out of sync.  Once players are bitten by this a time or two, they will quickly start ignoring any such information.

**Comment by mwatson2** [comment]
@joeyparrish In general, whomever is giving you the license knows the policy and could communicate it in application-visible terms (perhaps in the manifest) as well as in opaque DRM-specific terms in the license.

Players should probably support the case where the actual key statuses after the license is obtained don't match what was expected. In this case, downloaded data may have to be discarded and new data downloaded instead, but you are never worse off (in terms of playback delay) than if you did not have the early detection at all.

I didn't understand why your point was specific to the initData solution, though ? If you are concerned about mis-match between the early detection and the final license-driven detection then this concern would apply for any early detection solution, surely ?

**Comment by mwatson2** [comment]
[Btw, I am not wedded to any particular solution, I just wanted to have the ones I was aware of made public in this forum]

**Comment by joeyparrish** [comment]
The two paragraphs in my comment were meant independent of one another.  Sorry for any confusion.

I think early detection is useful to some applications, but not others.

Separate from that, I think putting policy info in init data specifically is not a good practice at all.  We should not encourage it by making it part of this spec.

Application-specific ways of communicating policy info are completely fine with me, including application-specific manifest extensions.

**Comment by mwatson2** [comment]
@joeyparrish Could you explain a bit more why your concern is specific to initData ?

Do you mean that policies should not be included in initData embedded in the media stream ? I certainly agree with that.

In [my post above](https://github.com/w3c/encrypted-media/issues/311#issuecomment-245318736) I was referring to initData provided to the `generateRequest` API, which could have other sources. Sorry if that was not clear (I will amend the post).

**Comment by joeyparrish** [comment]
Even if it's init data from some other source, the problem remains.

Say, for example, the init data comes from a DASH manifest in the form of a `<cenc:pssh>` element.  The init data in the manifest overrides any init data that may be in the stream, and is presumably easier to update.  On the surface, this appears to alleviate any concerns over the data getting out of sync.

But this is not so.  The init data provided to the CDM is used to generate a license request, but the HDCP policy is ultimately controlled by the license response from the server.  As far as I can tell, encoding HDCP policy information into init data in a standard way would mean of the following:

1. The information may not match with the policy on the server, making the HDCP information in the init data invalid **OR**
2. The license servers for all key systems must always comply with the HDCP information in the init data **OR**
3. All key systems must use init data as the source of truth for HDCP policies

In case 1, the system would not be useful and in my opinion should therefore not be part of the standard.  In cases 2 and 3, this would mandate changes to the designs of existing DRM systems, which I'm not sure we want to do here.

Now, alternatively, application-specific ways of communicating HDCP policy information are fine.  It's the application author's responsibility to ensure that policies are in sync, to decide where the authoritative information resides, etc.

If a particular key system is designed in such a way that HDCP policy information resides on the server and is delivered in the license, then as an author I have to keep the manifest in sync with the server's policies.  If I change the server policy, I had better update my manifests, and vice-versa.

If a particular key system is designed in such a way that HDCP policy information is in the init data and is set purely on the client without waiting for the license, then as an author I know there's nothing to synchronize between manifest and license server.  The manifest is the source of truth.

**Comment by mwatson2** [comment]
I would not advocate 2 or 3 for the reason you give.

> If a particular key system is designed in such a way that HDCP policy information resides on the server and is delivered in the license, then as an author I have to keep the manifest in sync with the server's policies. If I change the server policy, I had better update my manifests, and vice-versa.

I don't understand why the above paragraph doesn't apply to the `initData` option, for the case where `initData` is provided in the manifest ?

**Comment by jdsmith3000** [comment]
There is a general need for applications to know whether link protection is supported or not, and the first two options from @Wolenetz seem suitable for accomplishing this.  They both allow an app that wants to match content to device support for link protection to do so.  

The initData option doesn't do this.  It allows the content via the manifest or inband initData to state a requirement for link protection, and doesn't seem to directly inform the app whether it is supported by the device or not.  It doesn't seem desirable to restate policy in initData (as @joeyparrish states), but also it doesn't seem to usefully address the issue documented here.

I believe we should confirm that the issue itself is valid though.  My personal preference is for it to be solved more broadly, implying a new API rather than leveraging some existing API attribute.

**Comment by mwatson2** [comment]
> The initData option doesn't do this. It allows the content via the manifest or inband initData to state a requirement for link protection, and doesn't seem to directly inform the app whether it is supported by the device or not.

I think this is a mis-understanding of the proposal.

All three of the options I suggested allow an application to discover the current output protection status without a server round trip. Once this has been discovered, then the application can combine this information with content-specific output protection requirements (which may have been communicated in some application-specific way) to determine what to download.

The `initData` option _also_ admits a slightly different usage model, which I'll describe below.

The _differences_ between the proposal are that in the case of the first one (new API), we are directly exposing output-protection-specific concepts in the definition of a web API. This may be of concern to some people.

The second and third proposals leave this to be expressed in keysystem-specific terms.

Comparing the second and third proposals, the difference is that the second requires use of `requestMediaKeySystemAccess` every time the discovery is required, which may be problematic since `requestMediaKeySystemAccess` can have UI side-effects in terms.

With `initData` keysystems could support a client-constructible form that provides a key id for each possible OP status and then the keystatuses will immediately indicate the OP status now (and when it changes in future). A session could be created just for this purpose.

Alternatively, the initData for the content indicates the OP requirement for each key and then the keystatuses indicates which streams are supported at any given time.

**Comment by jdsmith3000** [comment]
This method implies that licenses are downloaded for cases with and without output protection though, right?  And then keyStatuses confirm which are usable so that the application can choose which segments to download?  This seems very indirect to me.

**Comment by mwatson2** [comment]
> This method implies that licenses are downloaded for cases with and without output protection though, right? 

No, the idea is that for cases with output protection you can find out the output protection status *before* requesting the license (without a server round trip).

> And then keyStatuses confirm which are usable so that the application can choose which segments to download?

Keystatuses would be used to expose the output protection status in the same way as they are today, except that today the keystatuses is only valid after the license is proposed wheras in the `initData` proposal keys that were unusable due to output protection could be marked as such right away, without a server round trip.

**Comment by jdsmith3000** [comment]
I get it.  So this solution extends MediaKeyStatusMap to work with initData, and conceptually could confirm any policy requirement that could be expressed via initData.  Licenses have not yet been requested, so "usable" keys are usable for subsequent license request, not directly for playback.

**Comment by mwatson2** [comment]
> "usable" keys are usable for subsequent license request, not directly for playback.

I would expect that a key only becomes "usable" after we have the license, but a key may become "restricted" immediately, if this can be determined early based on the policy / output restriction status.

**Comment by mwatson2** [comment]
It has been suggested that this be addressed as part of the proposed new [Media Capabilities API](https://github.com/WICG/media-capabilities). Does anyone have opinions on whether it is best addressed there, or as part of the EME API (in VNext) ?

**Comment by xhwang-chromium** [comment]
The new proposal is at https://github.com/WICG/media-capabilities/blob/master/eme-extension-policy-check.md

This is being actively implemented in Chromium. See Intent to Implement at: https://groups.google.com/a/chromium.org/forum/#!topic/blink-dev/Okto6s417Q8

**Comment by chrisn** [comment]
Historical note: The proposal was migrated here: https://github.com/WICG/hdcp-detection/blob/main/explainer.md

**Comment by joeyparrish** [comment]
I believe this is solved in the editor's draft now
