### ISSUE TITLE
Replace uses of "alerts"

### ISSUE THREAD

**Issue by ddorwin** [w3c/encrypted-media#316]
The spec currently uses "alert" seven times, all related to the "Provide per-origin user alerts / prompts and permissions" sections. Even within those sections, "alert" is not used for the main statement, which uses "ensure that users are fully informed" terminology. We should consistently use the latter, which more specifically addresses the requirement without implying a specific implementation.

Note that #315 may alter the structure of these sections.

**Comment by mwatson2** [comment]
Makes sense.

**Comment by ddorwin** [comment]
PR #323
