### ISSUE TITLE
Broken links in format registry

### ISSUE THREAD

**Issue by osmestad** [w3c/encrypted-media#317]
The links from Stream Format Registry (https://www.w3.org/TR/eme-stream-registry/ and https://www.w3.org/TR/2016/NOTE-eme-stream-registry-20160907/) to the actual stream formats are broken. They currently point to:
https://wwww.w3.org/TR/eme-stream-mp4/
and
https://wwww.w3.org/TR/eme-stream-webm/

I assume the they should be https://www.w3.org/TR/eme-stream-mp4/ and https://www.w3.org/TR/eme-stream-webm/ ? (only 3 w's)

**Comment by paulbrucecotton** [comment]
We are in the process of republishing the EME (and MSE) registries and some links do need to be fixed.  The Editors and W3C Team are in the middle of doing this.  See discussion [here.](https://lists.w3.org/Archives/Public/public-hme-editors/2016Sep/0012.html)

**Comment by ddorwin** [comment]
@plehegar fixed those problems, but the four w's still exist: https://github.com/w3c/encrypted-media/blob/17d9aeccfa6a2b3c94d48d5c85516e428d6aee0b/encrypted-media.js#L586

**Comment by ddorwin** [comment]
The fix is easy, but @plehegar will need to republish and test.

**Comment by ddorwin** [comment]
I fixed the script. @plehegar needs to generate the files again.

**Comment by dret** [comment]
seems like the "when the only tool you have is a hammer" approach is biting back. ;-) i still think that publishing and re-publishing notes that really should be registries has disadvantages on a variety of levels. i'll make a suggestion over at #183.

**Comment by plehegar** [comment]
Sorry for missing that one earlier. All docs have been republished.
