### ISSUE TITLE
Spec should mention that EME is not expected to work outside of MSE

### ISSUE THREAD

**Issue by cpearce** [w3c/encrypted-media#335]
Currently the only browser that supports EME in non-MSE video is Chrome for WebM only. It doesn't seem like there's demand for EME in non-MSE video, so I propose that the spec mentions somewhere that EME is not expected to work outside of MSE video.

**Comment by ddorwin** [comment]
EME is designed to be independent of the source, and it's possible some third source type could emerge in the future, so I don't think the spec should make any normative statements. However, I think it could be helpful to authors and implementers to have an informative non-normative statement.

**Comment by ddorwin** [comment]
There was already a note to this effect in the HTMLMediaElement extensions section. PR #344 makes this more prominent.
