### ISSUE TITLE
Remove is-persistent-session-type-algorithm check from remove() algorithm

### ISSUE THREAD

**Issue by ddorwin** [w3c/encrypted-media#337]
In https://github.com/w3c/encrypted-media/issues/180#issuecomment-222194463, we decided to allow `remove()` to be called for all session types. 4d5498e210e938f1c1d2fd4908bbeab2df7467be implemented handling of `"temporary"` sessions. However, it did not remove the `is-persistent-session-type-algorithm` check, meaning `"temporary"` sessions would still be rejected with a `TypeError`.

Removing this step should result in the desired behavior from the comment above.

**Comment by mwatson2** [comment]
PR #341
