### ISSUE TITLE
Internal waiting for key and encrypted block queue values must be cleared on seek

### ISSUE THREAD

**Issue by ddorwin** [w3c/encrypted-media#347]
The internal _waiting for key_ and _encrypted block queue_ values are initialized when the HTMLMediaElement is created:
>When a HTMLMediaElement is created, its internal _waiting for key_ value shall be initialized to false and its _encrypted block queue val_ue shall be empty.

But they are not cleared in other conditions. Seeking is the most obvious. Are there others?

@cpearce @foolip

**Comment by cpearce** [comment]
We would need to reset those when load() is called as well, in case the video element is reused.

**Comment by ddorwin** [comment]
I'll use the following language copied from https://html.spec.whatwg.org/multipage/embedded-content.html#video:
>When the current playback position changes such that the last frame rendered is no longer the frame corresponding to the current playback position...

followed by the text:
>the user agent shall set the _waiting for key_ value to `false` and make the _encrypted block queue_ value empty.

I'll follow that with a note that this applies to the load and seeking algorithms.

**Comment by ddorwin** [comment]
PR #348.

I ended up using different text since the text above was specific to video and would also trigger on normal playback.
