### ISSUE TITLE
Move gh-pages branch to master

### ISSUE THREAD

**Issue by ddorwin** [w3c/encrypted-media#355]
Early on, we created a `gh-pages` branch and deleted the `master` branch so that we could view the spec on `github.io`. It is possible ([documentation](https://help.github.com/articles/configuring-a-publishing-source-for-github-pages/)) to have `github.io` serve from either `master` or `gh-pages`.

Working on `gh-pages` is a bit strange and inconsistent with other repositories. More importantly, though, as we think about forking into WICG for incubation, it will probably be clearer if there is a `master` branch rather than focusing on what is on `github.io`. Having a `master` branch would also allow WICG or other forks to create a `gh-pages` branch that displays something special on `github.io`.

If we're going to do this, we should probably do it before forking into WICG.

@sideshowbarker, @plehegar: Any thoughts on this? Will the history look the same as it does for gh-pages today?

Note that this has no impact on PR and is completely transparent to the spec and what is served from https://w3c.github.io/encrypted-media/.

**Comment by adrianba** [comment]
Seems reasonable. We only used `gh-pages` because this option didn't exist at the time.

**Comment by plehegar** [comment]
I created master. It's now the default and is protected. GitHub.io now exposes master. Feel free to delete gh-pages or confirm that I can delete it.

**Comment by ddorwin** [comment]
What do you mean it is protected?

I was able to commit to master, so I think we can delete gh-pages.

**Comment by plehegar** [comment]
master is protected ie you cannot overwrite its history.

https://help.github.com/articles/about-protected-branches/
