### ISSUE TITLE
Explicitly state that MediaKeySystemMediaCapability's contentType attribute MUST be a valid MIME type

### ISSUE THREAD

**Issue by ddorwin** [w3c/encrypted-media#36]
MediaKeySystemMediaCapability's contentType is intended to be a valid MIME type, and there are references to some RFCs, but the spec does not appear to explicitly require this.

We should use similar language to HTML5:
* http://www.w3.org/TR/html5/embedded-content-0.html#attr-source-type
* http://www.w3.org/TR/html5/embedded-content-0.html#mime-types

This applies to both the MediaKeySystemMediaCapability members definition and the algorithm(s) that process them.

**Comment by jdsmith3000** [comment]
Added a reference link for "valid MIME type" to previous changes.

**Comment by ddorwin** [comment]
Thanks. A few comments:
 1. The first commit adds "Contents must not be the empty string."
   * This conflicts with the default value of `""`.
   * This limitation is not really related to this dictionary but when passing the `MediaKeySystemMediaCapability` within a `MediaKeySystemConfiguration` to the Get Supported Capabilities for Media Type algorithm.
   * We reference limitations related to the algorithms elsewhere, such as the text paragraph in the `MediaKeySystemMediaCapability` definition, but this one seems particularly problematic giving the default.
   * Perhaps we can reference this limitation in that same paragraph.
   * Alternatively, we could just say that the empty string is invalid for `contentType`. That would always apply to this dictionary.
 2. The RFC6381 reference doesn't seem directly related to the text it follows. I think we can remove it now that the second commit refers to the HTML5 spec, which references that RFC.
 3. For normative completeness we should probably add a normative reference to HTML5 after the "media-types" link.

**Comment by jdsmith3000** [comment]
I made the changes to remove the "must not be empty string" and RFC references.  I need to understand the comments about Get Supported Capabilities for Media Type better.  It already has steps for responding to non-valid MIME types.

**Comment by ddorwin** [comment]
Assigned to myself to respond to Jerry's comments.

**Comment by ddorwin** [comment]
I made some tweaks:
* Modified the text about the empty string, mostly as I described [above](#issuecomment-121415664).
* Added normative reference to HTML5 as mentioned above.
* Restored the  RFC6381 reference. Except for the HTML5 reference (previous item), this text is now identical to the text at https://www.w3.org/TR/html5/embedded-content-0.html#attr-source-type. (I didn't realize this previously.)
* Removed the "Allows the user agent to determine..." text. This actually applies to `MediaKeySystemMediaCapability` and related objects, and it actually "Allows the _application_ to determine..."

I'm not sure whether "media resource" is correct, but we can address that in #150.

I think this issue is now resolved. Feel free to reopen it if you feel otherwise.
