### ISSUE TITLE
Require explicit enabling of EME in nested contexts

### ISSUE THREAD

**Issue by ddorwin** [w3c/encrypted-media#364]
Nested contexts/iframes should only be able to access EME if the embedding app explicitly enables it. The reasons are similar to other features that [will] have such limitations. Specifically, this helps mitigate many security and privacy concerns, especially where the top-level context is not complicit. This includes some of the concerns in #101.

[Feature Policy](https://github.com/wicg/feature-policy/) appears to be the way forward for these purposes.

The default policies would be:
* Enable: `self` for top-level browsing context, and `null` for nested browsing context
* Disable: `null`

The changes to the EME spec itself would likely be similar to those [proposed for Web MIDI](https://github.com/WICG/feature-policy/issues/2). Basically, the promise returned by `requestMediaKeySystemAccess()` would be rejected with `SecurityError` if EME is disabled.

**Comment by ddorwin** [comment]
https://github.com/WICG/feature-policy/issues/40 is tracking this on the Feature Policy side.

**Comment by ddorwin** [comment]
The issue above is resolved and EME is now included in the Feature Policy spec: https://wicg.github.io/feature-policy/#eme-feature.

The name is currently `"eme"`, though I think `"encrypted-media"` would be better. See https://github.com/WICG/feature-policy/issues/40#issuecomment-289529242.

**Comment by ddorwin** [comment]
The correct link is now https://github.com/WICG/feature-policy/blob/gh-pages/features.md#encrypted-media. Also, the name has been changed to `"encrypted-media"`.

**Comment by ddorwin** [comment]
FYI, Blink/Chrome will be [deprecating on-by-default permissions in cross-origin iframes](https://groups.google.com/a/chromium.org/d/topic/blink-dev/mG6vL09JMOQ/discussion) for several features, including EME, in Chrome 61. These features will need to be explicitly allowed in Chrome 63. See https://sites.google.com/a/chromium.org/dev/Home/chromium-security/deprecating-permissions-in-cross-origin-iframes for details.

We'll post a PR for the relevant changes to the EME algorithms. (This will not officially be part of EME v1.0.)

**Comment by ddorwin** [comment]
PR #432

**Comment by raymeskhoury** [comment]
> FYI, Blink/Chrome will be deprecating on-by-default permissions in cross-origin iframes for several features, including EME, in Chrome 61. These features will need to be explicitly allowed in Chrome 63

Just an update: Chrome 64 is now the target for these changes to land.

**Comment by ddorwin** [comment]
To clarify, this change does not affect _permissions_ (consent). The change is that the `requestMediaKeySystemAccess()` call will reject by default in cross-origin iframes. As shown in PR #432, this happens in the first step, well before consent is checked.

**Comment by luwes** [comment]
Sorry to ask here but we ran into a bug related to this ticket with the Vimeo player. 

It started happening for Chrome 83 on Mac and Windows. For a cross-domain iframe embed with MSE and HDCP enabled playback is blocked while there is no external monitor connected.

The video plays for a few seconds and the key status returns `usable` but then after a bit it changes to `output-restricted`. 

Are there any known changes made to make the cross-domain iframe embed with MSE and HDCP more secure?

I did some searching but didn't come up with much.
Our embeds have the required `allow` attribute.

```html
<iframe allow="encrypted-media; autoplay; fullscreen" src="https://..." frameborder="0"></iframe>
```

I tried adding the `*` after the properties like `encrypted-media *;` but it didn't work.

**Comment by joeyparrish** [comment]
@luwes, that sounds like a potential Chrome or Widevine issue.  I would suggest you file on crbug.com and post the link here so interested parties can track it.  @xhwang-chromium, can you confirm if this should be filed on crbug?

**Comment by luwes** [comment]
thanks for the quick reply @joeyparrish, yes it might be a Chrome bug then. Hoping it's not :)

Ok, I will report it on crbug.com.

**Comment by xhwang-chromium** [comment]
luwes: Please file a crbug and assign to xhwang@chromium.org and I'll help you find the owner.

**Comment by luwes** [comment]
thanks @xhwang-chromium posted a bug report here, https://bugs.chromium.org/p/chromium/issues/detail?id=1087475

(not sure how I could assign anyone)
