### ISSUE TITLE
The term "partial configuration" is unnecessary and confusing

### ISSUE THREAD

**Issue by xhwang-chromium** [w3c/encrypted-media#366]
We use the term "accumulated configuration" in 58 places in the spec. 

Especially in 3.1.1.2, step 16.1:

> Let video capabilities be the result of executing the Get Supported Capabilities for Audio/Video Type algorithm on Video, candidate configuration's videoCapabilities member, **accumulated configuration**, and restrictions.

Then in 3.1.1.3 "Get Supported Capabilities for Audio/Video Type", we have:

> Given an audio/video type, MediaKeySystemMediaCapability sequence requested media capabilities, MediaKeySystemConfiguration **partial configuration**, and restrictions, this algorithm returns a sequence of supported MediaKeySystemMediaCapability values for this audio/video type or null as appropriate.

Note that the caller uses the term "accumulated configuration", but the callee uses "partial configuration". Then in step 1, we use "local accumulated configuration" again:

> Let **local accumulated configuration** be a local copy of partial configuration.

Also "partial configuration" appeared in the spec 5 times. In 3.1.1.3 it appeared 3 times. It also showed up in the "Note" of 3.1.1.1 twice, where this term is totally undefined.

It seems to me it's unnecessary and confusing to introduce the new term "partial configuration" at all. Can we just replace it with "accumulated configuration"?

**Comment by mwatson2** [comment]
Outside of the note, it's not a term, it's a variable name. It could be replaced by _foo_ throughout and the spec should still be correct.

I've no objection to changing the variable name, if people think that makes it clearer, though it does open the door to confusion between the _local accumulated configuration_ and _accumulated configuration_.

Within the note, I am not so sure it helps. In the note "partial configuration" refers to a configuration that is not completely specified, so "partial" is a better term the "accumulated" here.
