### ISSUE TITLE
Clarify text regarding how applications remove stored data

### ISSUE THREAD

**Issue by ddorwin** [w3c/encrypted-media#368]
The [Session Storage and Persistence](https://w3c.github.io/encrypted-media/#session-storage) section currently says:
>An application that creates a session using a type for which the Is persistent session type? algorithm returns `true` SHOULD later remove the stored data using `remove()`.

While true, I do not believe the last part is complete. It made sense before we changed the meaning of `remove()` (https://github.com/w3c/encrypted-media/issues/180#issuecomment-222194463). We should probably add something about handling the response and following the process through [until the client removes the data]. Currently, that means sending a message to the server, getting the response, and passing it to `update()`, though we should not (normatively) duplicate that in this section.

We may also want to reword the existing text to avoid implying that `remove()` removes all stored data. It is not until `update()` succeeds that all stored data is removed.

**Comment by mwatson2** [comment]
How about simply saying "... using `remove()` and `update()`." ?

**Comment by jdsmith3000** [comment]
This seems simple enough and worth doing to me.

**Comment by ddorwin** [comment]
While `update()` is currently required in all cases, it seems fragile to add this as normative text here. Also, it's important that the application complete the process, such as if it is interrupted.

Something like the following might work:
>"... later remove the stored data by initiating the removal process by calling `remove()` and ensuring that the process, which may involve message exchange(s), completes."
