### ISSUE TITLE
Unclear text about application managing storage generated by CDM

### ISSUE THREAD

**Issue by xhwang-chromium** [w3c/encrypted-media#369]
In the current spec on [persistent-license](https://w3c.github.io/encrypted-media/#dom-mediakeysessiontype-persistent-license), it says:

> The session must be loadable via its Session ID once update() is called successfully. **The application is responsible for managing any such storage that may be generated by the CDM.** See Session Storage and Persistence.

It's not clear to me what "such storage" generated by the CDM the application is responsible for managing. After some offline discussion (with ddorwin@), this is really about the text appeared at the end of [6.6 Session Storage and Persistence](https://w3c.github.io/encrypted-media/#session-storage):

> An application that creates a session using a persistent-license should later remove the stored data using remove(). The CDM may also remove sessions as appropriate, but applications should not rely on this.

However, it's pretty hard to figure this out from the current text. We should clarify this part to avoid any future confusion.

**Comment by mwatson2** [comment]
The text in 6.6 is clear (if #368 is addressed) so perhaps we should just remove the first phrase mentioned above ?

**Comment by jdsmith3000** [comment]
The wording under persistent-license sessions seems like it's intended to introduce the section 6.6 content.  I don't think it's improved by removing it.  I recommend leave as is.

**Comment by mwatson2** [comment]
Perhaps s/managing any such storage that may be generated/requesting the removal of session data stored/ ?

**Comment by jdsmith3000** [comment]
Works for me.

**Comment by ddorwin** [comment]
"any such storage" is referring to the things in the first paragraph:
>A session for which the license (and potentially other data related to the session) will be persisted. A record of license destruction shall be persisted when the license and key(s) it contains are destroyed.

The sentence containing "any such storage" and the next one seem out of place in the middle of a paragraph describing client implementation requirements. Also, the middle and last paragraph are out of order with respect to lifetime.

We have an incomplete sentence beginning with "Can only." I think we should change this to "Such sessions can only..."

Something like @mwatson2's suggestion seems reasonable. I'll make a PR to address the comments above, then we can see what makes sense to address this.

**Comment by ddorwin** [comment]
See PR #417 for structural changes.

As for addressing the original issue, I suggest something similar to one of the following:

>The application is responsible for ensuring that data persisted for such sessions is removed when the application no longer needs it. See Session Storage and Persistence.

>The application is responsible for removing the session, and thus data persisted for it, when the application no longer needs it. See Session Storage and Persistence.

**Comment by xhwang-chromium** [comment]
Both suggestions made by @ddorwin above lgtm. Thanks!

**Comment by mwatson2** [comment]
Mild preference for the first one, but either is ok with me.

**Comment by ddorwin** [comment]
Regarding the first, I was initially concerned that there is not a way to remove the data rather than the session, but looking again, that is exactly what `remove()` does. Also, the linked Session Storage and Persistence section covers this. Also, it is a simpler sentence. I'll make a PR.

**Comment by ddorwin** [comment]
PR #418.

**Comment by jdsmith3000** [comment]
LGTM.
