### ISSUE TITLE
Resolve ambiguous and/or contradictory explanations of time

### ISSUE THREAD

**Issue by ddorwin** [w3c/encrypted-media#370]
As discussed in https://github.com/w3c/encrypted-media/issues/59#issuecomment-275488967 and subsuquent comments, the definition of [Time](https://w3c.github.io/encrypted-media/#time) is ambiguous and/or contradictory. The same is true of references to time elsewhere in the spec.

Specific changes include:
1. Change all references to the unofficial ES6 draft to the official spec. Specifically, replace https://people.mozilla.org/~jorendorff/es6-draft.html#sec-date-objects with https://tc39.github.io/ecma262/#sec-time-values-and-time-range.
1. Rely on https://tc39.github.io/ecma262/#sec-time-values-and-time-range, providing only clarifying text when necessary. Perhaps, highlight the important parts in a non-normative Note to avoid redundantly and potentially confusingly defining time.
1. Ensure references to "Unix time" are removed.
1. Be explicit that time is represented in milliseconds ("millisecond accuracy" and "instants... it can represent... every millisecond" are not sufficiently explicit).
1. In algorithms, reference the Time definition rather than defining the meaning of the time value in each algorithm. For example, "...let expiration time be the [new] expiration time in milliseconds since 01 January 1970 UTC" is redundant and incomplete.

**Comment by mwatson2** [comment]
This seems like a good idea, especially replacing the references. However there is a fair amount of work here.

**Comment by jdsmith3000** [comment]
How extensive is this change?  It would seem to at least require:

1.	Updating the Time definition.
2.	Removing one reference to UNIX time.
3.	Modifying six requirements that use "millisecond"

If that's most of it, then picking this up seems worthwhile.

**Comment by ddorwin** [comment]
I don't think it is too extensive. At a minimum, updating the Time definition is straightforward. We might move some of the text to a NOTE for reader convenience.

There appear to be only two uses of time in the spec, so though (4) and (5) should be simple. (Most instances of "millicsecond" are in the Time definition.

(1) was partially addressed by https://github.com/w3c/encrypted-media/commit/4e8102ed95e103970e14080a87eb50edc241661a. However, we may want to update the anchor as suggested in (1).
