### ISSUE TITLE
3.1.1 Typo in requestMediaKeySystemAccess method

### ISSUE THREAD

**Issue by mcflyuk** [w3c/encrypted-media#375]
There is a typo in the first paragraph of 3.1.1 Methods requestMediaKeySystemAccess:

> Requests access to the specified Key System. When supportedConfigurations is specified, the configuration specified by at least one of its elements must be supported. The resulting MediaKeySystemAccess will correspond to the first such **elment**.

"elment" should be element.

**Comment by plehegar** [comment]
This has been fixed in the editor's draft.
