### ISSUE TITLE
Formal objection: Archiving and EME

### ISSUE THREAD

**Issue by doctorow** [w3c/encrypted-media#377]
EFF has repeatedly raised the issue of archiving and EME, on-list, in calls and during the earlier covenant process. We reiterate these concerns, first published here (https://www.eff.org/deeplinks/2016/03/interoperability-and-w3c-defending-future-present) as a formal objection:

Around the world, archives and libraries have the statutory right to make long-term copies of copyrighted works, even against the wishes of rightsholders. However, this statutory right is interfered with by the rules prohibiting breaking digital locks. Sometimes, governments grant exemptions for libraries (in the USA, the Copyright Office has granted some exemptions to the DMCA for the purposes of archiving), but these exemptions have serious defects. Most of the US exemptions, for example, expire every three years and must be renewed through a costly and cumbersome process, and only cover the right to use a tool to break the digital lock in order to make archival copies: they do not cover the right to make or share that tool, meaning every library must figure out how to make such a tool from scratch, and not share it.

If the W3C adopts the covenant permitting interoperability, it would help vendors who serve the library and archive sectors to make tools to accomplish the institutions' cultural duty by making a lawful use.

**Comment by plehegar** [comment]
The covenant would only cover at best a small subset of W3C Members. We know that several W3C Members already rejected the idea of the convenant. In addition, plenty of media companies are not part of W3C, so the cover provided by the covenant would be very limited at best. Ideally, it would be best to ensure that governments don't put such barriers in the first place or fix their defects.

**Comment by doctorow** [comment]
As there is no specific covenant under consideration at the W3C, and has
not been for over a year, there is no basis to assert this.

If the W3C believes that 100% participation in a covenant is necessary
for it to be useful, the covenant could be integrated into the
membership agreement.

If the W3C believes the covenant would not be useful without worldwide
participation, it could be integrated into the patent-pool license.

EFF does not suggest this, however. We believe that an incremental
approach, as recommended by the AB, is best: let us first make it a
condition of participation in EME standardization, and if it proves
useful, then let the members discuss a broader application.

But the perfect should not be the enemy of the good. The W3C
participants include some of the largest rightsholders, DRM vendors, and
tech companies in the world. Just as the W3C's patent policy can't bind
bad actors -- patent trolls who take out conflicting low-quality patents
that overlap its members' patents, and who represent the vast majority
of patent aggressors -- but still finds utility in establishing ground
rules for IP nonaggression in standards for the community represented by
its membership, so too would the covenant be useful, even if some bad
actors escaped its reach at the margins.

I find this response frankly puzzling, given that the W3C has strongly
advocated for an entirely voluntary process to benefit security
researchers, and has insisted that this represents an adequate remedy
for security researchers who fear retaliation for revealing defects in
members' implementations of EME.

How is it a waste of time to consider a covenant that binds all who work
on EME, but a good use of time to try to convince a small subset of them
to opt into a covenant?

As you're aware, EFF is working to reform anti-circumvention law, having
brought a suit against the US government to invalidate section 1201 of
the DMCA. However, the idea that we should only rely on legal reform to
the exclusion of all other tactics is incoherent.

If we have it in our power to make a difference now, regardless of the
outcome of these legal battles, why wouldn't we do so?

More importantly: the W3C could have gone to the world's legislatures to
reform software patent rules to make them fit for standardization, but
instead chose to bind its members to nonaggression rules.

I believe (based on discussions with the ex-staffers who promulgated
this policy) that the W3C did so because it did not believe that members
should have to take  a position on the fitness of software patents per
se -- only that they agree that software patents were incompatible with
open standards.

Likewise, there may be members who believe that anti-circumvention
rights such as those under DMCA 1201 are legitimate, but that they have
no place in standardization. Why would the W3C force its members to take
the more extreme position (abolish all anti-circumvention rights)
instead of a more nuanced one (agree only to enforce anti-circumvention
rights over standards when there is some other bona fide claim)?

Cory

**Comment by mwatson2** [comment]
> How is it a waste of time to consider a covenant that binds all who work
on EME, but a good use of time to try to convince a small subset of them
to opt into a covenant?

I think that is easy to answer based on the earlier discussions. The likelihood is that those working on EME would not sign such a covenant. There did not seem much interest in devoting the necessary legal resources to negotiating it. Absent such willingness I'm not even sure what the process would be for W3C to "impose" it and even if it could, the result would be that those companies would just go away. Same result as simply refusing to progress the work further, which would be a lot less effort.

On the other hand, most if not all the relevant companies have shown support for independent security research, celebrating and rewarding the discovery and public disclosure of vulnerabilities (for example, recently at pwn2own). Several people, yourself included, express concern that those companies' approach might not extend to DRM in browsers, though there is no evidence of this and those who already have clear policies do not have carve-outs for DRM. It seems likely that companies would want their policies to be clear, given that such concerns have been expressed. That approach seems far more tractable and does not require expensive multi-lateral legal negotiations.

**Comment by plehegar** [comment]
See https://lists.w3.org/Archives/Public/public-html-media/2017Jul/0000.html
