### ISSUE TITLE
what encrypt algorithm for video does EME support

### ISSUE THREAD

**Issue by dodolzg** [w3c/encrypted-media#38]
Hi, I have read the introduction about EME from this url : http://w3c.github.io/encrypted-media/,
but it doesn't mention the encrypt algorithm for video that EME support.

**Comment by joeyparrish** [comment]
Is it EME which supports a particular algorithm?  Wouldn't that fall on the CDM?  That said, my understanding is that a CDM should follow the Common Encryption (CENC) standard for interoperability.

**Comment by ddorwin** [comment]
The encryption is defined by the media format. For example, the CENC defines encryption algorithms for BMFF files using CENC, and the WebM Encryption spec specifies the algorithm for WebM files.

The formats are registered at https://w3c.github.io/encrypted-media/initdata-format-registry.html.

To be more clear, it might make sense to change the following step
>Use the cdm to decrypt the block using block key.

to something like
>Use the cdm to decrypt the block using block key as appropriate for the media format.

**Comment by dodolzg** [comment]
Thanks!
