### ISSUE TITLE
Formal objection: Public domain videos, Creative Commons, Crown and Parliamentary copyrights

### ISSUE THREAD

**Issue by doctorow** [w3c/encrypted-media#380]
EFF has repeatedly raised the issue of public domain videos, Creative Commons, Crown and Parliamentary copyrights and EME, on-list, in calls and during the earlier covenant process. We reiterate these concerns, first published here (https://www.eff.org/deeplinks/2016/03/interoperability-and-w3c-defending-future-present) as a formal objection:

Many videos are not in copyright. In some cases, the copyright on these videos has expired. In others, the videos are produced by governments that cannot assert copyright in their productions (this is the case for the US government). Other videos are in copyright, but governed by separate rules that allow the public to record and share them -- in Commonwealth countries, government works are bound by Crown Copyright or Parliamentary Copyright, under which the public enjoy automatic rights that are broader than the rules governing works made by individuals and companies.

Then there are works that are licensed under free/open content licenses, such as Creative Commons and the GNU Free Documentation License. More than a billion works have been licensed under Creative Commons alone, and all of those works allow viewers to record and share them, and moreover, many of them prohibit the use of digital locks like EME-CDM systems.

Despite the fact that the public is entitled to make use of these works, the companies that distribute them -- broadcasters, cable operators, webcasters, etc -- often lock them up with digital locks, and will continue to do so under EME.

Even though you have the legal right to record and re-use these videos, EME will prevent you from doing so, and anticircumvention laws will prevent anyone else from making a tool to enable you to bypass EME and exercise your legal rights.

A covenant protecting interoperability will give organizations, individuals, and companies a firm legal footing on which to make such a tool and enable the public to accomplish lawful activities with videos they are entitled to.

**Comment by benbucksch** [comment]
If the video is under Creative Commons, then the broadcaster would normally have to publish a copyright notice with a URL where the original video can be obtained, no? Isn't this preferable over recording a re-coded copy of a TV station?

**Comment by plehegar** [comment]
See https://lists.w3.org/Archives/Public/public-html-media/2017Jul/0000.html
