### ISSUE TITLE
Formal objection: Bandwidth arbitrage and EME

### ISSUE THREAD

**Issue by doctorow** [w3c/encrypted-media#381]
EFF has repeatedly raised the issue of bandwidth arbitrage and EME, on-list, in calls and during the earlier covenant process. We reiterate these concerns, first published here (https://www.eff.org/deeplinks/2016/03/interoperability-and-w3c-defending-future-present) as a formal objection:

In the developing world, use of the Web is strongly limited by the high cost of mobile data. What frees them to participate in the Web is time- or place-shifting their usage. Throughout the global south, we see a widespread usage pattern of downloading large files while in wifi range, for later use. This "bandwidth arbitrage" enables the poorest Internet users to approximate the kind of access to rich media assets that the rest of us take for granted.

A tool to allow for offline storage and playback of EME-locked videos would fall afoul of many countries' equivalents to DMCA 1201 -- the US Trade Representative having made the adoption of these laws a condition of trade with the USA -- but an interoperability covenant would protect local entrepreneurs and developers who produced a tool to enable this use.

**Comment by plehegar** [comment]
See https://lists.w3.org/Archives/Public/public-html-media/2017Jul/0000.html
