### ISSUE TITLE
Formal objection: Not a user agent

### ISSUE THREAD

**Issue by benbucksch** [w3c/encrypted-media#385]
Browsers are technically called "user agent", because they act on behalf of the user.

EME leaves this idea. It is are no longer doing what the user wants, but what the content provider wants. The inherent idea is to restrict what the user can do, on his own machine with his own software. As such, EME is no longer a "user agent", and does not belong into one, but it's a "foreign agent". Compare DMCA.

This is a very fundamental and important change. As soon as the software no longer does what the owner of the computer wants, we're in really difficult territory. Taken further, the user is forbidden to install operating systems unless they are approved by Microsoft or the computer vendor. This is the point where the user lost control over the machine in his own house. But it's only the logical consequence of trying to restrict the user.

You're now talking about making DRM a part not only of some PC-based home entertainment systems, but of the Web. This is much broader than just movie watching. What if NewYorkTimes thinks is needs to protect its video content with EME? Then I can only watch news when I'm on a foreign-controlled computer.

EME is posed against the user, trying to restrict him by force. As such, it does not belong into a "user agent" nor any standard for a user agent.

**Comment by plehegar** [comment]
Section 10 and 11 of the specification go in several details about protecting the user from the underlying CDM implementation. We could certainly ignore the fact that CDMs exist but that won't make them go away and, without a specification, you wouldn't be able to point out the flaws in the implementation approach. Btw, nothing prevents the NewYorkTimes to use the DRM system in the flash plugin today btw.

**Comment by plehegar** [comment]
See https://lists.w3.org/Archives/Public/public-html-media/2017Jul/0000.html
