### ISSUE TITLE
Formal Objection: EME should be 'off by default' 

### ISSUE THREAD

**Issue by hhalpin** [w3c/encrypted-media#386]
As my previous formal objection and clear suggestion for a spec improvement was ignored (and closed) without my express agreement (https://github.com/w3c/encrypted-media/issues/304), I'd like to re-open the Formal Objection.

Again, *normative* text that require user consent would help address the security and privacy concerns over the EME. It should be added in the Security Section part of the current EME spec: https://www.w3.org/TR/encrypted-media/#security

"A conforming implementation of this specification MUST ensure that this API cannot be used without the user's express permission due to the inherent risks in the activation of a CDM in a user agent. The API MUST be disabled by default, and should only be activated when the user gives express consent and is fully informed on a per-origin basis.

In particular, this is stronger text than is currently included in the specificaton, as this text does mandate off by default (uses MUST) and notes that an EME-enabled Key System always presents security concerns that are greater other user agent features (due to DMCA).

Indeed, I am stating that a user MUST be informed at least once and explicitly agree *before* EME is activated for any use, and, if not already pre-installed in the OS, the black box of CDM is sent and activated on their device.

I do not agree with the argument that user fatigue means that the user should not be informed. This ended up not being the case with WebRTC, a very frequently used API. Compared to WebRTC, I am only asking a user MUST give explicit consent at least once.

Worse, it appears since my original objection that Chrome has made some moves to making EME/DRM on by default and mandatory since my initial objection (http://boingboing.net/2017/01/30/google-quietly-makes-optiona.html), and difficult if not impossible to turn off. This is frankly unacceptable from a security and privacy standpoint, as well as from the viewpoint of user control and fundamental rights. 

The arguments from W3C PR and the HME WG that a 'sandbox' is somehow a magical solution to user concerns over security and privacy with DRM is equally incorrect. Browsers, including in particular sandboxes, routinely have vulnerabilities (https://venturebeat.com/2016/03/18/pwn2own-2016-chrome-edge-and-safari-hacked-460k-awarded-in-total/). There is plenty of evidence that no sandbox is secure, including those put around CDMs. For an evidence, see the recent pwn2own results, and we should expect more hacks soon particularly on the kinds of DRM enabled by EME.

This is explicitly different in scope and effect from : #288 and #332, as the latter does not acknowledge that there are always security concerns with DRM/EME and therefore is far too vague by not requiring implementers to give users control. 

I look forward to an actual response from the HME Working Group. If a response is not given, I believe there is clear violation of W3C process in ignoring of a rather reasonable demand to protect users. The supposed loss of user engagement from a single 'enabling' click hurts only the profit margins of a few  copyright holders, while DRM/EME poses a security threat to all users. It should not be silently installed and then made difficult, if not impossible, to turn off.

**Comment by taoeffect** [comment]
What's the proper way to express support? Clicking the thumbs up button?

**Comment by mwatson2** [comment]
> As my previous formal objection and clear suggestion for a spec improvement was ignored (and closed) without my express agreement (#304), I'd like to re-open the Formal Objection.

@hhalpin Just for the record, on the facts:
(1) Your issue was not ignored. It was discussed in issue #304 and IIRC on the mailing list. 
(2) Your Formal Objection was not "closed". The _WG issue_ was closed, indicating that the WG did not agree with the proposal. The FO is to be dealt with by the Director, not the WG.

Also, Chrome support for disabling protected content is back.

> I look forward to an actual response from the HME Working Group. If a response is not given, I believe there is clear violation of W3C process in ignoring of a rather reasonable demand to protect users.

What is wrong with the response you got, except that it expresses disagreement ?

It's not a process violation to disagree with a proposal. Noone gets to make "demands", reasonable or not, in a standardization process. You can make proposals and people can agree or not based on the merits as they see them.

**Comment by taoeffect** [comment]
> What is wrong with the response you got, except that it expresses disagreement ?

Could you quote or link to the response he got?

**Comment by taoeffect** [comment]
It this it? https://lists.w3.org/Archives/Public/public-html-media/2016Sep/0003.html

If so, I don't understand the response:

> Since these formal objections:
>
> a)      cannot be satisfied without making "substantive changes" [1] to the EME specification or halting work on the specification entirely, and/or
> 
> b)     are identical to previous formal objections that the Director has chosen not to sustain, and/or
> 
> c)      there is no consensus within the HME WG for the required changes especially this late in the EME specification development,
in my role as HME WG Chair I am ruling that these issues should be closed with no action for EME V1.

Does the W3C operate in any way similar to the IETF?

If so, what is written above is not a valid objection. It amounts to, "Our response is we're going to close the issue."

There is no actual reason given there.

Having to make "substantive changes" is not an objection. That is part of the process of what it means to be a standards body when there are objections that are unaddressed.

**Comment by taoeffect** [comment]
Also, one other thing that's not clear to me, @hhalpin mentioned something about "the black box of CDM"?

What does he mean by "black box"?

Isn't W3C an open standards group? How is a "black box" remotely an open standard?

**Comment by taoeffect** [comment]
Also, just a quick glance at issue #305 makes it clear that this "working group" (is that the right term?) does not have consensus around the issue.

My understanding of IETF, at least, is that "rough consensus" is required before a standard can proceed forward.

If this is a solo-Microsoft endeavor, you can of course implement this feature in Microsoft Internet Explorer without needing to wait for consensus.

**Comment by mwatson2** [comment]
> Could you quote or link to the response he got?

[Here](https://github.com/w3c/encrypted-media/issues/304#issuecomment-240173309) and the thread starting [here](https://lists.w3.org/Archives/Public/public-html-media/2016Aug/0001.html). There are 42 messages in that thread, so clearly the proposal was not "ignored".

As you note, some form of consensus is required to adopt a proposal and clearly Harry's proposal clearly did not have consensus in the WG. The process is then for his Formal Objection to be considered by the Director. Consideration in the WG is complete (unless the Director sends it back or someone has some new information), so the GtHub issue was closed.

> Isn't W3C an open standards group? How is a "black box" remotely an open standard? It sounds like the opposite?

Indeed. Noone has made a proposal to standardize the DRM systems themselves and as far as I understand there is no way to do this that would meet W3C criteria (e.g. for openness, royalty-free). So this is not what we did.

The details of the DRM component are not standardized by W3C. EME does place constraints on the DRM component, standardizes an interaction model and some required features, but this is as far as we could get.

**Comment by mwatson2** [comment]
> If this is a solo-Microsoft endeavor, you can of course implement this "feature" in Microsoft Internet Explorer without needing to wait for consensus.

EME (in some form) is already supported in at least Internet Explorer, Edge, Firefox, Chrome and Safari.

**Comment by hhalpin** [comment]
Just to be clear @mwatson2, the Working Group response seems to be, to sum up, the browser vendors should be trusted more than the user. That is obviously incorrect for every instance, particularly controversial cases. So, I disagree.

For example, with WebRTC, we keep audio/video *off by default* without user permissions. Can you please explain how WebRTC audio/video is more dangerous than opaque DRM code? After all, both are sandboxed, no? 

In terms of process, the Working Group opened an issue but I am not satisfied with the response. Therefore, I'd like to hear from the Director and @plehegar under what grounds the Director closed this Formal Objection. I do believe I have the right to demand this, and otherwise, my formal objection is being ignored - not by the Working Group, where we have simply stark disagreement - but by the W3C in general and the Director in particular. 

I'd also like to know if the Director was actually Tim or someone like @swickr, who normally acts as "Acting Director" for Proposed Recommendation Transitions, as often it's quite well-known Tim Berners-Lee is too busy.

**Comment by mwatson2** [comment]
> Just to be clear @mwatson2, the Working Group response seems to be, to sum up, the browser vendors should be trusted more than the user.

No, the browser vendors are better placed than this group to design the permissions systems in their products. Very different.

**Comment by plehegar** [comment]
The responses to the formal objections were included in
 https://lists.w3.org/Archives/Public/public-html-media/2017Mar/0016.html

**Comment by burdges** [comment]
EME is going to be a _major_ security hole.  It needs to be off by default.  And activating it needs big scary warnings.

**Comment by Atavic** [comment]
>What does he mean by "black box"?

A device you can't open. As CDM can be activated on various channels (operating system, firmware, hardware), most of them closed to the customer's inspection.

**Comment by plehegar** [comment]
See https://lists.w3.org/Archives/Public/public-html-media/2017Jul/0000.html
