### ISSUE TITLE
JNC objection to EME

### ISSUE THREAD

**Issue by bollow** [w3c/encrypted-media#387]
In response to the invitiation currently publichsed on https://www.w3.org/TR/encrypted-media/ that “interested parties are invited to review the document and send comments… through 13 April 2017”, the Just Net Coalition hereby submits as a comment our open letter http://justnetcoalition.org/2017/W3C_EME_objection.pdf which expresses our strong objection to EME.

[W3C_EME_objection.pdf](https://github.com/w3c/encrypted-media/files/915694/W3C_EME_objection.pdf)

**Comment by plehegar** [comment]
See https://lists.w3.org/Archives/Public/public-html-media/2017Jul/0000.html
