### ISSUE TITLE
Formal objection: EME specification cannot proceed further without a complementary CDM specification

### ISSUE THREAD

**Issue by gvlx** [w3c/encrypted-media#388]
As already stated in Formal Objections #379, #378 and issues #20944, #156, #166, the EME specification requires that "To implement an EME-capable browser, you must have a "Content Decryption Module."" (#378).

However the W3C has not made any (public) effort to create a working group to define an open and clear specification of the "Content Decryption Module", which would enable the free development of multiple interoperable implementations.

As strange as this may seem, the closest analogy would be the publication of the XSLT specification without the required and complementary XPATH specification.

In fact, time and time again, the chair of this WG @paulbrucecotton has reiterated "The HTML WG (predecessor of the HTML Media Extensions WG) was told that specifying characteristics of a CDM (ie generic license request/response protocol) was out of scope of the WG's media charter scope." ( #166 )

So I propose the EME specification should be not allowed to proceed further until:

1. a new WG is created specifically to address the CDM specification;
1. this new WG releases a proposal for a CDM specification according to the rules of W3C;
1. the EME and CDM specifications are verifiably interoperable;
1. the EME and CDM specifications are released simultaneously.

**Comment by ajyand** [comment]
CDM is supposed to be executed on client system and still there is no specification for it. It sounds like a joke. I wonder why this hurry to release EME without CDM at the risk of opening doors in the industry to pick up the practice of running arbitrary code on client machines under the hood of W3C.

**Comment by plehegar** [comment]
See https://lists.w3.org/Archives/Public/public-html-media/2017Jul/0000.html
