### ISSUE TITLE
replace "Distinctive Identifier" with "persistent Distinctive Identifier" where "use distinctive identifier" is false

### ISSUE THREAD

**Issue by steelejoe** [w3c/encrypted-media#40]
There are several cases where the use of "Distinctive Identifier" needs to be qualified. For example in section 6.6.1 -- Queue a "message" Event. It says in this case that "message must not contain a Distinctive Identifier, even if encrypted". By the current definition any device-unique key, even an ephemeral key generated just for the purpose of this request, is considered a "Distinctive Identifier" so this restriction does not seem appropriate (or feasible to implement).

I believe this change only kicks in when this flag is discussed, but it is worth reviewing all the uses to make sure.

**Comment by ddorwin** [comment]
I think https://w3c.github.io/encrypted-media/#distinctive-identifier does a good job of defining Distinctive Identifier, including things that are not.

>...even an ephemeral key generated just for the purpose of this request, is considered a "Distinctive Identifier"

"Examples of things that are not distinctive identifiers" includes "A nonce that is unique but used in only one session." Would that example not cover an ephemeral key for a single request?

**Comment by hsivonen** [comment]
As the example that David pointed out shows, the definition of Distinctive Identifier is not meant to cover ephemeral values even if they are unique.

The main problem is when something stops being ephemeral. Clearly, something that's valid for one request/response pair of messages is ephemeral. I think it's OK to even consider DRM session-scoped values ephemeral (and, therefore, not Distinctive Identifiers) when DRM session can't outlive a browser session.

For the topic of persistent DRM sessions that outlive browser sessions, see the last comments at https://www.w3.org/Bugs/Public/show_bug.cgi?id=27268

**Comment by steelejoe** [comment]
You make a good point. However I would at least like this spelled out more
clearly in the Distinctive Identifier definition then to include keys. For
example "A nonce or ephemeral key that is unique but only used in one
session". That would be a much smaller change.

**Comment by ddorwin** [comment]
More concisely, I believe @steelejoe's proposal is to add the text " or ephemeral key" to the "nonce" example.

@hsivonen: Any concerns?

**Comment by hsivonen** [comment]
> More concisely, I believe @steelejoe's proposal is to add the text " or ephemeral key" to the "nonce" example.
>
> @hsivonen: Any concerns?

Works for me. Sorry about the delay.
