### ISSUE TITLE
Clarify first sentence of the CDM Attacks and Vulnerabilities section

### ISSUE THREAD

**Issue by ddorwin** [w3c/encrypted-media#405]
A concern about the first sentence of the [CDM Attacks and Vulnerabilities](https://w3c.github.io/encrypted-media/#cdm-security) section was raised in https://github.com/w3c/encrypted-media/issues/383#issuecomment-290893383. We should address that independent of the outcome of that issue. The sentence currently says:
>User Agents are responsible for providing users with a secure way to browse the web, including any functionality, such as CDMs, from third parties.

In https://github.com/w3c/encrypted-media/issues/383#issuecomment-293104384, I proposed the following replacement:
>User Agents are responsible for providing users with a secure way to browse the web. This responsibility applies to any functionality used by User Agents, including functionalities from third parties.

Other suggestions welcome. The reference to "CDMs" is dropped to make the sentence easier to read; this is probably implied by the section, but it would be nice to find a way to include.

**Comment by mwatson2** [comment]
@ddorwin I think your proposal is a good one.

**Comment by dwsinger** [comment]
fine by me.

**Comment by jdsmith3000** [comment]
LGTM as well.
