### ISSUE TITLE
Definition  of CDM and security/privacy

### ISSUE THREAD

**Issue by plehegar** [w3c/encrypted-media#407]
Section contains "The CDM MUST NOT make direct out-of band network requests.". However, that part is highly relevant when reading security and privacy sections. Should this part of the CDM definition moved closer to those sections?

**Comment by jdsmith3000** [comment]
This refers to the following text:

**Comment by jdsmith3000** [comment]
I'm working on the PR for issue #408.  To me, it makes sense to append this requirement directly below or as part of the "CDM Constraints" section I'm inserting as Section 8.1.  I can pick this up in that PR, if others agree.

**Comment by jdsmith3000** [comment]
I'm proceeding with a combined pull request for issue-407 and issue-408.
