### ISSUE TITLE
Overview of CDM contraints

### ISSUE THREAD

**Issue by jdsmith3000** [w3c/encrypted-media#408]
The spec defines specific constraints on networking and storage access by CDMs, but doesn't currently have a clear overview of the constraints or the implementation options that might be used to meet them.  A summary section could make the overview clearer and help connect the detailed requirements elsewhere in the spec.  It would be good to add this summary early in **Section 8 Implementation Requirements**.

**Comment by jdsmith3000** [comment]
Resolution of this issue will be held until [Issue 407](https://github.com/w3c/encrypted-media/issues/407) and [Pull Request 394](https://github.com/w3c/encrypted-media/pull/394) have been resolved.

**Comment by jdsmith3000** [comment]
Draft language for the constraints overview is:

**Comment by mwatson2** [comment]
Typo, 4th bullet: s/media features/media using the features/

**Comment by jdsmith3000** [comment]
Resolved by PR #411.
