### ISSUE TITLE
ReSpec has 17 warnings and is omitting some text

### ISSUE THREAD

**Issue by ddorwin** [w3c/encrypted-media#416]
16 of the warnings are of the form:
```No <dfn> for Navigator. Please define it and link to spec that declares it. See https://github.com/w3c/respec/wiki/data--cite```

The other is:
```[WebIDL] is referenced in 3 ways: ('WebIDL', 'WEBIDL', 'WEBIDL-LS'). This causes duplicate entries in the reference section.```

Potentially related, some object members are omitted from the generated document.

For example, in https://w3c.github.io/encrypted-media/encrypted-media-respec.html#example-source-and-key-known
```if (!video.)```
should be
```if (!video.mediaKeys) {```

**Comment by plehegar** [comment]
I'm proposing a workaround in #430. I believe some of the issues would be better by switching to the new WebIDL handling but that doesn't seem appropriate for V1. For future versions, we should start by switching to the new WebIDL handling.
