### ISSUE TITLE
Provide a definition for expiration time

### ISSUE THREAD

**Issue by ddorwin** [w3c/encrypted-media#425]
The term "expiration time" is used multiple times in the algorithms (e.g., "If _cdm_ has changed the expiration time of _session_...") yet there is no definition for it.

The definition of the [`expiration`](https://w3c.github.io/encrypted-media/encrypted-media-respec.html#dom-mediakeysession-expiration) attribute says:
>The time after which the key(s) in the session will no longer be usable for decryption, or NaN if no such time exists or if the license explicitly never expires, as determined by the CDM.

While this provides a definition, the relationship to the instances in the algorithm is indirect, especially since those algorithms do not directly modify `expiration`.

We should define "Expiration Time" in the Definitions section and move the first part of the sentence there. We would then have:
>**Expiration Time**
The time after which key(s) will no longer be usable for decryption.

>`expiration`
"The **expiration time** for key(s) in the session, or NaN if no such time exists or if the license explicitly never expires, as determined by the CDM.

>If _cdm_ has changed the **expiration time** of _session_...

**Comment by jdsmith3000** [comment]
This seems like a good idea, but perhaps is more than necessary.  I believe execution time is commonly understood, and our goal has been to tighten up and use a better definition of time.  There are some loose ends still there, but it would only take some format cleanup, removing the section from the time reference, and purging the last stray millisecond reference from the spec.

**Comment by ddorwin** [comment]
I created PR #426 for discussion. One advantage of this is that it addresses the "expressed as **time**" issue without new text in the algorithms.
