### ISSUE TITLE
I can't watch videos in YouTube

### ISSUE THREAD

**Issue by kitchen5203** [w3c/encrypted-media#434]
If I understood computers better then I wouldn't need help. My whole reason for coming to you is for assistance. Please , if I can use any other, faster browser for my MacBook than Safari 10.11, then help me. I have downloaded two chrome capable browsers, but neither seem to work. Even the Google Chrome  has no video. They ask for HTML 5, and I thought I had that.

**Comment by joeyparrish** [comment]
I think this might be the wrong place for YouTube support.

Here's a link to general YouTube support: https://support.google.com/youtube/?hl=en#topic=7505892
Here's a link specifically for trouble playing video: https://support.google.com/youtube/topic/3014746?hl=en&ref_topic=7505892

Here's a page on YouTube's site that tells you what technologies your browser supports, including HTML5 video: https://www.youtube.com/html5

At the bottom of that last page, you'll see links to download browsers which are supported by YouTube.

Good luck, and I hope this helps!

**Comment by plehegar** [comment]
closing since this is indeed the wrong place to ask for YouTube support.
