### ISSUE TITLE
Idea: Add opaque "label" DOMString member to MediaKeySystemConfiguration

### ISSUE THREAD

**Issue by ddorwin** [w3c/encrypted-media#44]
It is possible that applications will pass long sequences of `MediaKeySystemConfiguration`s to `requestMediaKeySystemAccess()`. The resulting configuration is accessible via `MediaKeySystemAccess.getConfiguration()`, but it may not be easy to determine exactly which configuration was selected. This is especially true when debugging, but it could also be useful in production scenarios. Since the resulting configuration is not the same object that was in the sequence passed to `requestMediaKeySystemAccess()`, object equality is not possible. Also, custom properties are lost.

Because this use case cannot be solved with custom properties, we should consider adding an identifier that user agents will preserve in the resulting configuration object. It would have no impact on the behavior of the algorithm, including configuration selection. This should have very low algorithmic and implementation overhead - lower than any other value currently in the dictionary. I propose the following for discussion:

```javascript
dictionary MediaKeySystemConfiguration {
  ...
  DOMString label;
};
```

**Comment by joeyparrish** [comment]
I would be in favor of this.  In Shaka Player, we have to match the results of getConfiguration() back to our various usable streams, and currently, we do this using keySystem and contentType.  A custom label would be significantly less error-prone, in my opinion, and simplify our code a lot.
