### ISSUE TITLE
Add "usable-in-future" to MediaKeyStatus

### ISSUE THREAD

**Issue by xhwang-chromium** [w3c/encrypted-media#451]
There are cases where we could have a license containing a key whose start time is in the future, e.g. to support key rotation. In the current spec, there's no corresponding MediaKeyStatus for this case. It's not "usable", so the closest one is "expired", which looks really odd.

Therefore, I am proposing that we add a new MediaKeyStatus "usable-in-future" to solve this issue.

For the reference, Android MediaDrm also added [STATUS_USABLE_IN_FUTURE ](https://developer.android.com/reference/android/media/MediaDrm.KeyStatus.html#STATUS_USABLE_IN_FUTURE) in Android Q.

**Comment by gregwfreedman** [comment]
this also sounds good to me.

**Comment by xhwang-chromium** [comment]
What's the next step for this? Shall we discuss about it in the Media WG meeting? Or shall I go ahead to send a pull request for the spec?

**Comment by joeyparrish** [comment]
I was out last week, but now that I'm back, I see this is on the Media WG agenda.  So let's discuss in the WG, and if there are no objections or further feedback from the group, I would be happy to review a PR from you.

**Comment by joeyparrish** [comment]
No objections raised in the WG.
