### ISSUE TITLE
Needs clarification on "Usable For Decryption" and "usable" key status

### ISSUE THREAD

**Issue by xhwang-chromium** [w3c/encrypted-media#460]
Currently, a key is _usable_ if

> The CDM is certain the key is currently _usable for decryption_.
> Keys that may not currently be _usable for decryption_ must not have this status.

Then _usable for decryption_ is defined as

> A key is considered usable for decryption if the CDM is certain the key is currently usable to decrypt one or more blocks of media data.

The language used here is a bit ambiguous. Does it mean if the CDM is certain the key can be used to decrypt **any** media block, then the key status should be _usable_?

If that's true, then the reverse of that is: if the key status is not _usable_, then the CDM should not be able to decrypt any media block. This seems to contradict with some other key statuses, e.g. 

> **_output-restricted_**: Media data **decrypted with this key** may be blocked from presentation, if necessary according to the output restrictions.

It seems that "usable for decryption" doesn't care whether the decoded media can be presented. Then in the case when a key can be used for decryption, but the decrypted media is blocked from presentation, it's unclear whether the key status should be _usable_ or _output-restricted_.

**Comment by joeyparrish** [comment]
It seems reasonable to assume that output-restricted supercedes usable.
