### ISSUE TITLE
Clarify the size of a key ID

### ISSUE THREAD

**Issue by vladimir-kazakov** [w3c/encrypted-media#464]
Currently, EME says that it's just a sequence of octets, which, in my opinion, implies that it's "at least 1 byte."

Usually, content protection is used together with CENC, where the key ID is exactly 16 bytes. Okay, EME is not CENC, so they don't have to be equal, but in the issue #34, there is [a comment](https://github.com/w3c/encrypted-media/issues/34#issuecomment-145944015) that says:

> The values in the commit above appear to be less than 128 bits. Also, they fail in Chrome.

This shows that Chrome expects key IDs to be at least 16 bytes. Sure, maybe this expectation is wrong, but then, what exactly must be expected?

EME also has [an example](https://www.w3.org/TR/encrypted-media/#clear-key-request-format-example), where multiple key IDs are exactly 16 bytes:

```
{
  "kids":
    [
     "LwVHf8JLtPrv2GUXFW2v_A",
     "0DdtU9od-Bh5L3xbv0Xf_A"
    ],
  "type":"temporary"
}
```

Does it mean that a key ID is exactly 16 bytes long?

To avoid any doubts and confusions, EME must explicitly mention the size of a key ID, and if it's variable, then the exact range must be specified, as well as the recommended (interoperable) size.

**Comment by mounirlamouri** [comment]
There is variation on what different key systems will accept wrt length. This may need an editorial note.

**Comment by joeyparrish** [comment]
Key ID size is specified by the encryption scheme and/or DRM vendor.
