### ISSUE TITLE
API to find existing sessions

### ISSUE THREAD

**Issue by mounirlamouri** [w3c/encrypted-media#467]
This issue is coming from discussions at TPAC 2019 during the Media WG F2F ([minutes](https://www.w3.org/2019/09/18-mediawg-minutes.html#item06))

The resolution was: _Expose an API to expose key ID information from initialization data in order to find existing sessions_

CC @joeyparrish

**Comment by chrisn** [comment]
TPAC 2022: Joey: This our preferred approach, to return key ids instead of sessions.

Feedback welcome from @aboba and @jernoble.

**Comment by joeyparrish** [comment]
We have decided to drop this feature for lack of interest and lack of consensus on the API.
