### ISSUE TITLE
Clarify if a persitent-usage-record message is needed for the load algorithm

### ISSUE THREAD

**Issue by alex-chromium** [w3c/encrypted-media#469]
In section 5 (https://w3c.github.io/encrypted-media/#idl-def-MediaKeySessionType.persistent-usage-record) for persistent-usage-record it says 
`A message of type "license-release" containing the record of key usage will be generated each time remove() is called` with no mention of the `load()` method.

Further down, in section 9.1.2 (https://w3c.github.io/encrypted-media/#clear-key-behavior), the specs mentions a message containing the record of key usage as part of the `load()` algorithm. 
`For sessions of type "persistent-usage-record", in the remove() and load() algorithms, the message reflecting the object's record of key usage is a JSON object encoded in UTF-8 as described in License Release Format.`

This feel like a spec bug, should the reference to `load()` be remove from the spec in section 9.1.2?

**Comment by xhwang-chromium** [comment]
I think we should only generate the "license-release" message in remove() in all cases for simplicity and consistency. Thoughts?

**Comment by joeyparrish** [comment]
Yes, the `load()` method does not generate such a message, so the section on Clear Key behavior of `"persistent-usage-record"` is in error.  I think we should just drop mention of `load()` from that line.

**Comment by xhwang-chromium** [comment]
Thanks! I'll upload a pull request.
