### ISSUE TITLE
MediaKeySystemConfiguration.sessionTypes should be sequence<DOMString> for forwards compatibility.

### ISSUE THREAD

**Issue by ddorwin** [w3c/encrypted-media#47]
`MediaKeySystemConfiguration.sessionTypes` is currently of type `sequence<MediaKeySessionType>`. Because JS dictionaries don't actually have a specific Web IDL type, the dictionary member types are not checked until passed to a Web IDL object that expects a specific type. Thus, enum values in the `sessionTypes` sequence will not be checked until `requestMediaKeySystemAccess()` is called.

`requestMediaKeySystemAccess()` takes a sequence of `MediaKeySystemConfiguration` values and **only one must be supported** for success. However, an unsupported value in the `sessionTypes` member of _any_ configuration would cause an exception, preventing a supported configuration in the sequence from succeeding. Thus, an application would not be able to use a new `MediaKeySessionType` value with the expectation that older implementations would ignore the configuration and try subsequent configurations.

To allow values to be added to `MediaKeySessionType` in the future, we should change the `sessionTypes` member to be of type `sequence<DOMString>`. This will allow the implementations to reject individual configurations with unrecognized session types.

**Example**

The first line does not throw, so the application cannot detect whether the enum is supported:
>`configurations[0].sessionTypes = [ "temporary", "future-type" ];`
>`configurations[1].sessionTypes = [ "temporary" ];`

This line will result in a type error rather than processing the configurations and ignoring the first one.
>`navigator.requestMediaKeySystemAccess("org.w3.clearkey", configurations).`

**Comment by ddorwin** [comment]
@bzbarsky: Is there a better way to handle this than using DOMString? Are there any special consideration when comparing DOMStrings to enum values in the prose?

**Comment by bzbarsky** [comment]
> Is there a better way to handle this than using DOMString? 

Not right now, no.  If https://www.w3.org/Bugs/Public/show_bug.cgi?id=19936 happens at some point, then maybe that could work here....

> Are there any special consideration when comparing DOMStrings to enum values in the prose?

I think it's fine to just do that.  It's pretty clear how it should work, since every enum value matches up 1-1 with a string.
