### ISSUE TITLE
Clear Key should not use "A128KW" as the JWK "alg"

### ISSUE THREAD

**Issue by ddorwin** [w3c/encrypted-media#48]
Clear Key's License Format specifies JWK with an "alg" (algorithm) value of "A128KW".

The JSON Web Algorithms (JWA) registry [describes] (https://tools.ietf.org/html/draft-ietf-jose-json-web-algorithms-40#page-39) "A128KW"  as "AES Key Wrap using 128 bit key." However, Clear Key does not use key wrapping, so this is an incorrect description of the algorithm.

According to the JWK specification of the ["alg" parameter](https://tools.ietf.org/html/draft-ietf-jose-json-web-key-41#section-4.4):
> The values used  should either be registered in the
   IANA JSON Web Signature and Encryption Algorithms registry defined in
   [JWA] or be a value that contains a Collision-Resistant Name....
 Use of this member is OPTIONAL.

Rather than attempting to register "A128" or using some ugly Collision-Resistant Name, we should just drop "alg" from the specification. The implementation will use the key as specified by the container anyway.

**Comment by steelejoe** [comment]
This seems reasonable since usage of "alg" is OPTIONAL in the JWK spec as well.
