### ISSUE TITLE
[question] how to get list of media session handlers?

### ISSUE THREAD

**Issue by jimmywarting** [w3c/encrypted-media#481]
found out that you can add a list of action handlers using `navigator.mediaSession.setActionHandler`
but how do i get a list of what's supported? i have one media key that when i press it it opens up youtube.
how could i for example override that so it would open my website?

**Comment by mounirlamouri** [comment]
The standard is available here: https://www.w3.org/TR/mediasession/ and isn't related to Encrypted Media. I'm closing this ticket.
