### ISSUE TITLE
Update Key Statuses does not allow insight into each change

### ISSUE THREAD

**Issue by estobbart** [w3c/encrypted-media#489]
The [Update Key Statuses](https://w3c.github.io/encrypted-media/#update-key-statuses) algorithm can appear like duplicate events to a player when the changes are queued up for the same event loop. For example when a key is added, its status begins as pending but can very quickly become usable. When the player responds to the event and asks the MediaKeySession for the statuses, it only sees the most recent status of usable. But the event has fired twice, causing some confusion in player code. `pending` to `usable` is one scenario, but there could be others that the player may want insight to.

**Comment by joeyparrish** [comment]
Players can/should batch up key statuses and let them settle before processing.
