### ISSUE TITLE
Update "May Document use powerful features?" text to point to the latest version and language (Privileged Contexts)

### ISSUE THREAD

**Issue by ddorwin** [w3c/encrypted-media#49]
The reference to the "May Document use powerful features?" algorithm is outdated and the link is broken. It needs to be updated to reference the Privileged Contexts, which appears to live at https://w3c.github.io/webappsec/specs/powerfulfeatures/.

**Comment by ddorwin** [comment]
I appears that "[secure context](https://w3c.github.io/webappsec/specs/powerfulfeatures/#secure-context)" is the current term. We probably need to reference the [Is settings object a secure context?](https://w3c.github.io/webappsec/specs/powerfulfeatures/#settings-secure) algorithm following the [example](https://w3c.github.io/webappsec/specs/powerfulfeatures/#new).

**Comment by mwatson2** [comment]
https://github.com/w3c/encrypted-media/pull/67
