### ISSUE TITLE
Cannot add into chrome and firefox

### ISSUE THREAD

**Issue by zorrvo3** [w3c/encrypted-media#490]
Hi, is the any correct way to insert into chrome/forerox extension? Tried already but error due to manifest unreadable

**Comment by joeyparrish** [comment]
I don't understand your question, but here is some general information about Encryption Media Extensions (EME):

EME is the API that applications use to talk to the Content Decryption Module (CDM) inside the browser or operating system.  It can generate license requests, which the application forwards to a license server.  The CDM does not do any networking directly, and all network exchanges are controlled by the application.  When the CDM has a license, it can use that license to decrypt content played through HTML5 video or MediaSource.

Chrome and Firefox do not require extensions for EME.  EME is built in.

Does any of this help?

**Comment by zorrvo3** [comment]
May i know how to use this? What kind of software needed?

**Comment by joeyparrish** [comment]
EME is an API provided by the browser.  To use it, you build a media-streaming application in JavaScript.  This is generally only done for premium (paid) media services, and usually involves a combination of EME and MSE (MediaSource Extensions).

The specs detail the various objects and methods, and you can also find API documentation on the [Mozilla Developer Network (MDN)](https://developer.mozilla.org/).  This isn't really the forum for teaching you how to build an application from scratch, though.  This is an issue tracker for the specification itself.

If you want to get started quickly with a streaming media application without getting into the details of EME and MSE, you can use open-source tools such as Shaka Streamer to prepare media for streaming with the DASH or HLS standards, and you play that content back in a browser (using MSE and EME under the hood) using open-source JavaScript players such as Shaka Player.  (Disclosure:  I'm the team lead responsible for both the Shaka Player and Shaka Streamer projects, as well as an editor of the EME spec.)  There are plenty of other media tools out there, too, both open-source and commercial.

Does this help?

**Comment by zorrvo3** [comment]
thanks
