### ISSUE TITLE
xrefs to HTML need updated

### ISSUE THREAD

**Issue by gsnedders** [w3c/encrypted-media#491]
e.g. "resource fetch algorithm" should be https://html.spec.whatwg.org/multipage/media.html#concept-media-load-resource (v. the current https://www.w3.org/TR/html51/semantics-embedded-content.html#resource-fetch-algorithm which redirects to https://html.spec.whatwg.org/multipage/embedded-content.html#resource-fetch-algorithm, which is an anchor that doesn't exist there).

**Comment by gregwfreedman** [comment]
Closed in #506
