### ISSUE TITLE
Initialization Data Types SHOULD be supported independent of content types and other capabilities

### ISSUE THREAD

**Issue by ddorwin** [w3c/encrypted-media#5]
The Get Supported Configuration algorithm checks `initDataTypes` first. If an implementation was capable of supporting, for example, `"keyids"` and `"cenc"` but `"keyids"` was only supported for `"*/webm"`, a `MediaKeySystemConfiguration` that contained the following would fail because none of the videoCapabilities supports both of the supported `initDataTypes`.
```
initDataTypes: ["keyids", "cenc"],
videoCapabilities: [
         { contentType: "video/mp4; codecs=avc1.42E01E" }
]
```
Even if the following was added to the `videoCapabilities` sequence, the configuration would still fail unless `"video/webm`" can be used with `"cenc"`.
```
          { contentType: "video/webm; codecs='vp9'" }
```
Moving the `initDataTypes` check to the end of the algorithm does not solve this problem. To solve this, we would need to significantly complicate the already complex algorithm.

Fortunately, this should not be a problem in practice since license request generation, which implements Initialization Data Type support, and demuxing, which extracts the Initialization Data, are independent of the codecs. The only scenario that might be problematic is if different codecs were supported by different pipelines that supported different Initialization Data Types.

We should avoid adding complexity for such cases and instead recommend that implementations not restrict Initialization Data Types to specific content types and non-normatively explain the consequences.

**Comment by steelejoe** [comment]
I am not sure what the proposed text would look like here. Is the implication that a UA is required to be able to demux every possible initData type from every contentType?

**Comment by ddorwin** [comment]
>I am not sure what the proposed text would look like here.

The existing algorithm already implies this. Without supporting this assumption, applications need to use many more `MediaKeySystemConfiguration` entries than they would otherwise.

I think we would want to add a note to the algorithm calling out this behavior and perhaps document this requirement in Implementation Requirements.

>Is the implication that a UA is required to be able to demux every possible initData type from every contentType?

The intended implication was that the CDM must support all `initDataTypes` for which a positive result is returned _regardless of the content being decoded_. As I noted above, this should not be a problem since the license request generation is independent of decryption.

You bring up a good point about demuxing the initData in the UA. I think the implication is that the UA supports demuxing all the listed initData types from the containers that support them. For now, there is a 1:1 pairing for WebM and MP4. (It doesn't mean that the UA must be able to parse "webm" from an MP4 or "keyids" from WebM. If a UA added support for a new BMFF protection scheme, it seems reasonable to expect it to support both demuxing of and license generation based on the initData format for that scheme.

**Comment by steelejoe** [comment]
Ok, I agree with the recommendation. Hopefully this will not be an issue in practice but we should avoid it anyway.
