### ISSUE TITLE
Remove steps associated with cross-origin or non-clearable identifiers, as these are not allowed

### ISSUE THREAD

**Issue by mwatson2** [w3c/encrypted-media#51]
Section 3.1.2.1, step 15 includes a test for whether a distinctive identifier is unique per-origin and clearable and an "Otherwise" step. It is mandatory for distinctive identifiers to be unique per-origin and clearable, so this "Otherwise" step is not required.

**Comment by ddorwin** [comment]
This step had two purposes:
1. Include the unique per-origin and clearable requirements in the algorithms, where implementors are more likely to see them.
2. For implementations that do not or cannot meet these requirements (in violation of the spec), require user consent. (Of course, if an implementation is violating one part of the spec, it could easily violate this part as well. Still, there might be some implementations that are restricted by the platform but would prompt.)

Another way to accomplish (1) would be to normatively code the requirement into this algorithm by checking the condition explicitly (as it currently is) and reject the configuration if it is not met. For example, insert the following before the current step 15:
>If the Distinctive Identifier is not unique per-origin or is not clearable, return `null`.

We could then reference the Privacy Considerations section.

**Comment by mwatson2** [comment]
Actually, wouldn't it make more sense for the case where the distinctive identifier cannot meet the requirements to be handled the same as the case where consent is sought and denied ? That is, another configuration option proposed by the site may be allowed, rather than just returning null.

**Comment by ddorwin** [comment]
I think we're in agreement. Returning `null` from this algorithm (Get Supported Configuration, section 3.1.2.1) causes the calling algorithm to try the next configuration. `null` is already returned from steps 3, 5, 10, and 11.
