### ISSUE TITLE
Remove reference to keys in Initialization Data definition

### ISSUE THREAD

**Issue by steelejoe** [w3c/encrypted-media#52]
Specifically this sentence in the Initialization Data [Definition](https://w3c.github.io/encrypted-media/#definitions):
It MUST NOT contain application data, client-specific data, user-specific data, **key(s)**, or executable code.

Should become this sentence:
It MUST NOT contain application data, client-specific data, user-specific data, or executable code.

**Comment by steelejoe** [comment]
I forgot to add this reference. DASH-IF-OIP-v3.0 section 7.2 paragraph 5 has a specific reference to PSSH including keys.

**Comment by ddorwin** [comment]
Per the telecon, this would be resolved at the same time as (retitled) #41.

**Comment by jdsmith3000** [comment]
The ISO spec on Common Encryption is ISO_IEC_23001-7_2015(E).  It includes language in paragraph 9.1 that specifically says keys may be included in initiData.  We should not include conflicting requirements in the EME specification.

I see that this issue is listed as blocked on either issue #41 or issue #53.  I don't believe that is correct.  We should remove "keys" now from items prohibited in the initiData, and work these other two issues going forward.

**Comment by steelejoe** [comment]
Extracting from his last email on this subject -- David proposed this text: 
"However, in order to make the text more technically sound, I propose we remove "key(s)" from the current sentence and add: Implementations MUST NOT use Initialization Data for anything other than generating a license request. Specifically, Initialization Data or portions of it MUST NOT be persisted, used to configure the CDM or session, or used directly by the implementation to extract or derive key(s)."
We can append "unless explicitly stated in the algorithms" as appropriate when adding support for use cases (i.e. Issues 41 and 53) that need more flexibility.

My counter proposal is that we simply remove "key(s)" from the sentence as in my initial proposal -- making the new definition: 
"It MUST NOT contain application data, client-specific data, user-specific data, or executable code."

The spec already covers what can be persisted as part of a session. Any text restricting how the potentially DRM-specific initData is used by the CDM beyond its storage is outside of the scope of this spec.

**Comment by mwatson2** [comment]
+1 to Joe's last comment.

**Comment by steelejoe** [comment]
Adding a tie-in to the ongoing email thread -- 
https://lists.w3.org/Archives/Public/public-html-media/2015Sep/0003.html

**Comment by ddorwin** [comment]
My last email on the subject was actually [here](https://lists.w3.org/Archives/Public/public-html-media/2015Aug/0023.html). The updated proposal in that email sought to address @steelejoe’s and @mwatson2’s responses to the email quoted in @steelejoe’s August 30th comment. He replied to that thread yesterday, and I think we are now in more agreement than the recent comments above imply.

To avoid confusion and crossed replies, let’s continue the discussion on this specific issue here. I’ll make a pull request with my latest proposal.

For future reference, the discussion that led to this point is captured in the thread archived at the following links:
https://lists.w3.org/Archives/Public/public-html-media/2015Aug/thread.html#msg0
https://lists.w3.org/Archives/Public/public-html-media/2015Sep/thread.html#msg3

Per the discussion in that thread, I’ve removed the blocked label.

**Comment by jdsmith3000** [comment]
I recall this mail, but it appears to not disallow keys in the initData, but disallow using keys for content decryption.  If that’s the case, I disagree with your suggested edit, and believe we should instead focus on updating the algorithms as Joe has started to do in https://github.com/w3c/encrypted-media/issues/41.

Jerry

**Comment by ddorwin** [comment]
@jdsmith3000, I assume you meant to say something like "disallow using keys **in the initData directly** for content decryption." There are two suggested edits in my latest proposal - which do you disagree with? Do you disagree with the **accuracy** of my suggested text or dislike that this is the current state of the spec?

I am trying to resolve this issue in a manner consistent with the consensus in the discussion thread - that this issue is **not** blocked on #41 or #53. Are you proposing this issue **is** blocked on #41?

**Comment by mwatson2** [comment]
I think there is continuing confusion around what is meant by "directly"
using the content of initData (and what the other option, ("indirectly"?),
might mean).

First, I think we are all agreed that when encountered in a media file the
initData must be provided in the "encrypted" event and not processed in any
way (except perhaps sanitization). David's proposal to make that clear
seems good to me.

Now we are done with that, what remains is only to discuss how initData is
used when it is provided in the generateKeyRequest. In this context there
should be no restrictions on how it is used, *so long as the observable
behaviours follow the spec*. Unqualified text that restricts what can be in
the initData is interpreted as restricting what can be done with it in
generateKeyRequest. We should remove such text.

So, ... https://github.com/w3c/encrypted-media/pull/88

**Comment by ddorwin** [comment]
Although PR #88 includes one of my proposed additions, it goes well beyond the scope of this issue by removing the entire sentence containing “key(s).”

As I [commited to in my last reply to that thread](https://lists.w3.org/Archives/Public/public-html-media/2015Sep/0006.html), I have created PR #92. I believe it captures the agreed upon clarification and removal of “key(s)” and improves the flow of the Initialization Data definition without adding any restrictions. 

As I [mentioned earlier in that thread](https://lists.w3.org/Archives/Public/public-html-media/2015Aug/0023.html), I am also concerned about the potential for confusion around the current `generateRequest()` algorithm. PR #91 captures the second part of my proposal. There are **no** _new_ restrictions or behavioral changes - it clarifies the _existing_ behavior of the algorithm.

**Comment by mwatson2** [comment]
Sorry, David, I missed that you had promised a PR. I do think we should remove the other restrictions now that we have the clear requirements that initData not be processed when encountered, but your PR is find to address this issue.

**Comment by steelejoe** [comment]
I am fine with PR #92. This addresses the issue I was most concerned about. I think PR #91 will be made obsolete when ISSUE #41 is resolved, but I have no objection to including it until that is resolved.
