### ISSUE TITLE
Formal Analysis of EME

### ISSUE THREAD

**Issue by anonymous-submission-papers** [w3c/encrypted-media#522]
Dear Authors of EME,

I am an associate professor from the University of Rennes in France.
With my colleagues, we have formalized EME as instantiated by Widevine (arguably the most deployed DRM).
We use Tamarin to accomplish automated analysis regarding a new formalization of the concept of piracy.

If you are interested about our study, we can send you a draft. 

Regards,
Mohamed Sabt

**Comment by chrisn** [comment]
Thank you. I'm co-chair of the working group that is developing EME. We would be interested to read this. If you prefer not to share it publicly at this stage, you can find my contact details via my GitHub profile.

**Comment by Murmur** [comment]
@anonymous-submission-papers  Yes please am interested in your paper.
_(we = HbbTV DashDrm Refapp implementation)_

**Comment by tanalam** [comment]
@Mohamed Sabt
If possible do share me a copy as well.

BR
Tanweer

**Comment by anonymous-submission-papers** [comment]
I am glad that this piques your interest.
I sent our draft to @chrisn 
Hopefully, he will share it with the other editors.

Any comment about the draft is welcomed to push this topic forward.
You can reach me by email.
You can find my email on my web page: https://people.irisa.fr/Mohamed.Sabt

Regards,
Mohamed Sabt

**Comment by chrisn** [comment]
Hi Mohamed,

Thank you for sharing the report with us.

The EME specification is an interface to support platform-provided content protection systems on the web.

It’s not a goal for the EME APIs to affect or improve content security, which is the responsibility of the underlying platform-specific content protection system.

As such, our consideration of security focuses on user security, for example in the Security section of the spec https://www.w3.org/TR/encrypted-media/#security and in the W3C press release https://www.w3.org/press-releases/2017/eme-recommendation/.

The setServerCertificate() API was proposed to improve privacy (as the license request might have identifiable information). It was not designed to improve content security.

We suggest that discussions of the EME API should focus on interoperability, privacy, security and accessibility for users, and should not be driven by content security of a particular DRM system. Any content security concerns are best raised with the DRM providers themselves.

If you have further suggestions for the EME APIs, e.g., from a privacy or user security perspective, you are welcome to raise those as new issues.

**Comment by anonymous-submission-papers** [comment]
Hi Chris,

I would like to thank you as well as all the EME team for discussing our work.
I will follow your suggestion, and raise the issue directly to the concerned party.

Regards

**Comment by chrisn** [comment]
Thank you for contacting us about the work you've done, we genuinely appreciate it. I'll go ahead and close this issue.
