### ISSUE TITLE
EME-HDCP-VERSION-REGISTRY link is error 404 (not found)

### ISSUE THREAD

**Issue by alastor0325** [w3c/encrypted-media#544]
The link for [EME-HDCP-VERSION-REGISTRY](https://w3c.github.io/encrypted-media/#bib-eme-hdcp-version-registry) is invalid. [https://www.w3.org/TR/eme-hdcp-version-registry/](https://www.w3.org/TR/eme-hdcp-version-registry/) is error 404.

**Comment by chrisn** [comment]
Thanks, this will be fixed as part of publishing FPWD for EME v2 (tracked in https://github.com/w3c/encrypted-media/issues/501), as we'll publish the registry to /TR at the same time.

**Comment by tidoust** [comment]
Publication of the documents solved the issue. Links are now up and running.
