### ISSUE TITLE
Clarify that "resources" in close() method refers to non-persisted data

### ISSUE THREAD

**Issue by mwatson2** [w3c/encrypted-media#55]
The close() section says "release any resources associated with this object and close it".

"resources" is a general term that could be mis-understood to include persisted information. It should say "temporary resources" or "non-persisted data".

**Comment by steelejoe** [comment]
I agree. I vote for "temporary resources" instead of "resources". If necessary we can include a list of examples like file handles, mutexes, semaphores, memory, etc.

**Comment by ddorwin** [comment]
This makes sense. It was intended to mean "in-use" resources, such as platform resources. This would also include handles and memory as mentioned above.

"Temporary" seems too ambiguous (also, it could be confused with the session type). Persisted data should not be cleared, but specifically calling out "non-persisted data" could also be confusing. We could had a second sentence that explicitly says something like "Persisted data should not be released or cleared."

**Comment by jdsmith3000** [comment]
I agree with David's suggestion.  Leave a broader definition of resources and then explicitly say persisted data should not be cleared.
