### ISSUE TITLE
Examples incorrectly use single quotes for codecs

### ISSUE THREAD

**Issue by ddorwin** [w3c/encrypted-media#56]
According to https://tools.ietf.org/html/rfc6381#section-3.2, codecs must be surrounded with double quotes, not single quotes. The cleanest fix is to replace all double quotes with single quotes and vice versa.

**Comment by jdsmith3000** [comment]
This sounds like it's suggesting that contentTypes be changed from this format:
  { <a def-id="capability-contentType"></a>: "audio/webm; codecs='opus'" },

To this:
  { <a def-id="capability-contentType"></a>: 'audio/webm; codecs="opus"' },

Is this correct?

**Comment by mwatson2** [comment]
Yes, I believe so.

**Comment by jdsmith3000** [comment]
I’ve found other examples that follow this pattern in the HTML5 spec.  I’m going ahead with implementing.

**Comment by ddorwin** [comment]
Yes. For consistency, we should switch all strings from single quotes to double quotes. I think that's a manual process since the HTML source contains double quotes in this area.

**Comment by jdsmith3000** [comment]
So, all string values in sample source, or elsewhere as well?

**Comment by ddorwin** [comment]
Just the sample source I believe. Use of double quotes around enum value names in the normative specs seems to be the norm (and what ReSpec outputs).

**Comment by ddorwin** [comment]
Commit 5d32c74 also references this issue.
