### ISSUE TITLE
Update reference for CENC 2nd edition

### ISSUE THREAD

**Issue by ddorwin** [w3c/encrypted-media#64]
It looks like ISO/IEC 23001-7:2015 has been officially [published](https://www.iso.org/obp/ui/#iso:std:iso-iec:23001:-7:ed-2:v1). We should verify it contains the information `cenc-format.html` uses and that its use is still accurate then update the reference for CENC-2ND to `https://www.iso.org/obp/ui/#iso:std:iso-iec:23001:-7:ed-2:v1`.

Since "This second edition cancels and replaces the first edition...", we should probably replace references to CENC-1ST and perhaps just have a single CENC reference.

**Comment by mwatson2** [comment]
Note that under this issue we should update the reference, but we should not change the functionality that is required for compliance (that is, new things introduced in CENC v2 that were not in CENC v1 do not suddenly become required for compliance to this W3C specification). People should open separate issues to introduce that new functionality.

**Comment by mwatson2** [comment]
If people prefer to keep both references, we can revert 45bec71.

The main new feature v2 that was not in v1 is AES-CBC. Players that do not support AES-CBC should not be rendered unable to play compliant content by this reference update and so with this update we require streams to be AES-CTR as they were when we only referenced CENCv1. Support for AES-CBC should be discussed as a new issue if required.
