### ISSUE TITLE
Define key ID representation (byte order)

### ISSUE THREAD

**Issue by ddorwin** [w3c/encrypted-media#68]
`MediaKeyStatusMap` exposes key ID values to the application. We should clarify and eliminate all ambiguity about the representation of the IDs.

Since `keyStatuses` is populated from the license rather than media data, the representation could differ across implementations in a way that is visible to applications. For example, a license format using a GUID representation might need to take special care when exposing the IDs.

The simplest solution is probably to say that the bytes are to be presented as they would appear in media data (as defined by the container format spec). For example, the first byte in the stream would be byte 0 in the `BufferSource`.
Note: Any reference to the media data must refer to the common fields, such as the key ID to use for a given block, and not any system-specific fields, such as 'pssh' boxes, which could have the same issue.

Note: We may want to document the representation in/near the Key ID definition and refer to that from `MediaKeyStatusMap` to avoid any similar issues if key IDs are exposed in other ways. It may also be worth referencing in the Clear Key specification.

**Comment by mwatson2** [comment]
It's not clear to me that there is any ambiguity. If we define a Key ID to be a sequence of octets (we should say that in the definition), then the order (what is the "first octet" and what is the "last octet" etc.) is a thing independent of the representation. It is up to each representation of the Key ID to be clear about how the sequence order is reflected in the representation: for a BufferSource and a base64 string this is obvious. For a GUID it is not, but that's a matter for anywhere that wants to represent a Key ID as a GUID.

So, I suggest we just include in the definition of KeyID that it is a sequence of octets.

**Comment by paulbrucecotton** [comment]
At the Sapporo F2F meeting the attendees agreed with Mark's suggestion that we could just add that it is a sequence of octets with no other changes.  We need @ddorwin's feeback on this proposal.

**Comment by cpearce-mozilla** [comment]
I support the Key ID being defined as a sequence of octets.

**Comment by ddorwin** [comment]
@mwatson2's  proposal sounds good.
