### ISSUE TITLE
EME should not fire waiting or canplay events - use a separate mechanism

### ISSUE THREAD

**Issue by ddorwin** [w3c/encrypted-media#7]
There are a couple issues with the “waiting for a key” solution currently specified by EME. (See [bug 18515](https://www.w3.org/Bugs/Public/show_bug.cgi?id=18515) for background.) The first is the most important.

1) In the main HTML spec, the `waiting` and `canplay` events are fired on transitions in a `readyState` state machine.

The current EME spec fires these events but does not interact with the `readyState` state machine. This is problematic spec-wise and potentially for implementations (i.e. if they rely on readyState changes to fire events). 

I believe we previously decided not to modify `readyState` because it was perceived as related to network. If that is the case, we probably shouldn’t be using events based on `readyState` and thus network.

2) Maintaining the state of waitingFor is complex - in both the spec and potentially implementations - and, as previously noted, may have timing issues. This is perhaps a side effect of trying to inject into the `readyState` state machine.

For the replacement, we have two options:
A) Fully integrate into the `readyState` state machine.
B) Define independent event(s).

Since this is primarily intended to indicate problems with playback (vs. being actionable by the application), I propose we start with a simple to implement and understand solution:
* Revert the two changes made for [bug 18515](https://www.w3.org/Bugs/Public/show_bug.cgi?id=18515). This includes removal of the waitingFor attribute.
* Change the Queue a "waiting" Event algorithm to just fire a “waitingforkey” simple event (and rename it as such).
* Change the Attempt to Resume Playback If Necessary algorithm to not fire any events.

**Comment by ddorwin** [comment]
There was general agreement in the [telecon this week](http://www.w3.org/2015/01/13-html-media-minutes.html#item11). Jerry took an action to confirm there are no downsides to stripping out the `waitingFor` information.

**Comment by jdsmith3000** [comment]
waitingFor is set or used in these EME algorithms:

-	Encrypted Block Encountered
-	Queue a Waiting Event
-	Attempt to Resume Playback If Necessary
-	Playing the Media Resource Algorithm Modifications

Only Attempt to Resume Playback actually uses the value.  The others just set it.  In Attempt to Resume Playback, the value must be waitingFor “keys” for resumption to be attempted.  I believe this may have been one reason we created this attribute.  Keys may be received early or late, which means only a subset of scenarios will require attempting to resume playback.  We will likely want language here that attempts to resume playback only if the media element is not currently playing.

It seems unlikely that apps will need access to this information, and can be adequately serviced with events.

**Comment by steelejoe** [comment]
This sounds reasonable. I don't see any obvious negative impacts.

**Comment by ddorwin** [comment]
In the telecon today, we agreed ([minutes](http://www.w3.org/2015/01/20-html-media-minutes.html#item05)) to resolve as discussed last week and proposed in the original report.
