### ISSUE TITLE
Define the behavior of MediaKeyStatusMap::get(keyId) when |keyId| is not in the map

### ISSUE THREAD

**Issue by ddorwin** [w3c/encrypted-media#70]
The definition of `MediaKeyStatusMap`'s `get(BufferSource keyId)` method is currently:
> Returns the MediaKeyStatus of the key identified by keyId.

It does not say what happens or is returned if `keyId` is not in the map and thus there is no value for it.

To be consistent with the [ES6 Map interface's get()](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-map.prototype.get), this method should return `undefined`.

**Comment by mwatson2** [comment]
I assume the method should return `undefined` in the same circumstances as the has method returns `false`.
