### ISSUE TITLE
Explicitly define the initial state of the `keyStatuses` attribute

### ISSUE THREAD

**Issue by ddorwin** [w3c/encrypted-media#72]
Step 2.4 of the `createSession()` algorithm currently says:
>Let the keyStatuses attribute be empty.

However, there is no explicit definition of what that means or how to construct a MediaKeyStatusMap.

For consistency, we should probably use something like step 2. For example
>Let session be a new MediaKeyStatusMap object, and initialize it as follows:
  1. ...

**Comment by jdsmith3000** [comment]
I believe that only the size attribute needs to be initialized for this.  In my change:

4.Let key status be a new MediaKeyStatusMap object, and initialize it as follows:
    1.Let the size attribute be NaN.

**Comment by ddorwin** [comment]
I commented in the commit (d3b17ea93df230b165969c3c3b4f7c4fa6dcf16d).

**Comment by jdsmith3000** [comment]
I need to address David's comments before this issue can be closed.

**Comment by cpearce-mozilla** [comment]
@jdsmith3000 MediaKeyStatusMap.size is of type "unsigned long". NaN isn't a valid value for this type, it's only valid for "unrestricted float", "unrestricted double", and "any". So shouldn't the size be initialized to 0 instead?

**Comment by jdsmith3000** [comment]
I picked up @ddorwin's comments in my previous commit, including initializing size to 0.

**Comment by jdsmith3000** [comment]
Fix checked in 12 days ago.  Issue should be closed.
