### ISSUE TITLE
Get Supported Capabilities for Media Type algorithm uses both "media type" and "media types"

### ISSUE THREAD

**Issue by ddorwin** [w3c/encrypted-media#73]
As identified in #12, the [Get Supported Capabilities for Media Type algorithm](https://w3c.github.io/encrypted-media/#get-supported-capabilities-for-media-type) has a parameter named "media type" (for Audio vs. Video) and a local variable named "media types" (for codecs, etc.). This could be confusing, so we should rename one or both of them. Note that "media types" could contain more than codecs if supported by a UA. (RFC6381 also defines profiles.)

I also wonder whether the "set of media types" in "Let media types be the set of media types specified by parameters" is generalizable. It certainly works for codecs, but what about other (potential) parameters?

**Comment by paulbrucecotton** [comment]
As per the discussion at the Jul 21 meeting, let's just pick a replacement name for the "media type" parameter and move on.
http://www.w3.org/2015/07/21-html-media-minutes.html#item04

I suggest we simply change the parameter name "media type" to "type" to resolve the first part of this ISSUE.

**Comment by jdsmith3000** [comment]
I don’t want to bike shed, but think we should find a term that distinguishes media type from content, session and initData types that we use in the spec.  Perhaps “Audio/Video Type”, since that’s what is meant by our usage.

Jerry

**Comment by paulbrucecotton** [comment]
>Perhaps “Audio/Video Type”, since that’s what is meant by our usage.

I can live with this.  

Please self-assign issue and make the changes.

**Comment by ddorwin** [comment]
The commit above changed **both** uses of "media type(s)" to the new name. The plural version that applies to the codecs needs to be changed back (or to something else).
