### ISSUE TITLE
The WebIDL reference points to the first edition

### ISSUE THREAD

**Issue by ddorwin** [w3c/encrypted-media#74]
https://w3c.github.io/encrypted-media/#bib-WebIDL refers to the [2012 version](http://www.w3.org/TR/WebIDL/), the first edition. This is may actually be fine for some uses instances of "[WebIDL]". However, others appear after links to the [second edition](https://heycam.github.io/webidl/) and a lot of the Web IDL in the spec relies on features only in the second edition. In particular, Promises and `MediaKeyStatusMap`.

There is a previous and still unresolved discussion beginning at https://www.w3.org/Bugs/Public/show_bug.cgi?id=26573#c5. Regardless of the process issues, we should make our reference correct, and that is what this issue tracks.

Related question: Should our Web IDL somehow include a normative reference to the second edition of "[WebIDL]" or is it sufficient to have a normative reference somewhere in the doc.

**Comment by paulbrucecotton** [comment]
>Related question: Should our Web IDL somehow include a normative reference to the second edition of "[WebIDL]" or is it sufficient to have a normative reference somewhere in the doc.

I suggest we add a [WebIDL2] reference and use it for references that are ONLY in V2.

**Comment by ddorwin** [comment]
As discussed in the telecon, we'll follow Paul's suggestion.

**Comment by paulbrucecotton** [comment]
For further input on using WebIDL v1 versions v2 features see:
https://www.w3.org/Bugs/Public/show_bug.cgi?id=26573#c11
https://www.w3.org/Bugs/Public/show_bug.cgi?id=26573#c12

/paulc

**Comment by paulbrucecotton** [comment]
The Web Applications Working Group has published a Working Draft of WebIDL Level 1:
http://www.w3.org/TR/2015/WD-WebIDL-1-20150804/

**Comment by ddorwin** [comment]
It looks like ReSpec might have fixed this for us as the "[WebIDL]" Reference now refers to http://www.w3.org/TR/WebIDL-1/. I opened issue #107 to update inline URLs.

It appears that all features we use are in Level 1. I'll update #107 to include confirmation of this.
