### ISSUE TITLE
Define behavior for implementations that delay playback until setMediaKeys() is called

### ISSUE THREAD

**Issue by ddorwin** [w3c/encrypted-media#8]
Because the selection of a key system can affect the pipeline and/or decoders used, some implementations MAY delay playback of media resources that may contain encrypted blocks (i.e. when Initialization Data [is] Encountered during demuxing) until a Key System is specified by passing a `MediaKeys` object to `setMediaKeys()`.

There is currently a non-normative note that acknowledges this:
> As a best practice, applications should create a `MediaKeys` object and call `setMediaKeys()` before providing media data (for example, setting the `src` attribute). This avoids potential delays in some implementations.

We should normatively define the behavior for such implementations.

I propose adding a step to the end of the [Initialization Data Encountered](https://w3c.github.io/encrypted-media/#initdata-encountered) algorithm that says such implementations will:
1. Run the queue a "waiting" event algorithm on the media element.
2. Wait for a signal to resume playback.
(These are the same steps that are run when the needed key is not available (or `mediaKeys` has not been set) when an [Encrypted Block [is] Encountered] (https://w3c.github.io/encrypted-media/#encrypted-block-encountered).

**Comment by ddorwin** [comment]
Since this involves the waiting logic, we should wait until #7 is resolved.

**Comment by jdsmith3000** [comment]
I agree with making this guidance normative.

**Comment by ddorwin** [comment]
Some clarification: There are implementations that will delay playback of potentially encrypted media until a `MediaKeys` (and thus media pipeline) has been attached. For more information, see [bug 19156](https://www.w3.org/Bugs/Public/show_bug.cgi?id=19156#c0).

This is the reason for the non-normative note - applications can avoid such a delay by specifying the `MediaKeys` (and thus media pipeline).

However, it's not clear why calling `setMediaKeys()` immediately after setting the source is not also sufficient. Adrian [suggested  this order in bug 19156](https://www.w3.org/Bugs/Public/show_bug.cgi?id=19156#c2). We can consider fixing this.

For reference, this note was originally committed [here](https://github.com/w3c/encrypted-media/commit/3641e615bf4394890e4c3ddcd473963e71e249b7).

**Comment by steelejoe** [comment]
I agree with the proposal to add a wait step to the "Initialization Data Encountered" algorithm.

**Comment by ddorwin** [comment]
A few comments:
 1. The new step is missing a condition.
   * We don't want to require that all implementations block playback, which is what the current step does.
   * Therefore, we need to add something like "... and the implementation requires specification of a MediaKeys object before decoding potentially-encrypted media data..."
   * We can add text to the non-normative note that explains that selection of a key system can affect the pipeline and/or decoders used so some implementations delay playback of media resources that may contain encrypted blocks until a CDM is specified by passing a `MediaKeys` object to `setMediaKeys()`.
 1. The existing non-normative note is incorrect. It should say something like "These steps may be reached when the application provides media data before calling `setMediaKeys()` to provide a `MediaKeys` object."
 1. I think we should remove the non-normative note. I believe the algorithms now handle both cases and there is no need to prefer one over the other. The note actually discourages use of "encrypted" events to initiate the EME flow.

**Comment by jdsmith3000** [comment]
Since mediaKeys is null, it's not been set and that requires the existence of a MediaKeys object, right?  To me, your additional condition seems implied.  Is your proposed addition a missing condition, or a clarification?

I agree the non-normative note is more accurate with your proposed change.  I don't see it as much different though then others in the initData encountered algorithm, and would probably leave it in.

**Comment by jdsmith3000** [comment]
Change modified step 5 of the initialization Data Encountered algorithm to:

If the media element's mediaKeys attribute is null and the implementation requires specification of a MediaKeys object before decoding potentially-encrypted media data, run the following steps:

NOTE
These steps may be reached when the application provides media data before calling setMediaKeys() to provide a mediaKeys object. Selection of a key system can affect the pipeline and/or decoders used so some implementations may delay playback of media resources that may contain encrypted blocks until a CDM is specified by passing a mediaKeys object to setMediaKeys().

* Run the Queue a "waitingforkey" Event algorithm on the media element.

* Wait for a signal to resume playback.
