### ISSUE TITLE
"tracked" sessions: record of usage should track session usage, not individual key usage

### ISSUE THREAD

**Issue by ddorwin** [w3c/encrypted-media#80]
The text from pull request #54 says "the record of key usage" contains an "entry for block key ID." This means that there is a record of usage for each key in the session. This granularity seems unnecessary and has costs, including:

1. Complicating the CDM, license protocol, and license server implementation
2. Requiring the author's server to aggregate the intervals from all keys to come up with the total playback period for the session

The spec generally treats sessions as a single entity, including closing, removing, and expiration time, and it's unclear why this should be different. If an author really needs different usage data, he or she can use multiple sessions.

**Comment by mwatson2** [comment]
Agreed. We should record the overall start and end times and the ids of the keys that were available.

**Comment by jdsmith3000** [comment]
Tracking by session rather than individual keys aligns with Microsoft's thinking.  We support this recommendation.

**Comment by paulbrucecotton** [comment]
If we have initial agreement here, can one of editors volunteer to prepare a pull request for this issue?

**Comment by mwatson2** [comment]
Yes, I will do that. So for the others where there is agreement or at least
a direction to discuss in more detail.

...Mark

Sent from my iPhone

On Sep 3, 2015, at 6:55 AM, Paul Cotton <notifications@github.com> wrote:

If we have initial agreement here, can one of editors volunteer to prepare
a pull request for this issue?

—
Reply to this email directly or view it on GitHub
<https://github.com/w3c/encrypted-media/issues/80#issuecomment-137455870>.

**Comment by mwatson2** [comment]
PR: https://github.com/w3c/encrypted-media/pull/87
