### ISSUE TITLE
"tracked" sessions: "record of key usage" is undefined

### ISSUE THREAD

**Issue by ddorwin** [w3c/encrypted-media#81]
_record of key usage_, which was added by pull request #54, is used as a variable in several algorithms but not clearly defined anywhere. It should probably be "this object's _record of key usage_" and be initialized in `createSession()`.

In addition, it would probably be helpful to provide information about the variable. For example, that the record contains entries, as referenced in section 7.5.2 [Encrypted Block Encountered](https://w3c.github.io/encrypted-media/#encrypted-block-encountered). It might also help to make it plural somehow, since it has records for all keys in the session. (Both of these will be moot if the change proposed by #80 is made.)

_first decrypt time_ and _latest decrypt time_ are also undefined in section 7.5.2

**Comment by mwatson2** [comment]
The *record of key usage* is defined in the description of the "tracked" session type in Section 5. I agree we should explicitly initialize it.

**Comment by mwatson2** [comment]
I believe this is addressed by the changes proposed in https://github.com/w3c/encrypted-media/pull/87

**Comment by mwatson2** [comment]
Addressed by PR #87.
