### ISSUE TITLE
"tracked" sessions: when to persist "record of key usage" is not specified

### ISSUE THREAD

**Issue by ddorwin** [w3c/encrypted-media#82]
Pull request #54 added text to section 7.5.2, the [Encrypted Block Encountered](https://w3c.github.io/encrypted-media/#encrypted-block-encountered) algorithm, that specifies modification of an entry of the "record of key usage". However, that record and the behavior around it is not specified. As has been [previously discussed](https://lists.w3.org/Archives/Public/public-html-media/2015Jun/0021.html), there are specific implementation requirements in order for such records to be useful to the author. These should be specified.

The method that is technically possible for most user agents involves storing such records in (tamper-resistant) memory then persisting the record when the license/keys are destroyed.

Therefore:
* The steps in 7.5.2 should have a Note to be clear that the data should not be persisted at that point.
* The algorithms related to license/key destruction should be updated to include persisting the "record of key usage." I believe this includes the Session Close algorithm and the remove() algorithm.

**Comment by mwatson2** [comment]
Requirements on exactly how this is implemented arise from the fact that CDMs are subject to robustness rules. This applies to other aspects of EME as well but we have not so far discussed robustness in our specification. What should be the rule for deciding which robustness aspects we need to address in the specification and which we do not ?

**Comment by ddorwin** [comment]
From previous discussions, I think we agree that:
* The usage records must be persisted to be effective in handling some cases, such as non-graceful close.
* Without certain platform capabilities, persisting the records at the wrong time leads to an unusable implementation.

This issue is requesting definition of the observable behavior in the algorithms as well as any additional information (not covered in the algorithms) necessary to ensure an implementation is interoperable and usable. This does not prevent implementations from using platform capabilities to enable greater protection (“robustness”) of the storage or optimizations, as long as the observable behavior is consistent with the algorithms.

**Comment by mwatson2** [comment]
I agree the observable behavior should be clear and I'll review the current text in the light of the points above (next week).

However, I'm still stuck on how we should decide which robustness aspects to address and which not. For example, with persistent sessions, CDMs can support features such as play counts or license expiration (e.g. 24 hour rental) for offline playback which typically, in practice, require certain robustness features of the persistent store and clocks, but we do not address this at all in our specification. The presence or absence of the robustness features does not affect the behavior on the API. The level of robustness required is up to service providers. Should we address all this too ?

**Comment by mwatson2** [comment]
We discussed this on the telco and there's reluctance to go down the path of specifying requirements that are derived only from robustness rules - this could be a can of worms.

In this instance we should specify that the _record of key usage_ is persisted _at the latest_ when the keys are destroyed. This is sufficient to define the observable behavior.

**Comment by mwatson2** [comment]
Actually, we explicitly state that the presence of a persisted _record of key usage_ indicates that the keys were destroyed. So, in terms of defining observable behavior, we should require that persistence occurs at the time the keys are destroyed.

The approach of persisting to secure store during playback is an implementation approach with the same observable behavior.

**Comment by mwatson2** [comment]
https://github.com/w3c/encrypted-media/pull/89

**Comment by ddorwin** [comment]
I agree with the [comment before the pull request](#issuecomment-137501251), and #89 captures this in prose. We might want to add “securely” to “persisting” in the Note as a hint at the issues I mentioned in the original description.

In addition, the algorithms should be updated such that "persistence occurs at the time the keys are destroyed" as I suggested in the last bullet of the original description. (See also the discussion of prose vs. algorithms in #83.)

**Comment by mwatson2** [comment]
We can update the algorithms for the times the keys are explicitly destroyed but there are other times keys are destroyed where the record of key usage may still be persisted.

Regarding "securely", everything that is persisted (e.g. licenses) in practice needs to be persisted "securely". As per the comments above, I don't think we should go into that since exactly what "securely" means is very complex.

**Comment by mwatson2** [comment]
I've updated the PR to be explicit in the algorithms about when the record of key usage is stored. This happens in the remove() method and the Session Close algorithm. I noticed that the Session Close algorithm did not explicitly say in its procedures that licenses and keys would be destroyed (it was just in the prose) so I have added that as well.

**Comment by mwatson2** [comment]
Per comments on PR#89 we are waiting for Issue #80 to be resolved before resolving this one.
