### ISSUE TITLE
"tracked" sessions: Does "record of key usage" need not be updated each time a block is decrypted?

### ISSUE THREAD

**Issue by ddorwin** [w3c/encrypted-media#83]
Pull request #54 specifies that the _record of key usage_ be updated every time a key is used to decrypt a block. I wonder whether we need to _require_ this level of granularity. We should definitely be clear about what authors can expect and the minimum granularity implementations must achieve, but I'm not sure requiring per-decrypted-block granularity is necessary to support the relevant use cases for the `"tracked"` session feature.

The reasonable minimum granularity probably depends on when this information is persisted. Thus, this issue is blocked on issue #82. Issue #80, whether to track key or session usage, may also affect this issue.

**Comment by mwatson2** [comment]
I agree that the per block granularity should not be required. I think we could leave the actual granularity as CDM-specific.

**Comment by mwatson2** [comment]
I think this issue can be addressed by addressing the required accuracy of the time fields in the _record of key usage_. Specifically, we should indicate that this is implementation-dependent. If there is agreement we could specify a minimum accuracy.

Keeping the updates on the block decrypted procedure allows for implementations to support whatever accuracy they choose. Obviously, an implementation does not have to actually update the record more often than the accuracy it supports to achieve the correct observable behavior.

**Comment by ddorwin** [comment]
SGTM. Since the algorithms are supposed to define the observable behavior, we should make it clear in the block decryption algorithm that implementations may choose not to update every time. One idea would be to add text similar to "The user agent may choose to skip this step if..." that follows a couple of "Queue a task to run the attempt to resume playback if necessary algorithm..." steps.

**Comment by mwatson2** [comment]
It's a general rule that user agents can follow whatever algorithm they like as long as the observable behavior matches the specification-defined algorithm. I'm (mildly) concerned that if we call out this rule in specific places it gives the impression that perhaps the rule doesn't apply in other places. Of course I'm guilty myself of proposing it be called out with respect to persistence of the _record of key usage_. I guess we should use such call-outs sparingly, where there really has been some confusion or mis-understanding. Is this one of those cases ?

**Comment by ddorwin** [comment]
I agree with what you said, though I'm not sure it applies in this case.

I think it probably applies more to the existing examples I cited. I'd have to double check, but there might not be any observable difference in behavior if the "attempt to resume playback if necessary" algorithm is not run. That was intended as a note to implementers that they don't have to follow the algorithm explicitly and to authors about what to expect from implementations. However, it may not be necessary for the former, as you noted, and the latter may not observe any difference.

In this case, however, the algorithm currently specifies block-accurate times. Thus, no matter how the feature is actually implemented, the time of decryption of the last block should be provided to the application. Since we do not intend to require such observable behavior, the algorithms should make this clear in some way.

That could be with a statement after the step like I suggested above or by actually making the step conditional in some way. The latter is probably even better. For example, "if the time since the last record is greater than _tolerance_, set the latest decrypt time..." We would need to define _tolerance_ somewhere, including that it is implementation dependent [up to some threshold]. We might even move the entire condition to a separate algorithm where this can be described.

**Comment by mwatson2** [comment]
I was assuming that we would indeed explicitly say somewhere that the tolerance / accuracy of the times is implementation-specific and possibly provide a minimum accuracy if there is agreement. If we add that text, do we need to say anything in the algorithms ?

**Comment by ddorwin** [comment]
In general, I think it’s best to specify things in algorithms where possible. They are more likely to be read by implementers, and my understanding is that tests are usually associated with algorithm steps.

In this case, I think we have a couple of simple options for referencing tolerance/accuracy in the algorithms and either linking to a definition of what is acceptable or including it in its own algorithm.

**Comment by mwatson2** [comment]
WDYT: https://github.com/w3c/encrypted-media/pull/93

**Comment by mwatson2** [comment]
@ddorwin, all: is this one good to go, or still on your list(s) to review ?
