### ISSUE TITLE
"tracked" sessions: document usage for limiting concurrent streams

### ISSUE THREAD

**Issue by ddorwin** [w3c/encrypted-media#84]
Given the complexity and relative inexperience of people in this group and the industry with using "tracked" sessions for limiting concurrent streams as well as open questions ([example](https://lists.w3.org/Archives/Public/public-html-media/2015Aug/0029.html)), it would be helpful to document how the “record of key usage times” provided by "tracked" sessions is intended to be used. This would be useful and important for members of this group to understand the feature and ensure it is adequately and accurately defined, authors considering using “tracked” sessions, and anyone else evaluating the spec.

Specific topics include:
* What times are expected
* Other assumed mechanisms, such as heartbeats and fire-and-forget end-of-session messages
* How to handle unexpected values or missing records
* Differentiating abuse/fraud from legitimate use cases
* Enforcement and/or clamping down to prevent abuse/fraud
* What happens in various use cases, such as non-graceful tab/browser closes, closing a laptop lid, and crashes.

It doesn’t necessarily need to be in the spec, but it needs to be somewhere that authors, implementers, and spec reviewers can reference. This issue tracks that need.

**Comment by mwatson2** [comment]
I'm happy to draft something like this. Any ideas on where it should be documented ? Should this actually be in the form of an extended example / sample code ?

**Comment by paulbrucecotton** [comment]
We could draft this using the usual WD template, indicate it is NOT on the Recommendation track and then publish the content when stable as a WG Note.
http://www.w3.org/2014/Process-20140801/#Note

**Comment by mwatson2** [comment]
If we go the path of a WG note, then we should probably include similar material for other features of the specification - the basic license flow - capability discovery - offline licenses - license renewal etc. Basically everything we have on our Use-Cases Wiki.

**Comment by paulbrucecotton** [comment]
Another option would be to just expand the Use-Cases Wiki itself which gives us the option of more easily crowd-sourcing the material and keeping it up to date if we get questions later.

**Comment by ddorwin** [comment]
> Should this actually be in the form of an extended example / sample code ?

Most of the topics relate to server side handling and interpretation of the data. Pseudo code or sample algorithms might be useful for some explanations, but I don't think that will be the primary form.

**Comment by mwatson2** [comment]
As per WG call today, I'll put a proposal up on the Wiki and then we can decide whether any different form of publication is necessary.

**Comment by mwatson2** [comment]
I have added some material to the wiki [1]. Some of David's questions were already answered in the existing wiki text. Could WG members review the new wiki text and comment on whether it is sufficient ?

[1] https://www.w3.org/wiki/HTML/Media_Task_Force/EME_Use_Cases#Example_usage

**Comment by steelejoe** [comment]
The algorithm described seems reasonable. It would be clearer if the wiki indicated that the algorithm is running on the service providers site. The use of Javascript for the algorithm makes it a little murky whether this could be running on the client side. In many cases you could not run this on the client side because the key release message is opaque to the client because of encryption. It also might be worth clarifying whether the "accuracy" is something provided directly by the client, or inferred on the service side based on the Key System, browser and/or platform in use.

**Comment by mwatson2** [comment]
Thanks Joe. I've updated the Wiki to address these comments.
