### ISSUE TITLE
Consider reasons other than Distinctive Identifier in the steps of the Consent Status algorithm

### ISSUE THREAD

**Issue by ddorwin** [w3c/encrypted-media#96]
PR #66 adds a "Get Distinctive Identifier Consent Status" algorithm that determines whether user consent is necessary. There are two areas for improvement:

1. The algorithm takes an <var>accumulated configuration</var> but doesn't use it.
2. The step being refactored contains a note that "Implementations MAY require consent for other reasons, such as the security properties of the CDM implementation." This could be made into a step that would fit better in the algorithm ([original suggestion](https://github.com/mwatson2/encrypted-media/commit/0d33734864311d6c61ad0f1af3f2213fd0611e39#commitcomment-13354947)).

Addressing (2) may use <var>accumulated configuration</var>.

I'll work on this after #66 is merged.

**Comment by mwatson2** [comment]
This issue is addressed in the PR for issue #57 (PR #165)

**Comment by mwatson2** [comment]
This is expected to be solved by #57

**Comment by mwatson2** [comment]
#57 is now closed.
