### ISSUE TITLE
Editorial: Algorithm references use title case inconsistently

### ISSUE THREAD

**Issue by ddorwin** [w3c/encrypted-media#97]
When the spec references algorithms, as in "run foo bar algorithm," the case of the first letters is inconsistent. We have:
* foo bar (e.g. encrypted block encountered)
* Foo Bar (e.g. Get Supported Configuration)
* Foo bar? (e.g. Are insecure contexts allowed?)

We should pick one and make them consistent. Some of these are specified in encrypted-media.js, but there is at least one that is not.

**Comment by ddorwin** [comment]
In the telecon, @jdsmith3000 expressed a preference for having all words capitalized. I propose that the algorithm reference use the same case as the section title for the algorithm. That is simple and should effectively be consistent with Jerry's preference.

Details: Most section names (e.g. Get Supported Configuration) already use title case. However, there are a couple algorithms that are question sentences (e.g.  Are insecure contexts allowed?) Should we capitalize those section names as well? It looks like those are the only section titles that are not capitalized, so we probably should. Thus, all section titles should use title case.

**Comment by jdsmith3000** [comment]
This is a good point.  I preferred capitalizing each word because most algorithm references seem like proper names.  Ones that read as a sentence don’t seem to fit that reasoning.

**Comment by jdsmith3000** [comment]
Updated these algorithm references to match:

3.1.2.1 Get Supported Configuration
3.1.2.2 Get Supported Capabilities for Audio/Video Type
3.1.2.3 Are insecure contexts allowed? - DEPRECATED
3.1.2.4 Get Distinctive Identifier Consent Status
5.2.1 Is persistent session type?
6.6.1 Queue a "message" Event
6.6.2 Update Key Statuses
6.6.3 Update Expiration
6.6.4 Session Close
7.5.1 Initialization Data Encountered
7.5.2 Encrypted Block Encountered
7.5.3 Queue a "waitingforkey" Event
7.5.4 Attempt to Resume Playback If Necessary

**Comment by ddorwin** [comment]
For what it's worth, algorithm names are not capitalized at all in the HTML5 spec. For example, the [resource fetch algorithm](http://www.w3.org/TR/html5/embedded-content-0.html#concept-media-load-resource). However, that spec does not use sections for algorithms like EME does.
