### ISSUE TITLE
Remove note recommending setMediaKeys() be called before providing media data

### ISSUE THREAD

**Issue by ddorwin** [w3c/encrypted-media#99]
This is the remaining item from the discussion in  #8.

The spec currently contains the following non-normative note:

> As a best practice, applications should create a `MediaKeys` object and call `setMediaKeys()` before providing media data (for example, setting the `src` attribute). This avoids potential delays in some implementations.

@adrianba [suggested this order in bug 19156](https://www.w3.org/Bugs/Public/show_bug.cgi?id=19156#c2), and the note was originally committed in 3641e615bf4394890e4c3ddcd473963e71e249b7.

There may be a delay as the fix for #8 acknowledges, but it's not clear that the delay would be differ based on the order. In addition, the note discourages use of `encrypted` events to initiate the EME flow.

I recommend we remove the note.

**Comment by ddorwin** [comment]
Assigning to Jerry to review.

**Comment by jdsmith3000** [comment]
I believe we were considering using this as a hint for building a protected media pipeline, but are not using it for that purpose.  I'm not aware of a compelling reason to keep this comment in the spec.

**Comment by steelejoe** [comment]
I don't think this needs to be in this spec since it is not universally applicable.

**Comment by jdsmith3000** [comment]
I've removed this non-normative note under setMediaKeys:

*As a best practice, applications should create a  MediaKeys  object and call  setMediaKeys()  before providing media data (for example, setting the  src  attribute). This avoids potential delays in some implementations.*

**Comment by jdsmith3000** [comment]
I've not seen any objections to the committed fix, so am closing this issue.
